### ISSUE TITLE
Converting raster from float to integer fails on misspelled datatype argument

### ISSUE THREAD

**Issue by jsta** [rspatial/raster#1]
Conversion of a raster from float to integer using `writeRaster` silently fails, if the `datatype` argument is misspelled as `dataType`.

```
library(raster)
#> Loading required package: sp

t_file <- tempfile(fileext = ".tif")
v <- c(rep(1, 25), rep(0, 50), rep(NA, 25))

m <- matrix(v, 10, 10)
r <- raster(m)
dataType(r)
#> [1] "FLT4S"

writeRaster(r, t_file, datatype = "INT2U", overwrite = TRUE)
dataType(raster(t_file))
#> [1] "INT2U"

writeRaster(r, t_file, dataType = "INT2U", overwrite = TRUE)
dataType(raster(t_file))
#> [1] "FLT4S"
```

[According to @rsbivand](https://stat.ethz.ch/pipermail/r-sig-geo/2018-August/026809.html) the underlying problem is that `dataType=` is going into `...`, and because 
nothing needs it, it isn't spotted.

**Comment by rhijmans** [comment]
Thanks for bringing this up. Ignoring misspelled arguments comes with the territory of using ellipses. But I now catch this one. That seems reasonable as this may be a common mistake due to confusion with the dataType method.
