### ISSUE TITLE
extract with default arguments misses small intersection

### ISSUE THREAD

**Issue by dbaston** [rspatial/raster#100]
As discussed here: https://gis.stackexchange.com/questions/353135/check-for-intersection-of-raster-and-vector-in-r

Example:

```
library(raster)
library(sf)

r <- raster(matrix(1:100, nrow=10, ncol=10), xmn=0, xmx=1, ymn=0, ymx=1)
p <- st_as_sfc('POLYGON ((0.90 1.05, 1.05 0.95, 1.05 1.05, 0.90 1.05))')

plot(r)
plot(p, add=TRUE)

extract(r, as(p, 'Spatial'))
# [[1]]
# [1] NA
```

**Comment by rhijmans** [comment]
Thanks for reporting. It is not a bug but the documentation of `small=TRUE` does not cover the case when the polygon is *very* small, that is, not covering any of the centroids of 100 virtual sub-cells. I will adjust the docs for now, but will consider changing this behavior as well. You can work around it by also using extract with a line.  See below 


```
library(raster)
library(sf)
r <- raster(vals=1:100, nrow=10, ncol=10, xmn=0, xmx=1, ymn=0, ymx=1)
p <- st_as_sfc('POLYGON ((0.90 1.05, 1.05 0.95, 1.05 1.05, 0.90 1.05))')
poly <- as(p, "Spatial")
line <- as(poly, "SpatialLines")
extract(r,  poly)
#[[1]]
#[1] NA
extract(r,  line)
#[[1]]
#[1] 10
```

**Comment by dbaston** [comment]
Is it the size of the polygon, or the fact that it has no vertices in the raster? If I density the polygon (not changing the size) I get a different result:

```
library(raster)
library(sf)

r <- raster(matrix(1:100, nrow=10, ncol=10), xmn=0, xmx=1, ymn=0, ymx=1)
p <- st_as_sfc('POLYGON ((0.90 1.05, 1.05 0.95, 1.05 1.05, 0.90 1.05))')

plot(r)
plot(p, add=TRUE)

extract(r, as(p, 'Spatial'))
```

**Comment by rhijmans** [comment]
It is neither --- as I explained above.  Also, I get the same result with this example.

**Comment by rhijmans** [comment]
I am not going to fix this. I am putting all my effort in `terra` instead.
