### ISSUE TITLE
couldBeLonLat generic now fails for Extent

### ISSUE THREAD

**Issue by mdsumner** [rspatial/raster#102]
I have packages that rely on old behaviour of the bare 'couldBeLonLat' function. 

IIUC, this was made internal as `.couldBeLonLat`, with a simplified S4 generic and now has methods for 'BasicRaster' and 'Spatial', but not for 'Extent'. 

Could a method be added for 'Extent'? (or just catch all with "ANY"?)  The underlying logic is still there. 

```R
raster::couldBeLonLat(raster::extent(100, 120, -50, -20))
# Error in (function (classes, fdef, mtable)  : 
#  unable to find an inherited method for function ‘couldBeLonLat’ for signature ‘"Extent"’

setMethod("couldBeLonLat", signature(x = "ANY"), 
function (x, ...) 
{
    .local <- function (x, warnings = TRUE, ...) 
    {
        .couldBeLonLat(raster(x), warnings = warnings)
    }
    .local(x, ...)
})

```

Thanks! I'll PR it if you like, it took me a little while to figure out what happened so I'm still slightly unsure.

**Comment by rhijmans** [comment]
Thanks, I added an "ANY" method. There were a number of functions in `raster` that I had to make generics to be able to use the same name in `terra`. For `isLonLat` I added an "ANY" method, but I should have done that for `couldBeLonLat` as well.

**Comment by mdsumner** [comment]
great thanks!
