### ISSUE TITLE
Use common generics from `generics` package

### ISSUE THREAD

**Issue by vspinu** [rspatial/raster#107]
There is now [generics](https://cran.r-project.org/web/packages/generics/index.html) package which defines a bunch of common generics like `union` and `intersect`. 

Currently, if a package imports both `raster` and a package which uses `generics` warnings like [these](https://github.com/tidyverse/lubridate/blob/master/revdep/problems.md#xroi) are generated. 

All one has to do is to import and re-export a generic like in [this example](https://github.com/tidyverse/lubridate/blob/bf9db3cb1cdbe270319936849de7431a054b5414/R/intervals.r#L452-L458)

**Comment by rhijmans** [comment]
I would consider that if many more tidyverse methods were in there; that would be very helpful.
