### ISSUE TITLE
Rasterise leaves holes behind

### ISSUE THREAD

**Issue by pricer-landcare** [rspatial/raster#108]
Hi,

Ive often thought it was just me but here is evidence that I'm not enitrely crazy

The rasterize function leaves out most but not all hole filling polygons. 

library(raster)
library(rgdal)

path.shape <- "P:/Projects/SL1709_SMap_Waikato/Data/GIS/ShapeFiles/Waipa_remodel2018"
lay <- "WaipaX2020_postModelling"
fld <- "mapunit_ed"

i.lay <- rgdal::readOGR(dsn = path.shape, layer = lay, stringsAsFactors = FALSE)
ext.dsmcl <- extent( i.lay)

fld.index = which ( toupper(colnames(i.lay@data)) == toupper(fld))
fld <- colnames(i.lay@data)[fld.index]

r1 <- raster::raster(xmn = ext.dsmcl@xmin, xmx = ext.dsmcl@xmax, ymn = ext.dsmcl@ymin, ymx = ext.dsmcl@ymax, vals = 0, resolution = resample.res)
plot( r1)
i.ras <- raster::rasterize(x = i.lay, y = r1, fld.index)
plot( i.ras)

r2 <- raster::raster(xmn = 1820000, xmx = 1840000, ymn = 5810000, ymx = 5840000, vals = 0, resolution = resample.res)
plot( r2)
i2.ras <- raster::rasterize(x = i.lay, y = r2, fld.index)
plot( i2.ras)
lines( i.lay)

r3 <- raster::raster(xmn = 1834000, xmx = 1836000, ymn = 5815000, ymx = 5819000, vals = 0, resolution = resample.res)
plot( r3)
i3.ras <- raster::rasterize(x = i.lay, y = r3, fld.index)
plot( i3.ras)
plot( i.lay, col="red", add=TRUE)

**Comment by pricer-landcare** [comment]
By leave out I mean an NA appears in the resulting raster

**Comment by pricer-landcare** [comment]
I have written this function as a work around for now:

#'@author Robbie Price
#'@description Creates a raster without holes caused by the Raster::rasterize function
#'@param x SpatialPolygonsDataFrame Vecort Layer to convert
#'@param y Raster raster layer that defines the extent and resolution of output
#'@param field character Name or index of field to rasterise
#'@param filename chacrater Full path of the raster to write
rasterize.safe <- function (x, y, field, filename, ...)
{
  lst.v.curated <- unique(as.data.frame(x[field])[[1]] )
  lst.o.curated <- sort(lst.v.curated)
  lst.r.curated <- match(x = lst.v.curated, table =  lst.o.curated)
  df.vals <- as.data.frame( lst.o.curated )
  colnames( df.vals) <- field
  df.vals$ras.value <- rownames(df.vals)
  ext.dsmcl <- extent(y)
  
  r.u <- raster::raster(xmn = ext.dsmcl@xmin, xmx = ext.dsmcl@xmax, ymn = ext.dsmcl@ymin, ymx = ext.dsmcl@ymax, vals = NA, resolution = resample.res)
  i.max <- nrow( x@data)
  i <- 1
  for ( i in 1:i.max)
  {
    i.fld.value <- x[i,field][[1]]
    i.fld.value.index <- which( lst.o.curated == i.fld.value) 
    
    i.ras <- raster::rasterize(x = x[i,], y = y, i.fld.value.index)
    r.u <- raster::merge( i.ras, r.u)
    #plot( i.rid)
  }
  #plot( r.u)
  tifoptions <- c("COMPRESS=DEFLATE", "PREDICTOR=2", "ZLEVEL=6")
  raster::writeRaster(x = r.u, filename = filename, datatype='INT2U',  options = tifoptions, overwrite=T)
  
  as.data.frame
  
  r <- freq(r.u)
  #r <- ratify(i.ras)
  #rat <- levels(r)[[1]]
  r.vat <- merge( x = r, y=df.vals, by.x="value", by.y="ras.value")      
  r.fn.dbf <- paste0( filename, ".vat.dbf")
  foreign::write.dbf(dataframe =  r.vat, file = r.fn.dbf)
}

**Comment by rhijmans** [comment]
It would be helpful if you could indeed provide some evidence (and example).  Is this the same as what what addressed here: https://github.com/rspatial/raster/issues/108

**Comment by pricer-landcare** [comment]
[WaipaX2020_postModelling.zip](https://github.com/rspatial/raster/files/4432657/WaipaX2020_postModelling.zip)

**Comment by pricer-landcare** [comment]
[WaipaX2020_postModelling.zip](https://github.com/rspatial/raster/files/4432659/WaipaX2020_postModelling.zip)
This version has the tiff from a the rasterise function.

**Comment by rhijmans** [comment]
Your code still cannot run, but with the shapefile you sent, I can do this

```
library(raster)
lay <- shapefile("WaipaX2020_postModelling.shp")
r <- raster::raster(lay, resolution = 500)
ras <- raster::rasterize(lay, r, field=1)
plot(ras)
lines(lay)
```

That looks ok to me.

**Comment by pricer-landcare** [comment]
Could there have been a modification of versions the package version on the machine Im using is packageVersion("raster") ‘2.8.19’

**Comment by rhijmans** [comment]
When reporting bugs, you should always first upgrade to current versions of R and packages. And preferably the development version from github. There have been five formal releases since the version or raster that you are using. But I also fixed a bug yesterday. See 
https://cran.r-project.org/web/packages/raster/index.html
And
https://cran.r-project.org/src/contrib/Archive/raster/
