### ISSUE TITLE
netCDF read with incorrect CRS

### ISSUE THREAD

**Issue by dbaston** [rspatial/raster#110]
Originally reported at https://github.com/isciences/exactextractr/issues/27

Noted when reading a netCDF file from Daymet:

> I used Daymet dataset "daymet_v3_prcp_2017_na.nc4" obtained from https://daac.ornl.gov/cgi-bin/dsviewer.pl?ds_id=1328.

The CRS is a Lambert projection with two standard parallels. `rgdal::GDALinfo` reports:

```
+proj=lcc +lat_0=42.5 +lon_0=-100 +lat_1=25 +lat_2=60 +x_0=0 +y_0=0 +a=6378137 +rf=298.25723 +units=m
+no_defs 
```

But when reading the file in as a RasterStack, we see only one standard parallel.

```
class      : RasterStack 
dimensions : 8075, 7814, 63098050, 365  (nrow, ncol, ncell, nlayers)
resolution : 1000, 1000  (x, y)
extent     : -4560750, 3253250, -3090500, 4984500  (xmin, xmax, ymin, ymax)
crs        : +proj=lcc +lon_0=-100 +lat_0=42.5 +x_0=0 +y_0=0 +lat_1=25 +a=6378137 +rf=298.257232666016 
```

**Comment by rhijmans** [comment]
Thank you for reporting this. I now get 

```
library(raster)
crs(brick("daymet_v3_prcp_2017_na.nc4"))
#CRS arguments:
# +proj=lcc +lon_0=-100 +lat_0=42.5 +x_0=0 +y_0=0 +a=6378137 +rf=298.257232666016 +lat_1=25 +lat_2=60 
```
