### ISSUE TITLE
Read/Add SUBDATASET rasters to a geopackage

### ISSUE THREAD

**Issue by barryrowlingson** [rspatial/raster#114]
geopackage raster support allows for multiple rasters in a single geopackage. The mechanism seems to be to set `APPEND_SUBDATASET=YES` as a GDAL creation option.

I can't get this to work with `writeRaster`, since if the file exists one is forced to use `overwrite=TRUE` and that deletes the geopackage.

Here's `gdal_translate` writing two rasters to a single GPKG:

```
$ gdal_translate -of GPKG -co "APPEND_SUBDATASET=YES" r.tif rrrrr.gpkg
Input file size is 4, 3
0...10...20...30...40...50...60...70...80...90...100 - done.
$ gdal_translate -of GPKG -co "APPEND_SUBDATASET=YES" r2.tif rrrrr.gpkg
Input file size is 4, 3
0...10...20...30...40...50...60...70...80...90...100 - done.
$ gdalinfo rrrrr.gpkg 
Driver: GPKG/GeoPackage
Files: rrrrr.gpkg
Size is 512, 512
Coordinate System is `'
Subdatasets:
  SUBDATASET_1_NAME=GPKG:rrrrr.gpkg:r
  SUBDATASET_1_DESC=r - r
  SUBDATASET_2_NAME=GPKG:rrrrr.gpkg:r2
  SUBDATASET_2_DESC=r2 - r2
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  512.0)
Upper Right (  512.0,    0.0)
Lower Right (  512.0,  512.0)
Center      (  256.0,  256.0)

```

These can be read using the TABLE option:

```
$ gdalinfo -oo TABLE=r2 rrrrr.gpkg 
Driver: GPKG/GeoPackage
Files: rrrrr.gpkg
Size is 4, 3
```

Trying to read them with a `sub` option to `raster` fails:

```
> raster("rrrrr.gpkg",sub=2)
Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file.
In addition: Warning message:
In dim(x) : no bands in dataset
```

I have managed to read these subdatasets with good old `rgdal::readGDAL`!

**Comment by rhijmans** [comment]
This can now (at long last) be done with `terra`:  https://github.com/rspatial/terra/issues/300
I hope that is good enough.
