### ISSUE TITLE
New WorldClim 2.1 on getdata function

### ISSUE THREAD

**Issue by joao-rafael-soares** [rspatial/raster#115]
Dear developers,

Recently I updated the raster package to the latest version and work with worldclim dataset. I tried to use the getData function and I realized that it was downloaded the version 1.4. Is there any way to download this newest version through this function?

Regards,

**Comment by Gabrielforest** [comment]
Hello João,
Do you already found a way to get this data in the newest version (2.1)?
I want to do the same thing with CMIP6...

**Comment by joao-rafael-soares** [comment]
Hello Gabriel,

Not from direct download from the package. Just downloading the bios from worldclim website and reading the files

**Comment by womeimingzi11** [comment]
From what I can tell, the new version has been merged into one tile, not like 1.4 version which is seperated into multiple tiles. Which mean, bioclimatic variables with the high resolution, like 30 sec,  are larger than 9GB. So, `getData` will take a really long while to download such a huge file if replace 1.4 version by 2.1 version.

I guess this may be the reason why `getData` stays in a older version of WorldClim.

So as @joao-rafael-soares said, download files manually and read it into workspace is a way.

**Comment by rhijmans** [comment]
You can use the `geodata` package to download more recent worldclim data

`remotes::install_github("rspatial/geodata")`
