### ISSUE TITLE
Issue with plot.raster() when using layout() with widths argument

### ISSUE THREAD

**Issue by jm-gray** [rspatial/raster#116]
plot.raster has an issue when using a layout() with variable widths. The extent of the first plotted raster is not consistent with subsequent plots, even if they have the same width, and the box() is plotted incorrectly. This happens on my default device (quartz) or pdf output, I haven't tested other devices. Here's a MWE:

```
tmp_r <- raster(matrix(rnorm(100), nrow=10))
# nf <- layout(matrix(1:3, nrow=1), widths=c(1, 1, 1)) # this works
nf <- layout(matrix(1:3, nrow=1), widths=c(1, 1, 0.5)) # this does not
layout.show(nf)
plot(tmp_r, box=F)
plot(tmp_r)
plot(tmp_r)

```
I am using raster 3.0-12 on a Mac w/ macOS 10.15.4 (Catalina)

**Comment by rhijmans** [comment]
You cannot easily `raster::plot` with layout. Although you could try  `plot(x, legend=F` (and add your own legend). Or use `image(x)`.  It is not likely that this will get fixed in the near future.
