### ISSUE TITLE
margins with plot for "RasterBrick" and "RasterLayer"

### ISSUE THREAD

**Issue by mgageo** [rspatial/raster#117]
When I plot an image read with raster or brick, there are top, right and bottom margins.
I use  plot(img, axes = FALSE, legend = FALSE, box = FALSE)
plotRGB and image plot without margins but without the good colors.

[issue_raster_plot.txt](https://github.com/rspatial/raster/files/4559962/issue_raster_plot.txt)

**Comment by rhijmans** [comment]
See the `mai` argument to `par`

**Comment by mgageo** [comment]
With   "par(mar = c(0, 0, 0, 0), oma = c(0, 0, 0, 0), mai = c(0, 0, 0, 0))" I still have top, rigth and bottom margin (no left margin) when I use plot not with image

image
![RasterLayer_image](https://user-images.githubusercontent.com/2681495/85250194-2a6a0600-b456-11ea-9151-8f8322b19068.png)

plot
![RasterLayer_plot](https://user-images.githubusercontent.com/2681495/85250206-335ad780-b456-11ea-8dbe-2a76beb8ed20.png)
