### ISSUE TITLE
Unexpected behavior in the extract() function

### ISSUE THREAD

**Issue by sermomon** [rspatial/raster#119]
I am seeing unexpected behavior in the extract() function. 

In my example I have a raster file that contains a pixel-based classification with 3 categories. On the other hand I have a cadastral file of type ESRI Shapefile. My goal is to extract the pixel values and then create a field in the attribute table with the most frequent pixel value (mode) of each polygon. 

To do this, I first apply the extract function with the "mfv" function of the modeest package to create a data frame with a column for the most frequent value and an automatically created ID column. Then I join this data frame with the ESRI Shapefile attribute table using the ID column. The code is the following:

```
# wd

setwd("D:\\pruebas\\zonal_stat")
getwd()

# library

require(raster)
require(rgdal)
require(modeest)

# inputs

ras <- raster("D:\\pruebas\\zonal_stat\\pix_classif.tif") # raster file for calculate the zonal statistics

zon <- readOGR("D:\\pruebas\\zonal_stat\\parcelas_marco.shp") # ESRI Shapefile which contains the zones
#NOTE: the attribute table should contain an "ID" field with an identifier with values from 1 to n. polygons

# zonal statistics

beginCluster()

ex <- extract(ras, zon, fun=mfv, df=TRUE)

endCluster()

# join results

join <- merge(zon@data, ex, by= "ID")

zon@data <- join

# export ESRI Shapefile

writeOGR(zon, "new_classif.shp", driver= "ESRI Shapefile", layer="zonal_statistics")
```

I observe two problems. First, the ex data frame does not have the same length as the number of polygons in the ESRI Shapefile attribute table:

```
> nrow(ex)
[1] 6912
> nrow(zon@data)
[1] 6878
```

Second, a duplication of record 17 occurs in the ID column of the ex data frame.

```
> ex
     ID pix_classif
1     1           3
2     2           2
3     3           2
4     4           2
5     5           1
6     6           2
7     7           2
8     8           1
9     9           1
10   10           1
11   11           2
12   12           3
13   13           3
14   14           1
15   15           3
16   16           1
17   17           2
18   17           3
19   18           3
20   19           1
21   20           3
```

This code works well for a small set of manually created polygons but not for the cadastral file. What is the problem?

**Comment by rhijmans** [comment]
This site is for reporting bugs, not to ask for help (`stackoverflow` or `R-sig-geo` are more appropriate for that. 

It is difficult to respond as you not provide example data. But this probably happens because mfv (which is really in the statip package) can return multiple numbers.

```
library(statip)
mfv(c(1,2,3,3,4,4,5))
#[1] 3 4
``
You could use `statip::mfv[1]` or `raster::modal` instead
```
modal(c(1,2,3,3,4,4,5))
#[1] 3
```

By the way, you should *not* use the following code 
```
join <- merge(zon@data, ex, by= "ID")
zon@data <- join
```
Merge sorts the table and this can lead to completely wrong associations between geometries and attributes.  You should avoid reading directly from "slots" (`@`) and never write to them, instead use methods that were designed for that.  In this case

```
zon2 <- merge(zon, ex, by= "ID")
```

**Comment by sermomon** [comment]
Thank you very much for your help. I'm new to R and I don't have a good level of coding, as you may have seen. I have been trying to solve this problem for a long time without success and finally I thought that it could be due to an error.

Thank you for your patience.

**Comment by rhijmans** [comment]
You are welcome and I understand. Good luck.
