### ISSUE TITLE
large time difference between calc and row, column selection

### ISSUE THREAD

**Issue by GeraldCNelson** [rspatial/raster#126]
I have a large brick that consists of manipulated climate data 10 years of daily data. It's called gdd and here some stats
```
class      : RasterBrick 
dimensions : 360, 720, 259200, 3653  (nrow, ncol, ncell, nlayers)
resolution : 0.5, 0.5  (x, y)
extent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 
source     : /Users/gcn/Documents/workspace/ISIMIPData/data/cmip6/growingDegreeDays/gfdl-esm4_Barley_ssp585_gdd_global_daily_2051_2060.tif 
```
To reduce the volume of data and speed up number crunching I'd like to break it up into northern and southern hemisphere. One obvious way is with a crop command like 
` gdd_north1 <- crop(gdd, extent(northerHemExtent))`
where `northerHemExtent <- c( -180, 180, 0, 90)`

A second approach is to select specific rows as in  `gdd_north2 <- gdd[1:180, 1:720, drop = FALSE]`

I put a timing loop around each of these. The crop command took 2.9 minutes. The matrix operation took 1.55 minutes so about 1/2 as long. 

My issue is whether there is anything wrong with using the matrix approach?

**Comment by rhijmans** [comment]
Hi Jerry, 
I do not see anything wrong with the matrix approach. My guess is that `crop` takes the result to a temporary file on disk whereas the sub-setting approach does not. If so, you can probably speed up crop by changing the `rasterOptions` (allow for the use of more RAM). But this is also why I would generally prefer crop, as it is more memory-safe.
 
Happy to help but these github pages are for bug reports. For general help please use stackoverflow, R-SIG-GEO, or send me an email.
Robert
