### ISSUE TITLE
projectRaster loses slot @title

### ISSUE THREAD

**Issue by brry** [rspatial/raster#128]
projectRaster sets the @title slot to an empty vector.

```{r}
library(raster)
r <- raster(xmn=-110, xmx=-90, ymn=40, ymx=60, ncols=40, nrows=40)
r <- setValues(r, 1:ncell(r))
r@title <- "Some Text"
r@title
rp <- projectRaster(r, crs="+proj=lcc +lat_1=48 +lat_2=33 +lon_0=-100 +ellps=WGS84")
rp@title # character(0)
```

**Comment by brry** [comment]
I see the same behaviour for subsetting layers (of an nc file).  
Can't get a minimal example right now, this one is as small as I can get it now:

```
url <- "daily/Project_TRY/pressure/PRED_199606_daymean.nc.gz"  #  5 MB
nc <- rdwd::dataDWD(url, base=gridbase, joinbf=TRUE, dir=tempdir())
nc@title # "mean air pressure at sea level"
nc2 <- nc[[1]]
nc2@title # character(0)

nc3 <- raster::subset(nc, 1)
nc3@title # character(0)
```

Not sure if this is directly related or should be it's own issue...

**Comment by rhijmans** [comment]
I am not sure either is an issue (in the sense of a bug). Also, I do not consider this to be valid 

`r@title <- "Some Text"` 

As users should not directly write to a slot (unfortunately, with R/S4 I cannot prevent it). 

I can imagine that you would like to have a way to store "some text" with an object; and that is what that slot was designed for; but that is not implemented; so it is an issue in the sense of a request for a new feature. 

.

**Comment by brry** [comment]
In my view the issue is that this will also happen if the title slot is not set manually, as with the nc file referenced above.
For me personally, that's not a problem, I have a (temporary) [workaround](https://github.com/brry/rdwd/blob/master/R/projectRasterDWD.R#L90-L92), but I thought other people may also run into it...

**Comment by rhijmans** [comment]
Fair enough, but in my view this is just not part of the user interface. You can use it, but it is at your own risk. I will try to implement this (properly) in `terra` though.
