### ISSUE TITLE
raster::predict() resulting in NAs after R update

### ISSUE THREAD

**Issue by clairedavies** [rspatial/raster#136]
Hi,
This is very similar to #73. I have just updated to R 4.0.2 and hence reloaded all my packages. Raster is now version 3.1-5.

I had previous code for predicting output from a gam (mgcv) using a raster brick and some constants as below. This worked fine until I updated R and my package library. After updating all this outputs is a raster with NAs with no error message. 

mgamPred2 <- predict(RS_data_brick2, model = mgam, type="response", const = data.frame(DOY = 45, Survey = 'CPR'))

I read another issue about chr headings in factors so I tried the following, but the same results, only NAs. The brick is purely numeric layers.

newdata <- data.frame(DOY = 45, Survey = 'CPR') %>% mutate(Survey = as.factor(Survey))
mgamPred2 <- predict(RS_data_brick2, model = mgam, type="response", const = newdata)

As there have been several similar instances in these issues is this something you can comment on or do you want to see a reproducible example? I can organise one, or share my repo, if that will help.

thanks,

**Comment by rhijmans** [comment]
It would be very helpful to have an example.

**Comment by clairedavies** [comment]
Here is an example where the resulting prediction is only NAs. Whilst the data is made up all the conditions are within the real data. The model isn't the best fit to this data but this is the structure of the gam with the real data.
Thanks for your help.

library(raster)
library(mgcv)
library(tidyverse)

# create data

Chla <- c(3.333859, 2.328977, 3.013871, 2.961597, 3.272800, 2.106981, 3.512839, 2.880169, 2.053434, 2.221503, 3.942247, 2.087390, 3.875232, 2.977241, 3.978126, 2.436831,  2.629490, 3.668735, 3.965939, 3.187521, 2.663086, 2.459660, 3.208646, 2.642910, 3.406478, 3.163739, 3.626899, 3.849606, 3.845748, 3.663386)
SST <- c(29.91603, 20.63260, 25.57310, 24.77549, 24.36985, 28.39712, 22.98190, 21.09131, 28.68794, 29.62652, 17.46303, 17.96453, 10.11374, 12.45159, 10.64121, 13.30740, 18.47485, 12.12203, 16.87809, 12.75086, 26.81057, 20.35132, 22.72253, 25.89162, 27.60815, 28.04093, 25.05276, 21.24932, 25.31605, 25.17181)
DOY <- c(38.907778,  35.783846,  46.751160,  68.431949,  62.652909,  50.195528,  36.880417,  76.383213,  17.867636,   9.270339, 185.964870, 173.004206, 123.287654, 108.081415, 150.787730, 170.202449, 179.847341, 154.585603,  99.434812,  95.153182, 278.069427, 263.276402, 352.249795, 264.781395, 294.421483, 278.538777,  269.009761, 330.313001, 339.563016, 263.603335)
Depth <- c(154.75422, 225.50723,  88.37746, 233.45412, 244.32774,  73.81559,  58.76476, 216.27638, 196.10828, 172.72498, 298.45073, 168.87762, 171.14954,  51.20933, 123.20508, 182.85752, 121.98296,  79.72206, 153.04733,  97.72958,  73.92650, 267.38902, 292.47359, 254.54929, 229.45967, 162.95837, 117.61892,  99.50547, 98.78427, 161.34468)
SampVolL <- c(1.130405, 1.112984, 1.437747, 1.137086, 1.457495, 1.101167, 1.437479, 1.427287, 1.242754, 1.409320, 1.440140, 1.014111, 1.450878, 1.478112, 1.218598, 1.118681, 1.164005, 1.241720, 1.326287, 1.162326, 1.314819, 1.485414, 1.380043, 1.039346, 1.391103, 1.408828, 1.435910, 1.159506, 1.120938, 1.037523)
Survey <- c(rep('CPR', 10), rep('NRS', 20))
Tripos <- c(1,3,1,1,1,2,1,1,2,1,1,3,1,2,1,4,1,2,2,1,2,1,3,1,3,4,1,5,2,1)

dat <- as.data.frame(cbind(Chla, SST, DOY, Depth, SampVolL, Survey, Tripos )) %>%
  mutate(Chla = as.numeric(Chla),
         SST = as.numeric(SST),
         DOY = as.numeric(DOY),
         Depth = as.numeric(Depth),
         SampVolL = as.numeric(SampVolL),
         Tripos = as.numeric(Tripos),
         Survey = as.factor(Survey))

# model data with gam
mgam <- gam(Tripos ~  Survey + Chla + Depth + te(SST, DOY, bs = c('cr', 'cc')) + offset(log(SampVolL)), Gamma(link = "log"), data = dat)
summary(mgam)

# create rasterbrick
Chla <- raster(nrows = 10, ncols = 10)
V1 <- runif(100, min = 1, max = 4)
values(Chla) <- V1

SST <- raster(nrows = 10, ncols = 10)
V2 <- runif(100, min = 15, max = 30)
values(SST) <- V2

Depth <- raster(nrows = 10, ncols = 10)
V3 <- runif(100, min = 50, max = 300)
values(Depth) <- V3

rbrick <- brick(Chla, SST, Depth) 
names(rbrick) <- c("Chla", "SST", "Depth")

# make predictions
pred <- predict(rbrick, mgam, type = "response", const = data.frame(DOY = 45, Survey = 'CPR'))
summary(pred) # all NAs

**Comment by rhijmans** [comment]
Thank you for your helpful example. I believe this has now been fixed. With the development version, I now get:

```
cdf <- data.frame(DOY = 45, Survey ='CPR', SampVolL=1)  # note SampVolL
p = predict(rbrick, mgam, type = "response", const = cdf )
summary(p) 
#            layer
#Min.    0.6273174
#1st Qu. 1.1097148
#Median  1.6060660
#3rd Qu. 2.4222140
#Max.    7.5125068
#NA's    0.0000000
```

**Comment by clairedavies** [comment]
Brilliant, I’m getting data in the predict output from the example and with my real data. Thanks for the speedy response, really appreciate it.
