### ISSUE TITLE
raster::extract fails on a spatial line with Error in rbind(vv, v) :  number of columns of matrices must match (see arg 2)

### ISSUE THREAD

**Issue by fabrice-rossi** [rspatial/raster#137]
Hi,

On a code on the form
```
library(raster)
library(rgdal)
srtm <- readGDAL("myterrain.tif")
ras_srtm <- raster(srtm)
sldf <- readOGR (dsn = "./", layer = "myriver")
cells <- extract(ras_srtm,sldf,cellnumbers=TRUE,along=TRUE)
```
the last line fails with the error message:
```
Error in rbind(vv, v) : 
  number of columns of matrices must match (see arg 2)
```

I've tracked the problem in R/extractLines.R, line 255. If I understand correctly, it is a consequence of having multiple disconnected traces for a given SpatialLine on a raster. The loop on line 223 over the parts closes on line 269. However at the end of the internal loop on k (from line 225 to line 257), the accumulator data.frame vv is converted to another format (from row,col,value to cell,band1) and thus becomes incompatible with the data.frame v once the loop over the parts move to another part.

I think this can be fixed by moving the conversion outside of the part loop, but I do not understand the internals of raster to fix it myself. 

I'm not sure I can provide the example files publicly, so I hope the report is clear enough.

**Comment by rhijmans** [comment]
Thank you for reporting this. It would be very helpful if you could create an example that reproduced this. For example, can you take a small part of the data you are using and change it enough to allow sharing? Or create something similar with `spLines`?

**Comment by fabrice-rossi** [comment]
I've to check with the owner of the files. Meanwhile, I've tested the "solution" proposed above and it seems to work: `pbStep(pb)` on line 268 should stay in the `for (j in 1:nparts) {` loop but lines from 258 to 267 should be moved to the enclosing loop over i (`for (i in 1:nlns) {`).

**Comment by rhijmans** [comment]
Thank you for your help. I changed the code as you suggested.
