### ISSUE TITLE
trim function returns empty raster (NAs) since R 4.0.1 or 4.0.0

### ISSUE THREAD

**Issue by Antoine-CSQN** [rspatial/raster#138]
The trim function returns an empty raster (good size, but full of NAs instad of the expected values) since I updated R and the raster package.
It does what is expected on my old R install (3.6.0)
It also throws a warning for projection issues, that is related to the new way of rgdal is (not) handling PROJ string I guess ... 

```
library(raster)
wat.rst <- raster('wat_P01.tif)
wat.trimmed <- trim(wat.rst)
```

I joined the raster I was working on if it could help.

[wat_P01.zip](https://github.com/rspatial/raster/files/4847082/wat_P01.zip)

**Comment by rhijmans** [comment]
Thank you very much!
