### ISSUE TITLE
projectRaster gives very different results to resample which is not documented

### ISSUE THREAD

**Issue by Blundys** [rspatial/raster#140]
Hi, 

I have realised that `projectRaster` and `resample` can give very different results when both using the bilinear interpolation. 

The documentation implies that these can be used in place of each of depending on the if your crs match or not "Use projectRaster if the target has a different coordinate reference system (projection)." 

`projectRaster` appears to ignore all cells except the closest 4 to the new centroid which for highly variable data or large changes to grid sizes can make very large differences to the final output. 

I've made a reprex to highlight this with obviously extreme data. It would be nice if `projectRaster` could be made to behave as `resample` does but at very least it should be clearly documented that many cells may be ignored. 

``` r
library(raster)

testproj <- "+proj=lcc +lat_1=48 +lat_2=33 +lon_0=-100 +ellps=WGS84"

testmat <- matrix(1, nrow = 8, ncol = 8)

testmat[1,5] <- 400
testmat[8,4] <- -400

testsmallraster <- raster(testmat, xmn=0, xmx=8, ymn=0, ymx=8)
crs(testsmallraster) <- testproj

testlarger <- raster(matrix(rep(NA,4), nrow = 2, ncol = 2), xmn=0.3, xmx=8.3, ymn=0, ymx=8)

crs(testlarger) <- testproj

tout_reproj <- projectRaster(testsmallraster, testlarger)
tout_resamp <- resample(testsmallraster, testlarger)

#reprojected values ignore all but 4 cells closest to new centre (I think)
values(tout_reproj)
#> [1] 1 1 1 1
#resample uses all cells
values(tout_resamp)
#> [1]  10.851852  15.777778  -7.911111 -12.366667
```

<sup>Created on 2020-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rhijmans** [comment]
There (now?) is a note in the docs that says  

> If the resolution of the output is much larger than that of the input, you should first aggregate the input such that the resolution of the input becomes more similar (perhaps a little smaller) to the output.
