### ISSUE TITLE
brick error name raster

### ISSUE THREAD

**Issue by MAUjam** [rspatial/raster#141]
in previous versions of raster, in the brick () function the name of the raster appeared correctly, in the last version it appears only as layer
names      :    layer

**Comment by rhijmans** [comment]
Can you please provide more context? How are you using `brick`? With a filename? If so what format?

**Comment by MAUjam** [comment]
I have tried using directory path with .tif and .img files
brick("c:/directory/rastertest.tif") or "../rastertest.img"

the latest version provides the name of the raster as "layer", while version 2.9 shows the name of the raster as "rastertest"
I have uninstalled and installed the package and tested on other computers, but only version 2.9-23 provides the name correctly

version 2.9
> brick("C:/test/rastertest.tif")
class      : RasterBrick 
dimensions : 17223, 25861, 445404003, 1  (nrow, ncol, ncell, nlayers)
resolution : 0.0002222222, 0.0002222222  (x, y)
extent     : -92.4778, -86.73091, 17.8061, 21.63344  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
source     : C:/test/rastertest.tif 
names      : rastertest 


version 3.3-7

> brick("C:/test/rastertest.tif")
class      : RasterBrick 
dimensions : 17223, 25861, 445404003, 1  (nrow, ncol, ncell, nlayers)
resolution : 0.0002222222, 0.0002222222  (x, y)
extent     : -92.4778, -86.73091, 17.8061, 21.63344  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
source     : C:/test/rastertest.tif 
names      : layer

**Comment by rhijmans** [comment]
raster now reads the names from the geotiff if they are available. So I am guessing that your file specifies "layer" as the band name.
