### ISSUE TITLE
printed warnings when reading nc files

### ISSUE THREAD

**Issue by brry** [rspatial/raster#143]
When reading nc files with `raster::brick`, a DIMVAR warning gets printed to the console.  
While printing instead of using `warning()` may be bad practice by `ncdf4`, it might be worth trying to find out why it happens in the first place.
As far as I can tell, despite the warning "Code will probably fail at this point", it seems to work fine.

If you prefer to focus on terra instead of raster, feel free to close this issue.
I can work around it with `capture.output()`. I just did not want to let it get unreported.

Here's a reproducible example (raster 3.3-7, ncdf4 1.17):

```r
url <- paste0("ftp://opendata.dwd.de/climate_environment/CDC/grids_germany/",
              "daily/Project_TRY/pressure/PRED_199606_daymean.nc.gz")
gzfile <- tempfile(fileext=".nc.gz")
download.file(url, gzfile) # 5.4 MB
ncfile <- R.utils::gunzip(gzfile, remove=FALSE, skip=TRUE)

ncdata <- raster::brick(ncfile)
raster::plot(ncdata, maxnl=1) # works fine
```

the `raster::brick` call prints two charstrings to the console:  
`vobjtovarid4: **** WARNING **** I was asked to get a varid for dimension named [x/y] BUT this dimension HAS NO DIMVAR! Code will probably fail at this point`

The traceback (linked directly to relevant LOC):  
[raster::brick](https://github.com/cran/raster/blob/master/R/brick.R#L26) -> [raster:::.rasterObjectFromFile](https://github.com/cran/raster/blob/master/R/rasterFromFile.R#L50) -> [raster:::.rasterObjectFromCDF](https://github.com/cran/raster/blob/master/R/netCDFtoRasterCD.R#L188) -> [ncdf4::ncvar_get](https://github.com/cran/ncdf4/blob/master/R/ncdf4.R#L2174) -> [ncdf4:::vobjtovarid4](https://github.com/cran/ncdf4/blob/master/R/ncdf4_priv_var.R#L292-L293)

The print got introduced in ncdf4 version 1.17 (2019-10-23), see [git diff](https://github.com/cran/ncdf4/commit/3bf59997b5142488a0b3ab03b2d8dc0f4ac43ab6#diff-02f914e87bf0b86dae5047e404bc4fd2R293).

**Comment by rhijmans** [comment]
Hi Berry, Thanks for reporting this. Yet, the file "works", but the data are not properly geo-referenced because the file does not supply the x and y coordinates.  So that are not really usable in the way you would normally expect. So in this case, perhaps a warning may be a good thing? 

This obviously is Germany and we know where that is, so you could fix that, but that might take some work. If you know the extent you can set it like this:

      extent(ncdata) <- c(5, 16, 46.8, 55.5)

That gets it close, but not exactly, suggesting that the coordinate reference system is not lon/lat

> If you prefer to focus on terra instead of raster, feel free to close this issue.

I am sorry if I gave that impression. I am a bit wary of making changes in raster, because there are so many dependencies; and because of the time demand from terra; but I will make them if there is a good reason.

**Comment by brry** [comment]
I may have mis-understood the warning. The names "x" and "y" are available in the nc object (`nc$var[[zvar]]$dim[[dims[1]]]$name`). 
I thought the warning means the so-named dimensions cannot be found when queried, but you might be correct that they are named, yet missing.

I'm not a crs expert, but it seems `ncvar_get` somehow does find the coordinates. The projection seems to work with
```r
rdwd::plotRadar(ncdata, layer=1, proj="nc", extent="nc")
```
![nc_map](https://user-images.githubusercontent.com/8860095/86626985-cdc72900-bfc7-11ea-93a8-aea08e2d795f.png)

It sets `projection(r) <- "+init=epsg:3034"  ;   extent(r)<- c(3667000, 4389000, 2242000, 3181000)` and reprojects to latlon with `projectRaster(r, crs=sp::CRS("+proj=longlat +datum=WGS84 +no_defs"))`

EPSG 3034 is specified by the data source (DWD, German weather service) and the extent was found manually by me.
Not sure if this approach is actually correct, but it does look fine...

**Comment by rhijmans** [comment]
Yes, if you know the crs and with a reasonable accurate estimate of the extent you should be fine.  And if you can suppress the warning then I think all is good.
