### ISSUE TITLE
Possible problem with raster 3.3-7

### ISSUE THREAD

**Issue by walts** [rspatial/raster#145]
I had been successfully using the following R code until I updated to release 3.3-7 a few days ago

   library(raster)
   library(tmap)
   download.file(url = "https://drive.google.com/uc?export=download&id=1-C48DzgpuXwKwCzeeI57vrkel66YEntF",
              destfile = "houston_wards.jpg", mode="wb")
#
#  create a raster layer object from jpg
#
   ward_map <- raster::raster(x = "houston_wards.jpg",
                           crs= "+proj=longlat +datum=WGS84")  
#
#  set corner coordinates of raster map
#
   xmin(ward_map) <- -95.42946
   xmax(ward_map) <- -95.27887
   ymin(ward_map) <-  29.706078
   ymax(ward_map) <-  29.812857
#
#  make map using tmap
#
   ward_map <- tm_shape(ward_map) + tm_raster(alpha = .5, palette = "Greys", legend.show = FALSE)
   print(ward_map)

which now gives the error

"Error: Current projection of shape ward_map unknown and cannot be determined"

Any thoughts?

**Comment by Nowosad** [comment]
It could be related to the used version of the tmap package. What is the version you are using? If 3.0, then try the development version. You can install it with:

```r
library(remotes)
install_github("mtennekes/tmaptools")
install_github("mtennekes/tmap")
```

**Comment by walts** [comment]
I was using tmap 3.0.  I've installed the development 3.1 version.  The error message now reads

stars_proxy object shown at 1109 by 901 cells.
Error: Current projection of shape ward_map unknown and cannot be determined.

**Comment by Nowosad** [comment]
It seems like a tmap issue - please report it at https://github.com/mtennekes/tmap/issues.

**Comment by walts** [comment]
OK.  Thanks very much.
