### ISSUE TITLE
Raster 3.3-7 don't run with R 4.0.0 on Windows 10

### ISSUE THREAD

**Issue by STwintertal** [rspatial/raster#146]
When I try to load raster 3.3-7 after Installation, I get the error message Rterm.exe entry Point not found because the raster.dll can't be found.
I checked the folder and the raster.dll ist there.

Either I switch back to raster 3.3-6 under R 4.0.0 or I use R 3.6.1 with raster 3.3-7 everything works fine.

Any thoughts?

**Comment by rhijmans** [comment]
It should work fine with R 4; I would suggest installing R 4.0.2; and do fresh installs of the packages.

**Comment by TheTS** [comment]
I had this issue. Updating R from R 4.0.0 to 4.0.2 fixed it.
