### ISSUE TITLE
trim() error after raster 3.0-12

### ISSUE THREAD

**Issue by Cdevenish** [rspatial/raster#149]
trim() function does not work correctly in raster versions 3.3-6 and 3.3-7. The example from the function help file gives this result:

![s_raster3 0-7_on_r4 0](https://user-images.githubusercontent.com/7408581/87311129-c0a1c100-c516-11ea-9b0e-85fb3406f3cc.png)

```
# class      : RasterLayer 
# dimensions : 10, 3, 30  (nrow, ncol, ncell)
# resolution : 20, 10  (x, y)
# extent     : 80, 140, -30, 70  (xmin, xmax, ymin, ymax)
# crs        : +proj=longlat +datum=WGS84 +no_defs 
# source     : memory
# names      : layer 
# values     : 2, 2  (min, max)
```

It seems that line 67 has been dropped from  `.memtrimlayer()` in trim.R (version 3.0-12): `cols <- which(cols != nrow(x))`

Reinserting this line, and the raster is trimmed correctly.

Tested on r 4.0.2.

**Comment by rhijmans** [comment]
Thanks, this has already been fixed in the development version ---- and should get to CRAN soon.
