### ISSUE TITLE
Add braces to if-else

### ISSUE THREAD

**Issue by thk686** [rspatial/raster#150]
https://github.com/rspatial/raster/blob/41ea0f15b49fcc4ea4e0a3df73768cea4c1d2d74/R/readCells.R#L37

I think the lack of braces around the else block is causing an error with on-disk objects as the flow control skips to the error block. (At least that is my best guess as I get an error when I try to use extract with an on-disk raster -- the same code works fine with an in-memory raster. I seem to recall that R can behave unexpectedly around if-else without braces.) Perhaps add the missing braces around the else block and see if that works?

**Comment by rhijmans** [comment]
Can you provide a reproducible example for that error? My guess would be that the file is corrupted. 

I agree about the braces around `else` but this is an `else if` block

```
if() { } else if() { } else { }
```
I think that should be fine. But of course it could be changed to

```
if() { } else {  
    if () { } else { }
}    
```
That is not as expressive --- but I would do it if it helps.

**Comment by thk686** [comment]
I think the braces are ok. (I was recalling the else-on-new-line issue but that's not a problem here.)

It turns out I was inadvertently calling `x <- raster::raster(x)` and that apparently corrupts the data if `x` is an on-disk raster.

**Comment by rhijmans** [comment]
`x <- raster::raster(x)`, with input `x` being a Raster* creates an empty RasterLayer with no data attached. It is used a lot to copy the raster parameters into a new object.

**Comment by thk686** [comment]
Got it. Thanks.

**Comment by rhijmans** [comment]
By the way, nice to hear from you having used your (rgdal) work for so long.  You might be interested in exploring [terra](https://gihub.com/rspatial/terra) --- which, I hope, will replace `raster`

**Comment by thk686** [comment]
Yes, we should work together on something. I did notice terra. Its great
that things are developing so nicely in the r geo space.

THK
