### ISSUE TITLE
3.3-11 backward incompatibility when cropping with non overlapping shapes

### ISSUE THREAD

**Issue by Jean-Romain** [rspatial/raster#151]
This is related to https://github.com/Jean-Romain/lidR/issues/360. Reproduced without `lidR`. When cropping a `SpatialPolygons*` with and `Extent` (maybe other objects as well) that do not overlaps the polygons, the former behavior was `NULL`. Not it throws an error.

```r
library(sp)
library(raster)

# Make a polygon
set.seed(2)
P = matrix(runif(8), 4, 2)
P[4,] = P[1,]
P = Polygon(P)
P = Polygons(list(P), "1")
P = SpatialPolygons(list(P))

# Make a bbox
E = extent(2,4,2,4)

# Display
plot(P, axes = T, xlim = c(0, 5), ylim = c(0,5))
plot(E, add = T, col = "red")

# NULL expected
raster::crop(P, E) # <= 3.3-7: NULL, 3.3-11: error
#> Error in (function (cl, name, valueClass) : 'proj4string' is not a slot in class "NULL"
```

![](https://i.imgur.com/obwjyp5.png)

**Comment by rhijmans** [comment]
Thank you very much for your quick help. Sorry to have bothered you with this problem.

**Comment by Jean-Romain** [comment]
No problem :wink: . Unit tests are ok with 3.3-12
