### ISSUE TITLE
rasterize "fun" argument format varies depending on the function

### ISSUE THREAD

**Issue by Cgarland12** [rspatial/raster#152]
I'm using rasterize in a shiny app and when trying to pass the "fun" argument to rasterize in my server from "selectInput" in my UI, both `"mean"` and `"median"` break my code while` "count"`,` "min"`, and, `"max"` work. Through some troubleshooting, I've found that `mean `and `median` without quotes works in rasterize but `"mean" `and` "median"` with quote breaks the function. Alternatively, `"count"`, `"min"`, and `"max"` require quotes and break rasterize if quotes aren't present. Thoughts?

**Comment by rhijmans** [comment]
Interesting. What are the error messages you are getting? 

In a normal R session, the below works for me.

```
library(raster)
p1 <- rbind(c(-180,-20), c(-140,55), c(10, 0), c(-140,-60), c(-180,-20))
hole <- rbind(c(-150,-20), c(-100,-10), c(-110,20), c(-150,-20))
p1 <- list(p1, hole)
p2 <- rbind(c(-10,0), c(140,60), c(160,0), c(140,-55), c(-10,0))
p3 <- rbind(c(-125,0), c(0,60), c(40,5), c(15,-45), c(-125,0))
pols <- spPolygons(p1, p2, p3)

r <- raster(ncol=90, nrow=45)
r <- rasterize(pols, r, fun=sum)
r <- rasterize(pols, r, fun="sum")
r <- rasterize(pols, r, fun=mean)
r <- rasterize(pols, r, fun="sum")
r <- rasterize(pols, r, fun=min)
r <- rasterize(pols, r, fun="min")
r <- rasterize(pols, r, fun=max)
r <- rasterize(pols, r, fun="max")
r <- rasterize(pols, r, fun=median)
r <- rasterize(pols, r, fun="median")

```
