### ISSUE TITLE
mask() writing 0s instead of NAs

### ISSUE THREAD

**Issue by lucas-johnson** [rspatial/raster#153]
## Current Behavior

`mask()` function converts masked out ares to `0`s instead of `NA`s.

Example code:

```
> install.packages("raster")
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/raster_3.3-13.tgz'
Content type 'application/x-gzip' length 4229389 bytes (4.0 MB)
==================================================
downloaded 4.0 MB


The downloaded binary packages are in
	/var/folders/_c/bcw1j0251k12c8hqxpqpb7nr0000gn/T//Rtmp3gO8N1/downloaded_packages
> library(raster)
Loading required package: sp
Warning message:
package ‘raster’ was built under R version 4.0.2 
> cropped_conus <- raster("~/Downloads/cropped_nlcd_change_07232020.tif")
> unique(getValues(cropped_conus))
 [1] NA  7  1  6  4  2  5  3 13 17 65 64 46 26 45 42 54 52 43 57 62 67 47 16 21 61 71 56 24 14 12 25 51 27 53 41 75 74 76 15 72 23
[43] 36 73 63 37 32 35 34 31
> mask <- raster("~/Downloads/rasterized_ny_shoreline.tif")
> unique(getValues(mask))
[1] NA  1
> masked_nlcd_change <- mask(cropped_conus, mask)
> plot(masked_nlcd_change)
> unique(getValues(masked_nlcd_change))
 [1]  0  7  4  5  1  6  2 26 47 45 46 42 17 62 67 64 61 24 27 65 25 71 12 75 41 74 76 15 72 16 14 43 23  3 36 21 73 63 13 51 57 35
[43] 56 54 32 34 31 53 52 37
```
Resulting plot:
![image](https://user-images.githubusercontent.com/10555272/88355059-12292780-cd31-11ea-8d99-0c6e40e54e5d.png)

## Desired Behavior
`mask()` function convert masked out areas to `NA` values as is specified by the default value for `updatevalue`

**Comment by lucas-johnson** [comment]
## Update
When specifying the format as `GTiff` the NA values are correctly written. Previously the driver for the resulting masked raster was `raster`, but after specifying `format = "GTiff"` the driver is `gdal`. Perhaps the drivers are causing `0`s to be written instead of `NA`s.

Example: 
```
masked_nlcd_change <- mask(cropped_conus, mask, format = "GTiff")
> unique(getValues(masked_nlcd_change))
 [1] NA  7  4  5  1  6  2 26 47 45 46 42 17 62 67 64 61 24 27 65 25 71 12 75 41 74 76 15 72 16 14 43 23  3 36 21 73 63 13 51 57 35
[43] 56 54 32 34 31 53 52 37
```

**Comment by rhijmans** [comment]
Thanks for reporting this. I cannot reproduce it making it hard to fix.  Can you share these files?

**Comment by lucas-johnson** [comment]
@rhijmans Sending you the files via WeTransfer...

**Comment by rhijmans** [comment]
Thanks. I can confirm that NAs are lost in a "grd" file (and become zero) when you have an object with a colortable (that is why plot() gives you these nice colors ) because the values are bytes (0-255) and raster does not assign an NA in that range. I need to look into this a bit more (and see if I can fix this), but I think that is basically what is going on. Another work-around would be to first multiply the landcover raster with 1 (that gets rid of the colortable); but with the current constraints the best solution is (as you suggested) to save to a GTiff, perhaps like this

```
library(raster)
r <- raster("cropped_nlcd_change_07232020.tif")
m <- raster("rasterized_ny_shoreline.tif")
rm <- mask(r, m, filename="lcmasked.tif")
```

**Comment by lucas-johnson** [comment]
Thank you for looking into this.

**Comment by rhijmans** [comment]
I think this all works as expected with the `terra` package. So I am not going to worry about it anymore for `raster`.
