### ISSUE TITLE
install problem R 4

### ISSUE THREAD

**Issue by fipoucat** [rspatial/raster#155]
I am now using R version 4 and since then have trouble loading raster package on my mac:
> library(raster)
Error: package or namespace load failed for ‘raster’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/raster/libs/raster.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/raster/libs/raster.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/raster/libs/raster.so
  Expected in: /Library/Frameworks/R.framework/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/raster/libs/raster.so
In addition: Warning message:
package ‘raster’ was built under R version 4.0.2 

Really stuck and hope a hint to fix this.

Best

**Comment by rhijmans** [comment]
Something has gone wrong during installation. Perhaps you copied packages from a previous R version?  The problem could go away if you install Rcpp and raster from scratch. But it is probably best to start with a fresh install of R 4.0.2 and then of `raster`.
