### ISSUE TITLE
focal function gives cells bordering mask lower score

### ISSUE THREAD

**Issue by nancyjpeterson** [rspatial/raster#156]
I used the raster::focal function to resample a raster (WorldClim2 Mean Annual Temperature for the western Mexico) over different spatial scales.
 
I used the option fun = sum function because I need the resampled raster to have comparable values to the initial raster. (If I resample using the average function and the weight of each cell is 0.1111, as is the case for a 9-cell grid, then the average, resampled cell value drops down an order of magnitude from the initial value. So the sum function is conceptually the average resampled cell value, because the focal weight is taken into account). The problem with using fun = sum, is cells bordering masked values (which are coastal values near the water on this peninsula) have a lower overall sum, because these NA's/masked values/water areas are treated as zeros in the calculation. This happens even when I set na.rm=TRUE. Also, the masked values get treated as "0's" so the function resamples the mask as well. So I have to remask the resampled raster for true land area again.

To solve the coastal cells problem friend and I changed the sum function to read:
fun = function(x, na.rm=TRUE){mean(x, na.rm=TRUE) / cellWeight
in which cellWeight is the decimal value that each cell is multiplied by from the weight matrix (e.g. cellWeight = 0.111111 for a 9-cell matrix). 

This way all resampled rasters have similar units to the original raster, coastal cells aren't penalized, and masked water values don't become part of my calculations. 
[Resample_function.pdf](https://github.com/rspatial/raster/files/5093594/Resample_function.pdf)

**Comment by rhijmans** [comment]
I do not see a request here. It seems that what you do can with 

`r <- focal(r, w=matrix(1,nrow=3,ncol=3), fun=mean, na.rm=T, pad=T)`
