### ISSUE TITLE
writeRaster does not preserve crs with GeoTiffs

### ISSUE THREAD

**Issue by laurimyllyvirta** [rspatial/raster#157]
When writing a raster as .tif with writeRaster and reading back in with raster(), UTM projection is changed to tmerc. I know the two projections are equivalent, but this causes all further functions to fail that require rasters to have the same CRS. When writing into .grd format, behavior is normal. The issue appeared with an update some months ago.

```
library(raster)
r <- raster(crs="+proj=utm +datum=WGS84 +no_defs +zone=1 +units=km")
r1 <- writeRaster(r, 'test.grd')
crs(r1)
# CRS arguments: +proj=utm +zone=1 +datum=WGS84 +units=km +no_defs 
```

```
r2 <- writeRaster(r, 'test.tif')
crs(r2)
# CRS arguments: +proj=tmerc +lat_0=0 +lon_0=-177 +k=0.9996 +x_0=500000 +y_0=0 +datum=WGS84 +units=km +no_defs 
```

```
compareRaster(r1, r2)`
#Error in compareRaster(r2, r3) : different CRS
```

**Comment by rhijmans** [comment]
This surely is related to the changes in the PROJ library. I see that this does not happen if you use the standard `units=m`. I am guessing that by using `units=km` this is not considered UTM anymore, somewhere under the hood.

```
library(raster)
r1 <- raster(crs="+proj=utm +datum=WGS84 +no_defs +zone=1 +units=m", vals=1)
r1 <- writeRaster(r1, 'test1.tif', overwrite=TRUE)
crs(r1)
#CRS arguments:
# +proj=utm +zone=1 +datum=WGS84 +units=m +no_defs 
 
r2 <- raster(crs="+proj=utm +datum=WGS84 +no_defs +zone=1 +units=km", vals=1)
r2 <- writeRaster(r2, 'test2.tif', overwrite=TRUE)
crs(r2)
#CRS arguments:
# +proj=tmerc +lat_0=0 +lon_0=-177 +k=0.9996 +x_0=500000 +y_0=0 +datum=WGS84 +units=km +no_defs 

```

**Comment by laurimyllyvirta** [comment]
Thanks for noting the effect of the units. I'm stuck with km as the units due to my workflow. I guess this is too niche to expect a fix to be implemented in the raster package? I'll write a wrapper around raster for my own usage that converts tmerc to UTM.

**Comment by rhijmans** [comment]
This is not something I have control over as it is handled by the GDAL/PROJ libraries.
