### ISSUE TITLE
projectRaster axis mismatch

### ISSUE THREAD

**Issue by mdsumner** [rspatial/raster#158]
`projectRaster(, crs = "character")` performs its own logic for determining the output resolution from a local delta, and when rotation is involved this can result in very large output dimensions. The usual fix is "set the target raster", but it's a clear mistake in  `.computeRes()` where it differs from `projectExtent()`. I wonder if `.computeRes()` should use the overall extent rather than a local (cell-scale) region? 

This is what should happen in this instance: 

```R
v <- c(859L, 906L, 971L, 1017L, 1084L, 1158L, 1215L, 1223L, 1299L, 
       767L, 812L, 870L, 950L, 1029L, 1103L, 1152L, 1185L, 1250L, 627L, 
       679L, 758L, 868L, 995L, 1071L, 1131L, 1148L, 1167L, 453L, 540L, 
       623L, 808L, 905L, 1001L, 1041L, 1093L, 1110L, 341L, 438L, 509L, 
       716L, 847L, 905L, 1025L, 1078L, 1071L, 236L, 349L, 432L, 617L, 
       790L, 856L, 907L, 1004L, 1041L, 100L, 222L, 389L, 635L, 728L, 
       842L, 902L, 964L, 1002L, 82L, 111L, 387L, 591L, 723L, 797L, 853L, 
       927L, 938L, 88L, 68L, 353L, 525L, 640L, 751L, 808L, 877L, 857L, 
       73L, 57L, 296L, 472L, 612L, 655L, 770L, 804L, 767L, 59L, 73L, 
       170L, 330L, 480L, 596L, 708L, 730L, 685L, 49L, 57L, 71L, 238L, 
       352L, 436L, 601L, 633L, 585L, 38L, 29L, 61L, 73L, 181L, 368L, 
       477L, 492L, 409L, 34L, 21L, 51L, 87L, 106L, 308L, 333L, 291L, 
       262L)

r <- setValues(raster(extent(2400000, 2500000, 2e+05, 3e+05), 
                      crs = " +proj=stere +lat_0=-90 +WGS84", nrows = 9, ncols = 14), v)


projectRaster(r, crs = "+proj=longlat")
# class      : RasterLayer 
# dimensions : 23, 12, 276  (nrow, ncol, ncell)
# resolution : 0.257, 0.0614  (x, y)
# extent     : 82.61798, 85.70198, -68.89677, -67.48457  (xmin, xmax, ymin, ymax)
# crs        : +proj=longlat +datum=WGS84 +no_defs 
# source     : memory
# names      : layer 
# values     : -173.7249, 1368.711  (min, max)
```

but, in current raster we get

```R
projectRaster(r, crs = "+proj=longlat")
class      : RasterLayer 
dimensions : 115, 161, 18515  (nrow, ncol, ncell)
resolution : 0.0169, 0.00975  (x, y)
extent     : 82.79048, 85.51138, -68.76367, -67.64242  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
source     : memory
names      : layer 
values     : -289.2338, 1467.877  (min, max)
```

In the former example I [changed these lines](https://github.com/rspatial/raster/blob/master/R/projectRaster.R#L134-L135) to 

```R
pXY <- cbind(pXY[[1]], pXY[[2]])
outex <- extent(pXY)
out <- c(xmax(outex) - xmin(outex),
         ymax(outex) - ymin(outex))
```

because it otherwise assumes x and y are aligned (not rotated 90 degrees to y,x) and this blows out causing a memory failure with realistic data. (trying to allocate 5Gb or more from a 400x500 raster)

The logic behind .computeRes is quite different to projectExtent, so I'm not sure what the best approach is to balance resolution of the output (but in practice this has happened a lot leading me to almost always use `projectRaster(raster, target)`.

**Comment by rhijmans** [comment]
Thanks, I have implemented the proposed change.

**Comment by mdsumner** [comment]
Definitely, thanks
