### ISSUE TITLE
Coverting a factor-valued pixel image to a raster

### ISSUE THREAD

**Issue by idblr** [rspatial/raster#159]
When I attempt to convert a factor-valued pixel image to class `RasterLayer` using the `raster()` function I receive the following error:
```
Error in setValues(r, from$v) : 
  values must be numeric, integer, logical or factor
```
Minimal working example:
```
# The following integer-valued pixel image converts to a raster successfully
elevation <- spatstat.data::gorillas.extra[[2]]
raster(elevation)

# The follow throws an error:
aspect <- spatstat.data::gorillas.extra[[1]]
raster(aspect)
```
Looking within the source code for `setValues()`, it appears Line 37 is missing a conditional for factor values. See suggestion below:
```
if (!(is.numeric(values) | is.integer(values) | is.logical(values) | is.factor(values))) {
       stop('values must be numeric, integer, logical or factor')	}
```

**Comment by rhijmans** [comment]
Thanks for reporting this. I now get:

```
library(raster)
aspect <- spatstat.data::gorillas.extra[[1]]
raster(aspect)
#class      : RasterLayer 
#dimensions : 149, 181, 26969  (nrow, ncol, ncell)
#resolution : 30.70955, 30.70955  (x, y)
#extent     : 580440.4, 585998.8, 674156.5, 678732.2  (xmin, xmax, ymin, ymax)
#crs        : NA 
#source     : memory
#names      : layer 
#values     : 1, 8  (min, max)
#attributes :
#       ID VALUE
# from:  1     N
#  to :  8    NW

```

**Comment by idblr** [comment]
Thanks, @rhijmans!

**Comment by idblr** [comment]
Hi @rhijmans, I still receive the error after installing the latest development version 3.3-16

Happy to help troubleshoot

**Comment by rhijmans** [comment]
It works for me, so this suggests that you may need to get rid of an old workspace to really load the new version.
Sometimes `unlink(".Rdata")` and restarting R does the trick.

**Comment by idblr** [comment]
Ah, yep! Thanks, @rhijmans. That did the trick! Pinning this tip for later use.
