### ISSUE TITLE
[suggestion] switch to roxygen for documentation ? 

### ISSUE THREAD

**Issue by lbusett** [rspatial/raster#16]
Hi. I was wondering if you would consider switching to using roxygen for the documentation of the package. 

That is clearly a matter of preference, but in my opinion it helps both in keeping the docs up to date with the code, and in reviewing the code (since arguments "definitions" can be readily found in the roxygen comments).

In case you are interested in this, let me know: I'd be glad to help in the transition
(maybe trying using: https://yihui.name/rd2roxygen/)

**Comment by rhijmans** [comment]
Hi Lorenzo, Thanks, I see the benefit, but I prefer to keep raster as-is for now. Robert

**Comment by mdsumner** [comment]
Ah that's good to know. Would you mind adding a contributing.md, and a section in readme to make this clear. PRs are welcome, testthat tests, no roxygen, etc. 

I'm happy to do that if no one else does, and feel free to ping me to get on with it if I forget.  A pretty comprehensive outline of contribution guidelines is here: https://www.tidyverse.org/articles/2017/08/contributing/
