### ISSUE TITLE
projectRaster alignOnly issue

### ISSUE THREAD

**Issue by ailich** [rspatial/raster#162]
When trying to use projectRaster to align 2 rasters to the same origin and resolution, I get the message "Warning message:
In projectRaster(x, crs = .getCRS(y)) : 'from' has no cell values." Seems to be the same as issue #27 . I coded up a workaround [here ](https://gis.stackexchange.com/questions/333464/re-projecting-a-raster-in-r-to-matching-resolution-crs-and-origin-but-differe/335605?noredirect=1#comment610811_335605)a while ago that seems to work for my purposes.

R 3.6.3, raster version 3.3-13

Example:
```

#Create a raster with GRS80 crs and 1.5m resolution
r1<- raster(xmn=731458, xmx = 731458+100*1.5,  ymn=3116234, ymx= 3116234+100*1.5, 
nrow=100, ncol=100, vals=sample(1:50, size = 100*100, replace = TRUE), res=1.5, 
crs= "+proj=utm +zone=16 +ellps=GRS80 +towgs84=0,0,0,-0,-0,-0,0 +units=m +no_defs ") 

#Create a raster with WGS84 crs and 4m resolution
r2<- raster(xmn=740000, xmx = 740000+100*4,  ymn=3000000, ymx= 3000000+100*4, 
nrow=100, ncol=100, vals=sample(1:50, size = 100*100, replace = TRUE), 
res=4, crs= "+proj=utm +zone=16 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs") 

#Reproject r1 to WGS with 4m resolution 
r1_res4_WGS84<- projectRaster(from = r1, crs = crs(r2), res= res(r2)) 

#Origins do not match after reprojecting    
origin(r1_res4_WGS84) #1.999999e+00 9.094551e-05
origin(r2) #0 0 

#Try reprojecting with alignOnly=TRUE        
r1_res4_WGS84_align<- projectRaster(from = r1, to = r2, alignOnly = TRUE) 
        # Warning in projectRaster(x, crs = projection(y)) :
        #   'from' has no cell values
```

**Comment by rhijmans** [comment]
Thanks, fixed now.  That is, the warning is no longer given. It is expected that the values are lost, this option is just to create a template.

**Comment by ailich** [comment]
Thanks @rhijmans, knowing that it's supposed to make a template makes that behavior clearer. I downloaded the latest version from github, and it does still seem like it might be doing the opposite of what the documentation specifies, or I might still be misunderstanding it a bit. The documentation for the function says for alignOnly, "logical. Use `to` or other parameters only to align the output (i.e. same origin and resolution), but use the projected extent from `from`," but the output has the same origin and resolution as `from` rather than `to`, and the extent seems to be closer to that of `to` rather than `from`.

```
library(raster)
#Create a raster with GRS80 crs and 1.5m resolution
from_rast<- raster(xmn=731458, xmx = 731458+100*1.5,  ymn=3116234, ymx= 3116234+100*1.5, 
            nrow=100, ncol=100, vals=sample(1:50, size = 100*100, replace = TRUE), res=1.5, 
            crs= "+proj=utm +zone=16 +ellps=GRS80 +towgs84=0,0,0,-0,-0,-0,0 +units=m +no_defs ") 

#Create a raster with WGS84 crs and 4m resolution
to_rast<- raster(xmn=740000, xmx = 740000+100*4,  ymn=3000000, ymx= 3000000+100*4, 
            nrow=100, ncol=100, vals=sample(1:50, size = 100*100, replace = TRUE), 
            res=4, crs= "+proj=utm +zone=16 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs") 

#Use to or other parameters only to align the output (i.e. same origin and resolution), but use the projected extent from from
template<- projectRaster(from = from_rast, to = to_rast, alignOnly = TRUE) 

origin(template) # -0.5  0.5
res(template) #1.5 1.5

origin(from_rast) #-0.5  0.5
res(from_rast) #1.5 1.5

origin(to_rast) #0 0
res(to_rast) #4 4
```

**Comment by rhijmans** [comment]
Thank you, as you pointed out via email, from and to were reversed.

**Comment by ailich** [comment]
Thank you, tested it a bit and appears to work now.
