### ISSUE TITLE
rasterProjection with over = TRUE not working

### ISSUE THREAD

**Issue by dominicroye** [rspatial/raster#163]
Today I have noticed that the option over = TRUE does not work anymore. I use the latest version of raster. Any ideas?
In this example it worked fine: https://github.com/robertmonjo/drought

```
# world raster
dat <- getData('worldclim', var='tmin', res=10)

# select first layer
r <- dat[[1]]

#projection 
crs_robin <- "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

#project
r_rob <- projectRaster(r, crs = crs_robin, over = TRUE)

plot(r)
plot(r_rob)
```

Thank you!

**Comment by rhijmans** [comment]
You are saying *what* does not work, making it hard to tell, but it seems to work fine to me.
