### ISSUE TITLE
Simple `extent.bbox` method for interoperability with `sf::st_bbox`

### ISSUE THREAD

**Issue by ashiklom** [rspatial/raster#165]
I often find myself wanting to crop `raster` objects based on the bounding box of a `sf` geometry. However, `raster` doesn't know how to crop against `bbox` objects. I propose a very simple `extent.bbox` method:

```r
# Or whatever the S4 analog of this is...
extent.bbox <- function(x, ...) {
  extent.numeric(x[c("xmin", "xmax", "ymin", "ymax"])], ...)
}
```

That will allow you to do things like:

```r
crop(myraster, extent(st_bbox(mysf))
```

Of course, it would be even nicer if `sf::st_crop` worked with `raster` objects, or `raster::crop` worked with `sf` objects, but that seems more complicated.

For reference, an `st_bbox` object looks like this:

```r
bb <- st_bbox(mysf)
bb
#      xmin      ymin      xmax      ymax 
# 364278.3 4306165.9  364981.6 4306732.6 
str(bb)
#   'bbox' Named num [1:4] 364278 4306166 364982 4306733
#  - attr(*, "names")= chr [1:4] "xmin" "ymin" "xmax" "ymax"
#  - attr(*, "crs")=List of 2
#   ..$ input: chr "+init=epsg:32618 +proj=utm +zone=18 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0"
#   ..$ wkt  : chr "PROJCS[\"UTM Zone 18, Northern Hemisphere\",\n    GEOGCS[\"WGS 84\",\n        DATUM[\"WGS_1984\",\n            # "| __truncated__
#   ..- attr(*, "class")= chr "crs"
```

**Comment by rhijmans** [comment]
> it would be even nicer if raster::crop worked with sf objects, but that seems more complicated.

But it does. For example:

```
library(sf)
pol <- st_sfc(st_polygon(list(cbind(c(0,3,3,0,0),c(0,0,3,3,0)))))
h <- st_sf(r = 5, pol)
r <- raster()
x <- crop(r, h)
```

**Comment by rhijmans** [comment]
You can now also do `extent(st_bbox(h))`
