### ISSUE TITLE
subs success depends on key/value column order

### ISSUE THREAD

**Issue by andycraig** [rspatial/raster#17]
`raster::subs` can throw errors for valid inputs, depending on the order of the key/value dataframe columns specified by the `by` and `which` arguments.

Here's a reproducible example using `raster` version 2.8-1, in which we have a one-cell raster `r` and try to recode its value. (We're trying to recode its value `5` to `0`, in this case.) Whether this happens successfully depends on the order of the columns of the key/value dataframe (argument `y`). 

    r = raster::raster(nrows = 1, ncols = 1, vals = 5)
    key_value_df = data.frame(by_col = c(4, 5, 6), which_col = c(0, 0, 1), another_col = c(7, 8, 9))

    # SUCCESSFUL VERSION. Results in a 1x1 raster with value 0 (substituted from r's value of 5).
    raster::subs(x = r, y = key_value_df, by = "by_col", which = "which_col")
    #> class       : RasterLayer 
    #> dimensions  : 1, 1, 1  (nrow, ncol, ncell)
    #> resolution  : 360, 180  (x, y)
    #> extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
    #> coord. ref. : +proj=longlat +datum=WGS84 
    #> data source : in memory
    #> names       : which_col 
    #> values      : 0, 0  (min, max)

    # FAILING VERSIONS. Key/value dataframe content is the same but the columns are in a different 
    # order. This shouldn't matter, as we are specifying the 'by' and 'which' columns.
    # Expected output is identical to line above: a 1x1 raster with value 0.
    raster::subs(x = r, y = key_value_df[, c(3, 1, 2)], by = "by_col", which = "which_col")
    #> Error in .local(x, y, ...): duplicate "by" values not allowed
    raster::subs(x = r, y = key_value_df[, c(2, 3, 1)], by = "by_col", which = "which_col")
    #> Error in `[.data.frame`(y, , by): undefined columns selected

I am happy to put together a PR for this.

**Comment by rhijmans** [comment]
Thank you for reporting this. Fixed in version 2.8-2

```
library(raster)
r = raster::raster(nrows = 3, ncols = 1, vals = 4:6)
key_value_df = data.frame(by_col = c(4, 5, 6), which_col = c(10, 12, 10), another_col = c(7, 8, 9))
values(subs(x = r, y = key_value_df, by = "by_col", which = "which_col"))
#[1] 10 12 10
key <- key_value_df[, c(3, 1, 2)]
values(subs(x = r, y = key , by ="by_col", which="which_col"))
#[1] 10 12 10
key <- key_value_df[, c(2,3,1)]
values(subs(x = r, y = key , by ="by_col", which="which_col"))
#[1] 10 12 10
 
r2 = raster::raster(nrows = 3, ncols = 1, vals = 6:4)
s <- stack(r, r2)
y = keys = data.frame(by1= c(4, 5, 6), by2= c(6,4,4), which_col = c(10, 12, 10), another_col = c(7, 8, 9))
values(subs(x = s, y = keys, by = 1:2, which = 4))
#[1]  7 NA  9
values(subs(x = s, y = keys, by = 1:2, which = 4:3))
#     another_col which_col
#[1,]           7        10
#[2,]          NA        NA
#[3,]           9        10
values(subs(x = s, y = keys, by = 1:2, which = c(3, 4:3)))
#     which_col another_col which_col.1
#[1,]        10           7          10
#[2,]        NA          NA          NA
#[3,]        10           9          10
```
