### ISSUE TITLE
rasterize on polygons returns an error when applied on IUCN polygons

### ISSUE THREAD

**Issue by Farewe** [rspatial/raster#171]
Hello Robert, 

I am opening a new issue because I am experiencing a bug with `rasterize` on code that was previously working. 

Basically, I am no longer able to reproduce the code on https://gis.stackexchange.com/questions/307770/inconsistencies-in-r-rasterize-polygons-packages-raster-and-sf for both methods. Both chunks of code will create a "no slot" error.

```
Error in cbind(poly, rbind(poly[-1, ], poly[1, ])) : 
  tentative d'obtenir le slot "coords" d'un objet d'une classe élémentaire ("NULL") sans slots
```
The translation should in English should be:
```
Error in cbind(poly, rbind(poly[-1, ], poly[1, ])) : 
  trying to get slot "coords" from an object of a basic class ("NULL") with no slots
```

The code for "method 2" (rasterize on a per-species basis) suggests that it fails only for some specific species, not for all of them.

I have not been able to find a workaround so far.

Session info:
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.3.2 sf_0.9-6      raster_3.3-13 rgdal_1.5-16  sp_1.4-2     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         compiler_4.0.2     pillar_1.4.6       class_7.3-17       tools_4.0.2        digest_0.6.25      lifecycle_0.2.0   
 [8] tibble_3.0.3       gtable_0.3.0       lattice_0.20-41    pkgconfig_2.0.3    rlang_0.4.7        DBI_1.1.0          rstudioapi_0.11   
[15] xfun_0.18          e1071_1.7-3        withr_2.3.0        dplyr_1.0.2        knitr_1.30         generics_0.0.2     vctrs_0.3.4       
[22] classInt_0.4-3     grid_4.0.2         tidyselect_1.1.0   glue_1.4.2         R6_2.4.1           purrr_0.3.4        farver_2.0.3      
[29] magrittr_1.5       scales_1.1.1       codetools_0.2-16   ellipsis_0.3.1     units_0.6-7        colorspace_1.4-1   KernSmooth_2.23-17

```

_Originally posted by @Farewe in https://github.com/rspatial/raster/issue_comments/705591587_

**Comment by Farewe** [comment]
I provide here a reproducible example, with a simplified polygon file: [test_polygons.zip](https://github.com/rspatial/raster/files/5353531/test_polygons.zip)


```
library(sf)
library(raster)
# Example raster
wc <- getData("worldclim", res = 10, var = "tmean")
# Polygon file
testpoly <- readRDS("test_polygons.RData")
# Code that used to work but now fails
richness <- rasterize(testpoly, 
                      wc,
                      field = "binomial",
                      fun = function (x, ...) {length(unique(na.omit(x)))})
```

**Comment by rhijmans** [comment]
In the past I have seen that the IUCN polygons are not very clean (that is, there are invalid polygons), and perhaps that is the problem here. Unfortunately, I cannot read your file. It seems like you saved it with an old version of R?  Either way, it would be better to use `saveRDS` rather than `save`

**Comment by Farewe** [comment]
Hello Robert, 

sorry for the file. I used `saveRDS` but saved into and RData extension... Old habits...
I have updated the file here with the correct extension (.RDS). Run `library(sf)` before `readRDS`.

[test_polygons.zip](https://github.com/rspatial/raster/files/5480735/test_polygons.zip)

**Comment by rhijmans** [comment]
Thanks, I believe this has now been fixed. The error occurred because you are using a character field "binomial". So a work-around would be to replace that with an integer 

s <- as(testpoly, "Spatiall") 
s$id <- as.integer(as.factor(s$binomial)) 
richness <- rasterize(s, r,  field = "id", fun=f)
