### ISSUE TITLE
writeRaster() writes missing band statistic metadata as "1.#SNAN"

### ISSUE THREAD

**Issue by fisher-j** [rspatial/raster#172]
After loading a multi-band raster which does not have band statistics written in the metadata using:
`ras <- stack("multi-band.tif")`
and then subsequently writing it as a GeoTiff  using:
`writeRaster("output.tif")`
the output is written with incorrect metadata statistics. Here is some gdalinfo output:
```
Band 6 Block=1696x1 Type=Float32, ColorInterp=Undefined
  Min=-110.000 Max=20000.000
  Minimum=-110.000, Maximum=20000.000, Mean=1.000, StdDev=1.000
  NoData Value=-3.39999999999999996e+38
  Metadata:
    STATISTICS_MAXIMUM=20000
    STATISTICS_MEAN=1.#SNAN
    STATISTICS_MINIMUM=-110
    STATISTICS_STDDEV=1.#SNAN
```
It seems like the user is not able to control whether statistics metadata is written or not. Currently this requires that I use gdal_edit to recompute or remove bad  metadata.

**Comment by fisher-j** [comment]
I see after looking deeper that there is a (undocumented?) parameter: `setStatistics = T` that can be passed with the `writeRaster` call. This is great, its nice to be able to use such well thought out functions. Now, what could make this better is if it could be possible to set accurate mean and stddev, if so desired.

**Comment by rhijmans** [comment]
That was indeed not documented (it is now). While it would be nice to also have the mean and stddev, I am not going to implement that. But I might do that as an option in the `terra` package.
