### ISSUE TITLE
availableRAM underestimates memory that can be made available

### ISSUE THREAD

**Issue by benfasoli** [rspatial/raster#174]
Thanks for all of your work on raster!

I noticed that many operations were unexpectedly computing out of memory. It appears this is because [src/memory.cpp](https://github.com/rspatial/raster/blob/master/src/memory.cpp) is only considering `freeram` reported by `sysinfo` which omits buffers and caches. Similarly, virtual memory on MacOS is only considering `free_count` reported by `vm_stat` which omits inactive pages. These can make up a significant portion of RAM but most will be freed by the OS when needed.

For example, this is how memory is allocated on two test systems -

```bash
# Linux CentOS 7.6.1810 (3.10.0-957.27.2.el7.x86_64)
> free -h
              total        used        free      shared  buff/cache   available
Mem:            62G        9.0G        5.5G         76M         48G         47G
Swap:           15G        2.9G         13G

# MacOS 10.15.7 (19.6.0)
> vm_stat
Mach Virtual Memory Statistics: (page size of 4096 bytes)
Pages free:                               11835.
Pages active:                           1358456.
Pages inactive:                         1337588.
Pages speculative:                        25648.
Pages throttled:                              0.
Pages wired down:                        701309.
Pages purgeable:                          16272.
"Translation faults":                1525602797.
Pages copy-on-write:                   65411156.
Pages zero filled:                    830156099.
Pages reactivated:                      9255138.
Pages purged:                           7269374.
File-backed pages:                       909450.
Anonymous pages:                        1812242.
Pages stored in compressor:             2053962.
Pages occupied by compressor:            758930.
Decompressions:                        26767288.
Compressions:                          39425305.
Pageins:                               38833433.
Pageouts:                                406554.
Swapins:                               28881755.
Swapouts:                              29545377.
```

In both cases, free memory significantly underestimates memory that should be available to the process. We would expect to be able to use 47GB of memory on the above Linux system (reported by `MemAvailable` from `/proc/meminfo` as of version 3.14 of the Linux kernel). However, raster determines available memory is `5.5GB * memfrac` and instead uses temporary files.

On Linux systems, unfortunately `sys/sysinfo` does not give an estimate of caches. These seem to be the best approximations of available memory -

```bash
# Kernel versions >= 3.14, best estimate
# Use MemAvailable from /proc/meminfo
# See: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773
awk '/MemAvailable/ {print $2}' /proc/meminfo
49534444

# Kernel versions < 3.14
# Source: https://unix.stackexchange.com/questions/261247/how-can-i-get-the-amount-of-available-memory-portably-across-distributions
awk -v low=$(grep low /proc/zoneinfo | awk '{k+=$2}END{print k}') \
 '{a[$1]=$2}
  END{ 
   print a["MemFree:"]+a["Active(file):"]+a["Inactive(file):"]+a["SReclaimable:"]-(12*low); 
  }' /proc/meminfo 
48035124
```

On MacOS, a rough approximation would be `(free_count + inactive_count) * page_size`  given by `host_statistics64`.

I recognize this is a significant shift from how available memory has been determined in the past. It looks like `/proc/meminfo` was [used in the past](https://github.com/rspatial/raster/commit/0b8b356023c4ea355f09a008cfd1ac754d1a0e47) although in a different way from what I'm proposing here.

Is this something you would consider modifying? If so, would you like me to open a PR? I may be able to help with the Linux and MacOS implementations but Windows is out of my element.

**Comment by rhijmans** [comment]
Thank you very much and I would love a PR. I was aware that the estimate was too low for mac, but have not looked into fixing that.
