### ISSUE TITLE
`crop()` doesn't save to file if raster isn't cropped

### ISSUE THREAD

**Issue by mstrimas** [rspatial/raster#177]
If `crop()` is called with an extent that is as large or larger than the input raster, and a `filename` argument is given, the original raster is returned without writing to file.

```
library(raster)
r <- raster(nrow=100, ncol=100)
values(r) <- 1:ncell(r)
e <- extent(r)
crop(r, e, filename = "raster.tif")

class      : RasterLayer 
dimensions : 100, 100, 10000  (nrow, ncol, ncell)
resolution : 3.6, 1.8  (x, y)
extent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
source     : memory
names      : layer 
values     : 1, 10000  (min, max)
```

This is an odd edge case, but I believe `crop()` should treat `filename` consistently regardless of whether or not the raster is actually changed. It's caused an error in some production code I work on where extents are generated programmatically, occasionally give extents the same size as the input raster.

I believe this is happening [here](https://github.com/rspatial/raster/blob/master/R/crop.R#L57):

```
col1 <- colFromX(x, xmin(out)+0.5*xres(out))
col2 <- colFromX(x, xmax(out)-0.5*xres(out))
row1 <- rowFromY(x, ymax(out)-0.5*yres(out))
row2 <- rowFromY(x, ymin(out)+0.5*yres(out))
if (row1==1 & row2==nrow(x) & col1==1 & col2==ncol(x)) {
  return(x)
}
```

Perhaps is should be:

```
if (row1==1 & row2==nrow(x) & col1==1 & col2==ncol(x)) {
  if (filename == "") { 
    return(x)
  } else {
    return(writeRaster(x, filename=filename, datatype=datatype, ...))
  }
}
```

Happy to submit a PR if desired.

**Comment by rhijmans** [comment]
Thanks, I agree that is better to be consistent here and I used your solution.
