### ISSUE TITLE
pkgdown website

### ISSUE THREAD

**Issue by espinielli** [rspatial/raster#178]
It would be interesting to have a pkgdown website for `raster`.
If interested I can chip in.

**Comment by mdsumner** [comment]
easiest way would be to add github actions, something like

```R
usethis::use_github_action("pkgdown")
```

which creates the `.github/*.yml` that triggers the Actions and puts the pkgdown content into branch `gh-pages`. Then you set the URL up in Settings.

**Comment by mdsumner** [comment]
oh except, probably not without roxygen being in use ...  nvm

**Comment by mdsumner** [comment]
actually, it works fine

run

```R
 pkgdown::build_site()
```

whether this gets published in `@master /docs` or on `gh-pages` or also by Actions is extra stuffs

**Comment by rhijmans** [comment]
Thank you for the suggestion. I ran pkgdown::build_site(); and you can go to  https://rspatial.github.io/raster/

**Comment by kadyb** [comment]
Great! As @mdsumner said, you may be interested in automating this activity via GitHub Actions. [Here](https://github.com/r-lib/actions/blob/master/examples/pkgdown.yaml) is a prepared script.

Could you also add URL (https://rspatial.org/raster/index.html or  https://rspatial.github.io/raster/) to the **About** section on GitHub? It will be easier and faster to get there.

**Comment by kadyb** [comment]
```
Reading 'man/raster-package.Rd'
Error: Error: Failed to parse Rd in raster-package.Rd
 there is no package called ‘pls’
```

I don't know why this error occurs.  When I build a website locally, it also shows up. Strangely, if I try to generate this file only, it works fine.

**Comment by rhijmans** [comment]
I think the reason is that `pls` is not in the "Suggested" packages. That
works for CRAN because it is called in an example inside \dontrun{}. It
also works locally, if you have pls installed. Perhaps this is a bug in
pkgdown::build_site, as it seems to ignore the default run_dont_run = FALSE.

**Comment by rhijmans** [comment]
Actually it does not include the dontrun bits; but apparently it still inspects it and finds a missing package.

**Comment by kadyb** [comment]
I think we can add those packages that are mentioned in the examples but not "Suggested" in "Install dependencies" step in workflow. 

```r
# 38 line
install.packages(c("pkgdown", "pls", "randomForest"), type = "binary")
```

Maybe we should contact the `pkgdown` developers (if it's a bug)?

**Comment by kadyb** [comment]
It works: https://github.com/kadyb/raster/blob/master/.github/workflows/pkgdown.yml

**Comment by rhijmans** [comment]
That is good to know, but I would still call it a bug, and I filed a report: https://github.com/r-lib/pkgdown/issues/1621
