### ISSUE TITLE
extract returns attribute data as well?

### ISSUE THREAD

**Issue by jgrn307** [rspatial/raster#180]
Hi all!  One feature I was hoping to see in raster:::extract() is a returned df that contains both the attribute data from the sp/sf object and the extracted raster info all in a neat df -- this would be useful for training/testing models where the response data is in the sf/sp object and the predictors are in the raster.  Is this currently doable (without adding an extra user step to fuse the attribute table back with the extracted df?)  In the case of non-summarized poly/line data, just "repeating" the attribute data would be fine as new columns.

Cheers!

**Comment by rhijmans** [comment]
That feature does not exist. This seems a trivial problem when you have a single value/row for each spatial feature (use `$<-` or `cbind`). What you suggest for non-summarized data is not something I would recommend (creating many copies of the same geometry), but for sp objects it can be done with `sp::merge` --- and merge  can surely used with sf objects as well.

**Comment by jgrn307** [comment]
Would you consider adding it as a feature?  100% of the time we use extract we do this fusion afterwards -- but a lot of beginners get a bit tripped up with the merge.  The repeat isn't ideal (it wastes a lot of space, of course), but it still is a useful feature.

**Comment by rhijmans** [comment]
You can now easily do this with `terra`; and I prefer not to add new functionality to `raster`. 

Extracting values for points: 

```
library(terra)
r <- rast(ncols=5, nrows=5, xmin=0, xmax=5, ymin=0, ymax=5)
values(r) <- 1:25
xy <- rbind(c(0.5,0.5), c(2.5,2.5))
p <- vect(xy, crs="+proj=longlat +datum=WGS84")
p$var <- c("a", "b")

e <- extract(r, p)
v <- cbind(p, e)
v
# class       : SpatVector 
# geometry    : points 
# dimensions  : 2, 3  (geometries, attributes)
# extent      : 0.5, 2.5, 0.5, 2.5  (xmin, xmax, ymin, ymax)
# coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
# names       :   var    ID lyr.1
# type        : <chr> <num> <num>
# values      :     a     1    21
#                   b     2    13
```

With polygons:

```
r <- rast(system.file("ex/elev.tif", package="terra"))
v <- vect(system.file("ex/lux.shp", package="terra"))[, "NAME_2"]
ee <- extract(r, v, fun=mean, na.rm=TRUE)
cbind(v, ee)
# class       : SpatVector 
# geometry    : polygons 
# dimensions  : 12, 3  (geometries, attributes)
# extent      : 5.74414, 6.528252, 49.44781, 50.18162  (xmin, xmax, ymin, ymax)
# coord. ref. : lon/lat WGS 84 (EPSG:4326) 
# names       :   NAME_2    ID elevation
# type        :    <chr> <num>     <num>
# values      : Clervaux     1     467.1
#               Diekirch     2     333.9
#                Redange     3     377.4
```
