### ISSUE TITLE
NEWS file does not list recent changes and is hard to read

### ISSUE THREAD

**Issue by pat-s** [rspatial/raster#182]
The NEWS file shipped with the package was last modified 5 months ago.

In addition its structure is hard to read for users due to lacking structure/indentation.

It would be a great enhancement for users if

- it could be updates regulary and 
- restructured for readability

You might also want to consider switching to `NEWS.md` which improves readability a lot without adding complexity or overhead.

**Comment by rhijmans** [comment]
I am not going to change this as I do not expect that there will be much news in the future. To me, this package is now obsolete (because `terra` is now mature).
