### ISSUE TITLE
stop converting crs = CRS(as.character(NA)) to long/lat

### ISSUE THREAD

**Issue by luigidolcetti** [rspatial/raster#184]
Hi,

I am using raster and sp/sf for NON-geographical purpose.
Creating a raster from a matrix via raster::raster everything works if the dimensions do not exceed those limits (90/180) that triggers the argument crs to be changed to long/lat.... 
Is there any way to prevent this behavior?.... and since I am here, is there a way to set the reference system to pure Cartesian XY and units to micrometers?

Thank you in advance,
Luigi

**Comment by luigidolcetti** [comment]
.... Sorry.... errata corrige: CRS is properly set to NA if limits exceed (90/180) but forced to long/lat if they do not exceed...

Luigi

**Comment by mdsumner** [comment]
You could set it to anything non-longlat "+proj=laea" as good as any other non-angular family. Just need to find one that doesn't cause warnings from proj itself, or rgdal/sp (set the wkt equivalent ultimately).

**Comment by luigidolcetti** [comment]
@mdsumner, thank you very much for your prompt reply. I see your point... I am developing a package for image analysis (histology) using both raster and sf and I found the infrastructure they offer great and unavailable elsewhere (at least in R) I was just wondering if there is a way to re-purpose raster for a micrometer scale and detach it from the geographical environment in a more formal way. Thanks for any suggestion

**Comment by rhijmans** [comment]
There is no formal way. But I can imagine introducing that in `terra`  (the successor or `raster`), i.e. to explicitly support non-geographic image analysis.
