### ISSUE TITLE
crop function output of RasterStack is RasterBrick

### ISSUE THREAD

**Issue by micahwilhelm** [rspatial/raster#185]
When cropping a RasterStack object, the crop function returns a RasterBrick object, which is a bit annoying. 
I'm not sure if this is an intentional feature or a bug. See code below:
**crop.R**
```
	} else if (inherits(x, 'RasterStack')) {
		out <- brick(x, values=FALSE)

```

**Comment by rhijmans** [comment]
It is a general pattern. Almost all functions do this. It is a feature; RasterBricks are better (more efficient) than RasterStacks.
