### ISSUE TITLE
mask multiple values using `mask` function

### ISSUE THREAD

**Issue by MrJGao** [rspatial/raster#186]
I notice the code in the `mask` function has `maskvalue = maskvalue[1]`, do we have to do this? Can we release this limit so we can use `mask` function to select/mask multiple interested values? For example, in NLCD map, code 41, 42, and 43 are all forests, it would be nice if we could select forest pixels by just using `forest <- mask(img, NLCD, maskvalue = c(41, 42, 43), inverse = TRUE)`. 

Thanks!

**Comment by rhijmans** [comment]
You could do this in two steps. First use reclassify, then use mask. But I agree that one step would be nicer! 
I have implemented this in [terra](https://github.com/rspatial/terra)  --- the proposed successor of `raster`. I will fix bugs in raster but I am reluctant to enhance it.
