### ISSUE TITLE
getdata GADM error

### ISSUE THREAD

**Issue by oscarbau** [rspatial/raster#188]
Hi, I am trying to get the boundary level 3 data for Australia but seems the default URL is not working. Is there any alternative URL or method to get the data?

This is the error:

`trying URL 'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_AUS_3_sp.rds'
Error in utils::download.file(url = aurl, destfile = fn, method = "auto",  : 
  cannot open URL 'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_AUS_3_sp.rds'
In addition: Warning message:
In utils::download.file(url = aurl, destfile = fn, method = "auto",  :
  cannot open URL 'https://data.biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_AUS_3_sp.rds': HTTP status was '404 Not Found'`
  
 Cheers
 
 Oscar

**Comment by Yanfei2022** [comment]
hello! did you solve this problem? i also meet the same problem
