### ISSUE TITLE
stack flattens the z field

### ISSUE THREAD

**Issue by bramtayl** [rspatial/raster#193]
I'm not super experienced with R and raster, so maybe this is something I'm doing wrong.

I'm downloading some netCDF files from https://www.northwestknowledge.net/metdata/data/. Each file has a layer for all the days of the year.

Calling `brick` on a file seems to return a `RasterBrick` file, with the `z` field containing a named list with a vector named `day (days since 1900-01-01 00:00:00)`

Then when I try to call `stack` on a `list` of these files, I get a `RasterStack`, whose `z` field seems to be missing, but each layer of which has a single `z` value corresponding to... the first day of the year (even if it it was in December).

Apologies if this has already been fixed or if there's an issue open for this already.

BTW why not store the dates as...dates?

**Comment by bramtayl** [comment]
Also another side note is that `brick` seems to have trouble parsing the CRS given in these files so I have to set it myself.

```
Warning messages:
1: In .getCRSfromGridMap4(atts) : cannot process these parts of the CRS:
long_name=WGS 84
GeoTransform=-124.7666666333333 0.041666666666666 0  49.400000000000000 -0.041666666666666
spatial_ref=GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]
2: In showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj = prefer_proj) :
  Discarded datum unknown in Proj4 definition
3: In showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj = prefer_proj) :
  Discarded datum unknown in Proj4 definition
```

It looks like all the correct info is there? I could post code to reproduce for both issues if it would be helpful

**Comment by rhijmans** [comment]
Sorry for the belated response. I suggest using `terra` instead of `raster`. There is where I put my effort these days; and I am especially keen to get these things (`time`) working well.
