### ISSUE TITLE
Reading and writing tiled rasters

### ISSUE THREAD

**Issue by caiohamamura** [rspatial/raster#195]
When working on very large rasters, it is common to use the GDAL option "TILED=YES" and set appropriate tile sizes. AFAIK the `raster` package will only support to read and write chunks row-wise with writeStart. What about those using tiled approach? 

Tiled is much better when you want to update only a range of interest in your entire raster, say you have updated scenes and want to update your entire world raster accordingly, then then you can update just the tiles overlapping those scenes. With the row approach you would be reading/writing a lot of unnecessary pixels.

Is there any way to work with tiled `GEOTIFF`?

**Comment by rhijmans** [comment]
There is no explicit support for that; but in principle you can set GDAL options when writing. You could then perhaps "manually" work with particular tiles. I am not going to add support to "raster", but I will look into this for "terra". "terra" has some incipient support in the development version (see "tiles" and "vrt" methods).

**Comment by caiohamamura** [comment]
Thanks for the tip. The CPP GDAL already have readBlock and writeBlock methods. I've created my own wrappers in rGEDI from https://github.com/carlos-alberto-silva/rGEDI/blob/rasterizeHDF/R/gdalBindings.R. If you'd like to I could contribute to `terra` to add those features. 

The usage is very simple, though limited to block reading/writing as this was my specific requirement, but could also be easily expanded. Considering `ds` is a wrapper to  GDALDataset class:

```
# Get as instance of GDALRasterBand
band = ds[[1]]

# Reads block (0, 0) as matrix
band[[0, 0]]

# Writes to (0, 0) block of 512 x 512 pixels some dummy values
band[[0, 0]] = 1:(512*512)
```
