### ISSUE TITLE
Result of rotate unexpected if called on raster which already has x extent of -180 to 180

### ISSUE THREAD

**Issue by BENR0** [rspatial/raster#196]
Ideally the call to `rotate` would be idempotent so if it is called on a raster which already has the x extent of -180 to 180 the same raster is returned. 

Of course this could be expected to be user responsibility to know when to call `rotate` and when not. But sometimes extent might not be know in advance.

No breaks in the current behaviour and thus full backwards compatibility is expected with such a change.

The code already contains a warning for certain conditions but the following example does not raise it.

```
r <- raster(nrow=36, ncol=72)
m <- matrix(1:ncell(r), nrow=36)
r[] <- as.vector(t(m))
extent(r) <- extent(-180, 180, -90, 90)

nr <- rotate(r)
```
The result of rotate is a cropped raster with extent(-5, 180, -90, 90). The first if clause would catch this example but the second if does not match so no warning is issued.

**Comment by rhijmans** [comment]
Thanks, good suggestion.
