### ISSUE TITLE
problems with getData

### ISSUE THREAD

**Issue by boris191055** [rspatial/raster#198]
Tried to dowlload data from worldclim and got the following error message 

trying URL 'https://biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/bio_10m_bil.zip'
Error in utils::download.file(url = aurl, destfile = fn, method = "auto",  : 
  cannot open URL 'https://biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/bio_10m_bil.zip'
In addition: Warning message:
In utils::download.file(url = aurl, destfile = fn, method = "auto",  :
  InternetOpenUrl failed: 'A connection with the server could not be established'

**Comment by rhijmans** [comment]
The server was down --- and it is now back. So getData should now work again.
