### ISSUE TITLE
Dates in layer names wrongly use the proleptic Gregorian calendar

### ISSUE THREAD

**Issue by Kodiologist** [rspatial/raster#201]
If I get a file for MERRA-2 with this command, using `ncks` (the netCDF Kitchen Sink):

```
ncks -O --no_tmp_fl -v pm25 -d time,0,2 'https://opendap.nccs.nasa.gov/dods/merra2_gmi/tavg1_2d_aer_Nx' out.nc
```

and read the resulting file with `raster`, I get these layer names:

```
> R --vanilla --slave -e 'library(raster); print(names(stack("out.nc")))'
Loading required package: sp
Loading required namespace: ncdf4
[1] "X1980.01.03.1" "X1980.01.03.2" "X1980.01.03.3"
```

But the time variable actually starts on 1980-01-01:

```
$ ncks -O --no_tmp_fl -v time -d time,0,2 'https://opendap.nccs.nasa.gov/dods/merra2_gmi/tavg1_2d_aer_Nx'

netcdf tavg1_2d_aer_Nx {                
  dimensions:                           
    time = 3 ;                          
                                        
  variables:                                                                    
    double time(time) ;              
      time:grads_dim = "t" ;                                                    
      time:grads_mapping = "linear" ;                                                  
      time:grads_size = "350640" ;                                              
      time:grads_min = "00:30z01jan1980" ;                                      
      time:grads_step = "60mn" ;                                                              
      time:units = "days since 1-1-1 00:00:0.0" ;                                      
      time:long_name = "time" ;                                                        
      time:minimum = "00:30z01jan1980" ;                                                      
      time:maximum = "23:30z31dec2019" ;                                                              
      time:resolution = 0.04166667f ;              

  data:                  
    time = 722816.020833333, 722816.0625, 722816.104166667 ;                                          

} // group /
```

I think this error arises from `raster` interpreting the origin of the time unit as Gregorian rather than Julian. We can see that `time:grads_min` (1980-01-01T00:30:00Z) really is 722816.020833333… days after the origin by subtracting dates in R with a conversion factor between Julian and propletic Gregorian ( https://en.wikipedia.org/wiki/Conversion_between_Julian_and_Gregorian_calendars ):

```
> as.Date("1-1-1") - 2 + 722816
[1] "1980-01-01"
```

**Comment by rhijmans** [comment]
Thank you for reporting. Can you share the file in some way?

**Comment by Kodiologist** [comment]
Here you go:

[out.nc.zip](https://github.com/rspatial/raster/files/6549399/out.nc.zip)

I've added a bogus file extension ".zip" to work around a GitHub limitation. You may need to remove it after downloading.

**Comment by rhijmans** [comment]
Thanks for the file and the clear report. I am not sure what to do with this. 

- The file does not report the calendar used. In that case Gregorian is assumed without a warning. I can add a warning.
- Either way raster does not have logic for "Julian" but a warning would be given if it had been provided. 
-  I could store the 2-day adjustment needed for at least the "0001-01-01" origin
- `time:grads_min = "00:30z01jan1980"` also tells us what the adjustment should be, but that is not a standard field

So the best I can do, perhaps, is to check for `time:grads_min` to accommodate GrADS-netcdf files.

**Comment by rhijmans** [comment]
This is a bit more complicated than it looked at first sight.  These are the time attributes.
```
 $ grads_dim    : chr "t"
 $ grads_mapping: chr "linear"
 $ grads_size   : chr "350640"
 $ grads_min    : chr "00:30z01jan1980"
 $ grads_step   : chr "60mn"
 $ units        : chr "days since 1-1-1 00:00:0.0"
 $ long_name    : chr "time"
 $ minimum      : chr "00:30z01jan1980"
 $ maximum      : chr "23:30z31dec2019"
 $ resolution   : num 0.0417
```

The reported time "step" is 60 minutes, but the "unit" is days. Time span ("size") is from 1980-01-01 through 2019-12-31. That is 146010 days. `14610 * 24 = 350640 which matches the reported range. However, the file has only three days. Obviously because you subsetted the original file. But since subsetting did not update the metadata, it is now uncertain whether the time of the first layer is in fact the reported start time. 

With that much uncertainty I am not sure if I should try to fix this.

**Comment by Kodiologist** [comment]
Perhaps the metadata isn't correct, because of a flaw in either GrADS Data Server itself or the configuration of this instance. I'm not familiar with the relevant standards.

**Comment by rhijmans** [comment]
Closing this because it cannot be resolved with the information at hand, and the use of this calendar seems exceedingly rare.
