### ISSUE TITLE
behaviour "adjacent" function

### ISSUE THREAD

**Issue by jvandoninck** [rspatial/raster#202]
The adjacent functions seems to identify the first and last cell of each row as adjacent:

r <- raster(ncol=5, nrow=10)
values(r) <- 1:50
adjacent(r, 1, directions=4)

Returns:
     from to
[1,]    1  5
[2,]    1  2
[3,]    1  6

Cell 1 (first of row) and cell 5 (last of row) should not be listed as  pair.

**Comment by kbvernon** [comment]
Hi. I had the same confusion about this function. It turns out the behavior you are looking for only occurs when the raster has a projected crs.

```
r <- raster(ncol=5, nrow=10, crs="+proj=longlat +datum=WGS84")
adjacent(r, 1, directions = 4)
#      from to
# [1,]    1  5
# [2,]    1  2
# [3,]    1  6

r <- raster(ncol = 5, nrow = 10, crs="+proj=utm +zone=1 +datum=WGS84")
adjacent(r, 1, directions = 4)
#      from to
# [2,]    1  2
# [3,]    1  6
```

So, this is expected behavior rather than a bug.

Cheers,

**Comment by rhijmans** [comment]
When the raster consist of lon/lat data and the longitude spans -180 to 180, the E and W edges are adjacent.
