### ISSUE TITLE
raster::predict can't produce a RasterBrick

### ISSUE THREAD

**Issue by lucas-johnson** [rspatial/raster#204]
### Description

It seems like `raster::predict` will only produce a single `rasterLayer` even if your prediction function returns a list of values. My goal is to produce a brick/stack of predictions at each cell using a single call to predict. 

If this is not possible, the work-around seems to be to make a loop and build the brick on my own. 

Any help would be appreciated!

**Comment by rhijmans** [comment]
This should work better with `terra::predict`, but with `raster::predict` you should be able to use the argument `index`.
