### ISSUE TITLE
extend doesn't extend as expected

### ISSUE THREAD

**Issue by plantarum** [rspatial/raster#205]
Hello,

I have found an unexpected behaviour when trying to extend an extent. Here's a toy example to demonstrate the issue:

```R
myExtent <- extent(-90.1978, -71.1061, 38.6272, 43.75)
myRaster <- raster(myExtent)
myRaster <- extend(myRaster, extent(myRaster) + 1)
extent(myRaster)
# class      : Extent 
# xmin       : -90.1978 
# xmax       : -71.1061 
# ymin       : 38.11492 
# ymax       : 44.26228 
```

This is based on actual code where I'm trying to extend the raster layer "a little" in order not to lose points along the edge of the raster, as demonstrated on [rspatial.org](https://rspatial.org/raster/sdm/2_sdm_occdata.html#sampling-bias). 

In this case, after 'extending' my raster, the xlimits are in fact identical to the original xlimits. Walking through the code, this is due to the call to `alignExtent` from within `extend`, which uses the default snap value of "near". I think this snaps the extent to the nearest grid line, based on resolution and the distance from the origin. In some cases this will end up being the original limits.

Setting the resolution properly before calling `extend` fixes this problem, so I could chalk it up to user error. However, I wonder if it would make sense for calls to `extend` to use `alignExtent(..., snap = "out")` to guarantee extending actually extends? Or maybe to just issue a warning when the original and extended extents are the same in one or both directions?

Thanks,

Tyler

**Comment by mdsumner** [comment]
that's good to know - `snap="out"` seems sensible, note that `terra` does the right thing with the new `expand()` function: 

```R
myExtent <- ext(-90.1978, -71.1061, 38.6272, 43.75)
myRaster <- rast(myExtent)
expand(myRaster, ext(myRaster) + 1)
class       : SpatRaster 
dimensions  : 140, 413, 1  (nrow, ncol, nlyr)
resolution  : 0.051228, 0.051228  (x, y)
extent      : -91.22236, -70.0652, 37.60264, 44.77456  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +no_defs 

```
fwiw I made `spex::buffer_extent()` which extends out as far as required to a given resolution, so that the boundaries are aligned to that resolution, relative to 0.   I use that much more often than extend, but it's a clear alternative case (which I don't think exists in raster/terra?). 


```R
myExtent <- extent(-90.1978, -71.1061, 38.6272, 43.75)
myRaster <- raster(myExtent)

## align to whole increments of 0.2 from 0
spex::buffer_extent(myRaster, .2)
class      : Extent 
xmin       : -90.2 
xmax       : -71 
ymin       : 38.6 
ymax       : 43.8 
```

**Comment by rhijmans** [comment]
Thanks for reporting this. I have added a `snap` argument. The default `snap="near"` is perhaps not the best, but I do not want to change defaults in `raster` as there too much code out there that might be affected. 

Now I get 

```
library(raster)
#Loading required package: sp
myExtent <- extent(-90.1978, -71.1061, 38.6272, 43.75)
myRaster <- raster(myExtent)
myRaster <- extend(myRaster, extent(myRaster) + 1)
extent(myRaster)
#class      : Extent 
#xmin       : -90.1978 
#xmax       : -71.1061 
#ymin       : 38.11492 
#ymax       : 44.26228 
 
myRaster <- extend(myRaster, extent(myRaster) + 1, snap="out")
extent(myRaster)
#class      : Extent 
#xmin       : -92.10697 
#xmax       : -69.19693 
#ymin       : 37.60264 
#ymax       : 44.77456 
```

**Comment by rhijmans** [comment]
to @mdsumner: with `terra` you can do that like this:

```
library(terra)
myExt <- ext(-90.1978, -71.1061, 38.6272, 43.75)
myRast <- rast(myExtent)
 
ext(myRast) <- align(myExt, 0.2)
myRast
#class       : SpatRaster 
#dimensions  : 10, 10, 1  (nrow, ncol, nlyr)
#resolution  : 1.92, 0.52  (x, y)
#extent      : -90.2, -71, 38.6, 43.8  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
```

(it was *not my* [idea](https://github.com/rspatial/terra/issues/102)  :wink:)

**Comment by mdsumner** [comment]
Oh right, yep cool that's magic 😅

**Comment by plantarum** [comment]
Thanks for the fast responses!

I take it terra is intended to replace raster? Should I be migrating my work?
