### ISSUE TITLE
did Arith for Extent change?

### ISSUE THREAD

**Issue by mdsumner** [rspatial/raster#206]
The source suggests this changed at least 3 years ago? 

https://github.com/rspatial/raster/blame/master/R/arith.R#L371-L372

dx, dy halved was a bit of a shock to me, surprised it hasn't bitten me before now?  It doesn't make sense to me to add half the e2 value

```R
library(raster)
extent(0, 1, 0, 1) + 1
#class      : Extent 
#xmin       : -0.5 
#xmax       : 1.5 
#ymin       : -0.5 
#ymax       : 1.5 
library(terra)
ext(0, 1, 0, 1) + 1
#SpatExtent : -1, 2, -1, 2 (xmin, xmax, ymin, ymax) 
```

**Comment by rhijmans** [comment]
It seems like something reasonable people could disagree on.  When adding `x` to an extent, terra adds it at both sides, and in effect adds `2x`?  So what raster does seems mathematically more consistent; but probably less intuitive and less practical.  I do not like changing this kind of thing in raster (apparently I was not that careful 3 years ago) -- but I also do not like that `raster` and `terra` are different in this respect --- it is probably more important to be consistent than to be right in this case.

**Comment by mdsumner** [comment]
I was shocked to find it 1x in raster, I would swear it always buffered fully both sides (I have relied on it for ages, but never noticed any errors because of that ...).

I'm sympathetic to the question of what's more reasonable, but I'm firmly with the current terra behaviour.

**Comment by rhijmans** [comment]
I changed it back with https://github.com/rspatial/raster/commit/b9c32407c049c68de75139317fcf1fb3e4448175. And I will keep it that way, unless it breaks the revdeps

**Comment by mdsumner** [comment]
oh, thank you - I put in a workaround somewhere

(fwiw, I've been thinking about transform-concepts, and things like translate, scale for extents - these Ops in terra could really benefit from a richer set, though they probably don't belong on Arith - just in case you've done anything there - I don't think it needs affine transform chains, just straightforward ways to adjust an extent)

**Comment by rhijmans** [comment]
Does this cover some of that? 

```
library(terra)
#terra version 1.5.1
e = ext(0,1,0,1)
e*2
#SpatExtent : -0.5, 1.5, -0.5, 1.5 (xmin, xmax, ymin, ymax)
e/2
#SpatExtent : 0.25, 0.75, 0.25, 0.75 (xmin, xmax, ymin, ymax)
shift(e, -3, 3)
#SpatExtent : -3, -2, 3, 4 (xmin, xmax, ymin, ymax)
```

What is missing?

**Comment by mdsumner** [comment]
oh I think it does, thanks - I've got some stuff to try rn

**Comment by mdsumner** [comment]
that covers what I was thinking of thank you!

**Comment by rhijmans** [comment]
This change broke a number of reverse dependencies, so I cannot readily make this change right now. It would be possible to do it, but it would be a messy process, so I think I prefer to leave it as-is. 
At this stage it should also be possible to change the behavior of terra; that would be easier. 
Or just accept this as one of the quirky differences between the two.
