### ISSUE TITLE
Raster::raster() not properly changing sp or sf objects to raster objects

### ISSUE THREAD

**Issue by coconn41** [rspatial/raster#207]
`raster::raster()` seems to not be allowing sp or sf objects to be changed to raster objects

I posted this on stack exchange here: https://gis.stackexchange.com/questions/402385/r-raster-package-unable-to-properly-convert-sp-or-sf-feature-to-raster

Below is a reprex, and my dataset is different, but it seems that the new raster objects are not correct after the `raster::raster()` call. I had working code that utilized this call previously, but today it decided to stop working.

```
library(sp)
library(raster)
data("meuse.grid")
coordinates(meuse.grid) = ~x+y
mraster=raster(meuse.grid)
```
Note that the summary of meuse.grid (non-raster) appears as:
```
> meuse.grid
class       : SpatialPointsDataFrame 
features    : 3103 
extent      : 178460, 181540, 329620, 333740  (xmin, xmax, ymin, ymax)
crs         : NA 
variables   : 5
names       : part.a, part.b,     dist, soil, ffreq 
min values  :      0,      0,        0,    1,     1 
max values  :      1,      1, 0.992607,    3,     3 
```
while the summary of the raster version of meuse grid appears as:
```
> mraster
class      : RasterLayer 
dimensions : 10, 10, 100  (nrow, ncol, ncell)
resolution : 308, 412  (x, y)
extent     : 178460, 181540, 329620, 333740  (xmin, xmax, ymin, ymax)
crs        : NA 
```
See that the dimensions of the raster are reduced to 100 cells. In my personal dataset (not shown here), the dataset reduces from 69759 cells to 100 as well.

**Comment by rhijmans** [comment]
`meuse.grid` is a `SpatialPointsDataFrame`. It does not have rows, columns, or cells, so there is no basis for comparison. 
All that raster(`meuse.grid`) does (and can do) is create a `RasterLayer` with the same extent. See `rasterize` or for the odd case like this one, where the points have a regular pattern, `rasterFromXYZ`. 

```
data("meuse.grid")
b = rasterFromXYZ(meuse.grid)
b
#class      : RasterBrick 
#dimensions : 104, 78, 8112, 5  (nrow, ncol, ncell, nlayers)
#resolution : 40, 40  (x, y)
#extent     : 178440, 181560, 329600, 333760  (xmin, xmax, ymin, ymax)
#crs        : NA 
#source     : memory
#names      :   part.a,   part.b,     dist,     soil,    ffreq 
#min values :        0,        0,        0,        1,        1 
#max values : 1.000000, 1.000000, 0.992607, 3.000000, 3.000000 
```

Or 

```
coordinates(meuse.grid) = ~x+y
gridded(meuse.grid) =T
r <- brick(meuse.grid)
r
#class      : RasterBrick 
#dimensions : 104, 78, 8112, 5  (nrow, ncol, ncell, nlayers)
#resolution : 40, 40  (x, y)
#extent     : 178440, 181560, 329600, 333760  (xmin, xmax, ymin, ymax)
#crs        : NA 
#source     : memory
#names      :   part.a,   part.b,     dist,     soil,    ffreq 
#min values :        0,        0,        0,        1,        1 
#max values : 1.000000, 1.000000, 0.992607, 3.000000, 3.000000 
```
