### ISSUE TITLE
canProcessInMemory does not work with terra's SpatRaster

### ISSUE THREAD

**Issue by tungmilan** [rspatial/raster#208]
Hi Robert,

I tried `canProcessInMemory()` with terra's SpatRaster but got the following error message. Did I do something wrong? Thanks!

```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘nlayers’ for signature ‘"SpatRaster"’
```

**Comment by rhijmans** [comment]
The short answer is "yes". Per the manual, the first argument (`x`) of `canProcessInMemory` must be a Raster* object. 
I do not know what you want to achieve, but `terra` has a function `mem_info`.

**Comment by tungmilan** [comment]
Thank you Robert!
