### ISSUE TITLE
Datatype documentation missing

### ISSUE THREAD

**Issue by estebangatillo** [rspatial/raster#209]
Hi, thank you very much for the raster package. Truly wonderful work. 

I noticed a few links to [documentation pages](https://www.rdocumentation.org/link/dataType?package=raster&version=3.4-13) for arguments within `writeRaster` [are missing](https://www.rdocumentation.org/packages/raster/versions/3.4-13/topics/writeRaster). If package managers were aware of this (which they likely are) please disregard. Otherwise, it was a small thing I noticed that I thought I'd bring to your attention.

Again, thank you for your work and have a great day!

**Comment by rhijmans** [comment]
Thank you for reporting that, but you that is on www.rdocumentation.org --- I do not know who runs that, and I have no control over it.  The link to `dataType` works in R (html help) and [on this site](https://rspatial.github.io/raster/reference/writeRaster.html)
