### ISSUE TITLE
Warning: no function found corresponding to methods exports from 'raster' for: 'wkt'

### ISSUE THREAD

**Issue by graywh** [rspatial/raster#214]
Is there an external dependency I need?  There were no errors during package install.

raster 3.4-13
R 3.6.3
macOS 10.13.6

**Comment by rhijmans** [comment]
Can you provide an example? I see 

```
raster::wkt(raster::raster())
#[1] ""
#Warning message:
#In raster::wkt(raster::raster()) : no wkt comment
```
 
I would suggest updating R first, version `3.6.3` is ancient history.
