### ISSUE TITLE
Cannot extract value from raster file with cellnumbers

### ISSUE THREAD

**Issue by leminhson** [rspatial/raster#217]
In order to extract value at a point from Raster object, I use this command:
`result = extract(myRaster, myPoint, method="bilinear",df=T)`
This command runs smoothly. But the problem is:
1) If I include the option **cellnumbers=T**, such as:
`result = extract(myRaster, myPoint, method="bilinear", df=T, cellnumbers=T`
the command will fail with the error:
`Error in names(x) <- value : 
  'names' attribute [3] must be the same length as the vector [2]`
2) If I include the option **cellnumbers=T** without **df=T**, such as:
`result = extract(myRaster, myPoint, method="bilinear", cellnumbers=T`
the command can run but the **result is a vector**, **not a dataframe**, so the cellnumbers are also missing

Is that a bug or my command is not correct ?

**Comment by rhijmans** [comment]
Thank you. I now get

```
library(raster)
#Loading required package: sp
r <- raster(ncol=36, nrow=18, vals=1:(18*36))
xy <- cbind(-50, seq(-80, 80, by=20))
extract(r, xy[1,,drop=F], df=T, cellnumbers=T)
#  ID cells layer
#1  1   626   626
extract(r, xy[1,,drop=F], df=T, cellnumbers=T, method="bilinear")
#  ID layer
#1  1 607.5
#Warning message:
#In .xyValues(x, y, method = method, buffer = buffer, small = small,  :
#  'cellnumbers' does not apply for bilinear values
```

(but you *can* get the bilinear cell numbers with `terra::extract`)
