### ISSUE TITLE
filename not recognised as argument in brick()

### ISSUE THREAD

**Issue by aloboa** [rspatial/raster#22]
Is this a bug? 
```
> a <- array(runif(3*5*6),dim=c(3,5,6))
> b <- brick(a,filename="a")
Error in .local(x, ...) : unused argument (filename = "a")
```
filename is listed in ?brick as an optional parameter.
Found using raster_2.8-3 rgdal_1.3-4  sp_1.3-1 R version 3.5.1 on windows

**Comment by rhijmans** [comment]
Given that `a` is an array, you are using 
```
In this case, you have to do 
```
a <- array(runif(3*5*6),dim=c(3,5,6))
b <- brick(a)
writeRaster(b, filename="a")
```

## S4 method for signature 'array'
brick(x, xmn=0, xmx=1, ymn=0, ymx=1, crs=NA, transpose=FALSE)
```
So there is no `filename` argument.

It is an argument for the currently obsolete case 
```
## S4 method for signature 'big.matrix'
brick(x, template, filename='', ...)
```
i.e., when x is a `big.matrix`.  This does not work either as I had to remove that when the `bigmemory` stopped working on windows, but I should restore that again (or remove it from the manual!).

**Comment by aloboa** [comment]
I have a problem when the dimensions of a are moderately large (x=969; y=640; z=224),
my hope was to avoid bringing the brick into memory by using filename. Is there an alternative?
I'm posting the whole example to stackexchange in a minute, perhaps there is an entirely different approach. Thanks
agus

**Comment by aloboa** [comment]
> 
> 
> Given that `a` is an array, you are using
> 
> ```
> ## S4 method for signature 'array'
> brick(x, xmn=0, xmx=1, ymn=0, ymx=1, crs=NA, transpose=FALSE)
> ```
> 
> So there is no `filename` argument. In this case, you have to do
> 
> ```
> a <- array(runif(3*5*6),dim=c(3,5,6))
> b <- brick(a)
> writeRaster(b, filename="a")
> ```
> 
> It is an argument for the currently obsolete case
> 
> ```
> ## S4 method for signature 'big.matrix'
> brick(x, template, filename='', ...)
> ```
> 
Please include this clarification in the help page, perhaps just the example. 

> i.e., when x is a `big.matrix`. This does not work either as I had to remove that when the `bigmemory` stopped working on windows, but I should restore that again (or remove it from the manual!).
Hope you can restore it, or perhaps, just let the user write to disk for any array size.
