### ISSUE TITLE
getData not working

### ISSUE THREAD

**Issue by oliveirab** [rspatial/raster#223]
Hi,
I am having this message when trying to use getData for downloading worldclim data:

trying URL 'https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_5m_bio.zip'
cannot open URL 'https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_5m_bio.zip': HTTP status was '403 Forbidden'Error in utils::download.file(paste0(.wcurl, "base/", zip), pzip, mode = "wb") : 
  cannot open URL 'https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_5m_bio.zip'

Download through worldclim website also not working...

**Comment by rhijmans** [comment]
The server is down for maintenance. It should work again Monday evening (California time).
