### ISSUE TITLE
`focal` with `NAonly = TRUE` can change all cells

### ISSUE THREAD

**Issue by frousseu** [rspatial/raster#226]
Hi

While trying to figure out how to get a result using focal, I noticed that sometimes actual values are replaced even when using the argument `NAonly = TRUE`. Here is an example:

```
library(raster)
ras <- raster(ncol = 9, nrow = 9, ext = extent(c(0, 1, 0, 1)))
ras <- setValues(ras, runif(ncell(ras)))
ras[41] <- NA

par(mfrow = c(1, 3))

plot(ras, colNA = "gray", zlim = 0:1)

ras2 <- focal(ras, w = matrix(rep(1, 9)/9, ncol=3), na.rm = FALSE, NAonly = TRUE)
plot(ras2, colNA = "gray", zlim = 0:1)

ras3 <- focal(ras, w = matrix(rep(1, 9), ncol = 3), fun = mean, na.rm = TRUE , NAonly = TRUE)
plot(ras3, colNA = "gray", zlim = 0:1)

par(mfrow = c(1 , 1))
```
The second option shows that cell values are changed and not just the center value which was set to `NA`. The third option works in the sense that cells with values are not changed (although I'm not sure I figured out how to correctly compute the center when `NA` are present). This is with raster 3.5-2

Thanks!
François

**Comment by rhijmans** [comment]
Thank you very much and sorry for the delay. Too busy with `terra` these days. Originally I did not allowed to have `NAonly=TRUE` and `na.rm=FALSE` because I thought it was a contradiction. At some point I realized it was not, so I removed the restriction but did not check the results, it seems. I believe it works now:

```

library(raster)
ras <- raster(ncol = 9, nrow = 9, ext = extent(c(0, 1, 0, 1)))
ras <- setValues(ras, 1)
ras[41] <- NA

ras2 <- focal(ras, w=matrix(rep(1, 9), ncol=3), fun = sum, na.rm = FALSE, NAonly = TRUE)
ras3 <- focal(ras, w = matrix(rep(1, 9), ncol = 3), fun = sum, na.rm = TRUE , NAonly = TRUE)

par(mfrow = c(1, 3))
plot(ras, colNA = "red")
plot(ras2, colNA = "red")
plot(ras3, colNA = "red")
```
![focal](https://user-images.githubusercontent.com/11481397/145105142-46334953-0b21-4dcf-8871-1b78a4d90538.png)

**Comment by frousseu** [comment]
Thank you for your response and for the fix. I'm not sure I understand why the middle cell is evaluated to 4 in the second case, but I always had a bit of difficulty understanding how focal works with weights.

I haven't made the switch to terra yet, but I should really be starting to look into it!
