### ISSUE TITLE
Large rasters lose layer names

### ISSUE THREAD

**Issue by ailich** [rspatial/raster#228]
I'm running into an issue where rasters too large to fit in memory lose their layer names. Here's an example with a datset that can be downloaded [here](https://usf.box.com/s/5h4baxorzdvg9nmpi7rm29zr6rcu1unu).

```
library(raster)
packageVersion("raster")
# 3.5.3

# Name Preserved when fits in memory
r<- raster("C://Users/socce/Downloads/gebco_ns.tif")
canProcessInMemory(r)
#TRUE
names(r)
# "gebco_ns"
r[r>=0]<- NA
names(r)
# "gebco_ns" 

# Name lost when raster cannot fit in memory
rasterOptions(maxmemory=1*10^5) #lower memory
r2<- raster("C://Users/socce/Downloads/gebco_ns.tif")
canProcessInMemory(r2)
# FALSE
names(r2)
# "gebco_ns"
r2[r2>=0]<- NA
names(r2)
"layer"
```

**Comment by rhijmans** [comment]
raster does not write names to tif files. Maybe that is possible now trough rgdal, but I am not going to change behavior like this anymore in raster; unless it really is a bug of wrong; as there is too much code that depends on its current behavior. Better to move to terra.
