### ISSUE TITLE
clusterR and inverse masking

### ISSUE THREAD

**Issue by jgiovando** [rspatial/raster#229]
After several ways of trying to use the mask function with the "inverse" argument within clusterR, I could not determine the correct input. I attempted to use the args=list(mask, inverse = TRUE) with clusterR but this caused a cluster error.  Masking seems to work fine within  clusterR call if the "inverse" argument is omitted.

**Comment by rhijmans** [comment]
The thing with the `mask` method is that it takes two Raster objects as argUments (`x` and `mask`), whereas `clusterR` can only take one.  But we can work around that.

Example data 

```
library(raster)
r <- raster(ncol=10, nrow=10)
m <- raster(ncol=10, nrow=10)
values(r) <- runif(ncell(r)) * 10
values(m) <- runif(ncell(r))
m[m < 0.5] <- NA
x <- mask(r, m)
y <- mask(r, m, inverse=TRUE)
``` 

To use clusterR we write a new function 

```
f <- function(s, inverse=FALSE) {
	mask(s[[1]], s[[2]], inverse=inverse)
} 
``` 

And use it 

```
beginCluster()
cx <- clusterR(s, f)
cy <- clusterR(s, f, args=list(inverse=TRUE))
endCluster()
```
