### ISSUE TITLE
gridDistance 'no function found'

### ISSUE THREAD

**Issue by MurrayEfford** [rspatial/raster#239]
Checking my 'secr' and 'openCR packages' in R-devel (but not R-release) on WinBuilder I get warnings like this:

Found the following significant warnings:
  Warning: no function found corresponding to methods exports from 'raster' for: 'gridDistance'

These packages import from 'raster' and suggest 'terra', but 'gridDistance' does not appear in their code. I expect the problem will resolve itself, but is there anything I should do?

Murray

**Comment by rhijmans** [comment]
The messages is different from what I and others have seen (https://github.com/rspatial/terra/issues/485) but I think it is safe to assume that this will resolve itself (raster needs to be rebuild with the new version of terra), and that this is nothing you should worry about.

**Comment by MurrayEfford** [comment]
Thanks. I submitted the package and the warning does not appear in R-devel checks there, so I can relax.

**Comment by rhijmans** [comment]
Good --- the CRAN experience can be stressful.
