### ISSUE TITLE
raster::area results are not in km2 for projected CRS

### ISSUE THREAD

**Issue by see24** [rspatial/raster#240]
The documentation says that `area()` returns area in km2 for RasterLayer objects but it does not tell you that if you use a raster with a projected CRS the area is in map units (in this case m2). There is a warning generated that says the function is is only useful for Raster* objects with a longitude/latitude coordinates. But if a user finds it useful despite the warning they will be using the wrong units. 
 
``` r
library(raster)
rast <- raster(matrix(0, nrow = 100, ncol = 100))

crs(rast) <- "EPSG:4326"

area(rast)
# class      : RasterLayer 
# dimensions : 100, 100, 10000  (nrow, ncol, ncell)
# resolution : 0.01, 0.01  (x, y)
# extent     : 0, 1, 0, 1  (xmin, xmax, ymin, ymax)
# crs        : +proj=longlat +datum=WGS84 +no_defs 
# source     : memory
# names      : layer 
# values     : 1.230723, 1.230907  (min, max)

rast2 <- projectRaster(rast, crs = 3162)
area(rast2)

# class      : RasterLayer 
# dimensions : 157, 158, 24806  (nrow, ncol, ncell)
# resolution : 1360, 1370  (x, y)
# extent     : 11222373, 11437253, 12971622, 13186712  (xmin, xmax, ymin, ymax)
# crs        : +proj=lcc +lat_0=0 +lon_0=-85 +lat_1=44.5 +lat_2=53.5 +x_0=930000 +y_0=6430000 +ellps=GRS80 +units=m +no_defs 
# source     : memory
# names      : layer 
# values     : 1863200, 1863200  (min, max)
```

**Comment by rhijmans** [comment]
Thanks, fixed

**Comment by rhijmans** [comment]
I slightly changed it though because what you get is the product of the x and y resolution. This can be a far cry from the actual cells size. You can use terra::cellSize instead.
