### ISSUE TITLE
can't use Package raster

### ISSUE THREAD

**Issue by othmaner10** [rspatial/raster#246]

**Comment by rhijmans** [comment]
You need to first install the current version of `terra`. The problem is that CRAN has not build the binary for windows yet. But you can install it like this:

```
install.packages('terra', repos='https://rspatial.r-universe.dev')
```

And then re-install `raster` 

```
install.packages("raster")
```

**Comment by othmaner10** [comment]
thank you !

**Comment by othmaner10** [comment]
thank you !

**Comment by othmaner10** [comment]
thank you !
