### ISSUE TITLE
Error in sp::CRS(...) : NA when reading GEBCO bathymetry

### ISSUE THREAD

**Issue by MikkoVihtakari** [rspatial/raster#248]
This is not a big problem as the "error" does not actually stop the function (and hence is not an error). Just thought you may be interested in adjusting the messages `raster::raster()`(or `sp/rdgal::CRS()`) returns since GEBCO products are widely used.

I download the GEBCO_2021 Grid (ice surface elevation) netCDF bathymetry from [here](https://www.gebco.net/data_and_products/gridded_bathymetry_data/) and try to open it with the `raster()`function:

``` r
library(raster)
#> Loading required package: sp

raster("~/Desktop/gebco_2021/GEBCO_2021.nc")
#> Loading required namespace: ncdf4
#> Error in sp::CRS(...) : NA
#> class      : RasterLayer 
#> dimensions : 43200, 86400, 3732480000  (nrow, ncol, ncell)
#> resolution : 0.004166667, 0.004166667  (x, y)
#> extent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#> crs        : NA 
#> source     : GEBCO_2021.nc 
#> names      : Elevation.relative.to.sea.level 
#> zvar       : elevation
```

The error appears (because the grid has no crs). It did not appear with the 2020 grid. 

I try: 

``` r
raster::raster("~/Desktop/gebco_2021/GEBCO_2021.nc", crs = "+proj=longlat +datum=WGS84")
#> Loading required namespace: ncdf4
#> Warning in .getProj(prj, crs): argument "crs" ignored because the file provides
#> a crs
#> Error in sp::CRS(...) : NA
#> class      : RasterLayer 
#> dimensions : 43200, 86400, 3732480000  (nrow, ncol, ncell)
#> resolution : 0.004166667, 0.004166667  (x, y)
#> extent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#> crs        : NA 
#> source     : GEBCO_2021.nc 
#> names      : Elevation.relative.to.sea.level 
#> zvar       : elevation
```

Well, according to `raster()` it does and does not have a crs. 

Also, suppressing the message seems impossible using the standard R approach:

``` r
suppressMessages(suppressWarnings(raster::raster("~/Desktop/gebco_2021/GEBCO_2021.nc")))
#> Error in sp::CRS(...) : NA
#> class      : RasterLayer 
#> dimensions : 43200, 86400, 3732480000  (nrow, ncol, ncell)
#> resolution : 0.004166667, 0.004166667  (x, y)
#> extent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#> crs        : NA 
#> source     : GEBCO_2021.nc 
#> names      : Elevation.relative.to.sea.level 
#> zvar       : elevation
```

I suppose one could use the sink trick but that is beyond the point. 

<sup>Created on 2022-01-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
Thank you for reporting this. I now see: 

```
f
#[1] "GEBCO_2021.nc"
library(raster)
brick(f) |> proj4string()
#[1] "+proj=longlat +datum=WGS84 +no_defs"
``` 

But I would suggest using `terra` instead of `raster`:

```
library(terra)
rast(f) |> crs(proj=TRUE)
#[1] "+proj=longlat +ellps=WGS84 +no_defs"
``` 

The reason for this to fail is that the files specifies `epsg_code = "EPSG:5831"` where I expected `epsg_code = "5831"`.  It looks like my expectation was wrong (but anything goes in netcdf, and now both cases should work).
