### ISSUE TITLE
projectRaster() is duplicating cells

### ISSUE THREAD

**Issue by geotheory** [rspatial/raster#250]
Previously reported at [rstudio/leaflet](https://github.com/rstudio/leaflet/issues/774) but I see their implementation (`projectRasterForLeaflet()`) simply wraps `projectRaster()`, so re-posting here.  Just read `projectRaster()` in place of refs to `addRasterImage()` and `projectRasterForLeaflet()` below.

--------------

`addRasterImage()` (Edit: maybe more accurately `projectRasterForLeaflet()`) is rendering duplicate cells above/below, presumably due to the original geoms spanning two target geoms.  I appreciate the challenge of interpolating a raster to a new specification, but feel this needs to be addressed as duplicate symbols are much more misleading than slightly mispositioned ones.

**Example:**

```r
require(leaflet)
require(dplyr)

set.seed(42)

d = readr::read_csv('https://gist.githubusercontent.com/curran/13d30e855d48cdd6f22acdf0afe27286/raw/0635f14817ec634833bb904a47594cc2f5f9dbf8/worldcities_clean.csv') |> 
  group_by(lon = 5*round(lng/5), lat = 5*round(lat/5)) |> 
  summarise(n = length(lat), .groups = 'drop') |> 
  sample_n(100)

require(raster)
ras = rasterFromXYZ(d, crs = '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs') 
plot(ras)

col_pal = colorNumeric("magma", domain = NULL, na.color = 'transparent', reverse = TRUE)

leaflet(ras) |>  
  addProviderTiles("Stamen.TonerLite", group = "Toner",
                   options = providerTileOptions(noWrap = TRUE)) |> 
  addRasterImage(x = ras, layerId = 'n', colors = col_pal, opacity = 0.6) |> 
  addLegend(position = "topright", values = d$n, pal = col_pal) |>
  leafem::addImageQuery(ras, type="mousemove", layerId = "n", prefix = '') |> 
  addLayersControl(overlayGroups = "n", position = 'topleft')

```

The `plot(ras)` output is:

![image](https://user-images.githubusercontent.com/1282581/153309524-105b75df-1dae-4ddb-9997-880c14c2e844.png)

Note the heavy green in North America.  This becomes two dark cells in Leaflet's output:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/1282581/153309659-01cf36b1-56a0-4325-9969-25edd922debd.png">

The tooltip pops up on hover for a square that spans half of Leaflet's two dark cells.

-------------------------

Testing the `projectRasterForLeaflet()` methods shows both its methods demonstrate the duplicative behaviour (_bilinear_ more severely as also duplicates left/right - i.e. 4 cells representing just 1 in reality):

    ras |> projectRasterForLeaflet("ngb") |> plot()

<img width="769" alt="image" src="https://user-images.githubusercontent.com/1282581/153310700-89730e9a-fb3f-49af-8607-2e82775a9568.png">

    ras |> projectRasterForLeaflet("ngb") |> plot()

<img width="770" alt="image" src="https://user-images.githubusercontent.com/1282581/153310728-67103818-f390-4df3-ad57-03824e8f2706.png">

**Comment by rhijmans** [comment]
I do not think this is wrong. I suppose your approach could be to use rasterize on a Mercator raster: 

```
merc <- "+proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs +type=crs"

library(terra)
v <- vect(d, geom=c("lon", "lat"), crs="+proj=lonlat")
p <- project(v, merc)

r <- rast(d, type="xyz", crs="+proj=lonlat")
rm <- project(rast(r), merc)
r <- rasterize(p, rm, "n")

ras <- raster(r)
col_pal = colorNumeric("magma", domain = NULL, na.color = 'transparent', reverse = TRUE)

leaflet(ras) |>  
  addProviderTiles("Stamen.TonerLite", group = "Toner",
                   options = providerTileOptions(noWrap = TRUE)) |> 
  addRasterImage(x = ras, layerId = 'n', colors = col_pal, opacity = 0.6, project = FALSE) |> 
  addLegend(position = "topright", values = d$n, pal = col_pal) |>
  leafem::addImageQuery(ras, type="mousemove", layerId = "n", prefix = '') |> 
  addLayersControl(overlayGroups = "n", position = 'topleft')
 ```

**Comment by geotheory** [comment]
OK I get that Robert as far as a workaround is concerned.  But would you agree that any rasterization as a statistical aggregation _should_ sum to the same amount, give or take?  This bug does not have a randomly balancing effect - it will always inflate the aggregate sum, so it is a real problem for geospatial statistics.

**Comment by rhijmans** [comment]
> would you agree that any rasterization as a statistical aggregation should sum to the same amount, give or take? 

I suppose you mean "projection" when you say "rasterization". I would say that would be great, but it is hard to do and there are other considerations. This is a big topic, but here are some thoughts:

Generally these methods work OK when you are interested in estimating a quantity like elevation of land cover type for another raster geometry. And in that case it is preferable to have more estimates (that you can remove) then to have missing values where you expected some. Also, your example has a few scattered cells; that is not typical. 

Transforming counts to density, use bilinear interpolation, and then back-transforming *might* work better.  If you care about the number of cells with values, and counts, then you really should not project the data after rasterization, but rather use the approach I suggested. I do not think it is a work-around, but rather the proper way to do it.  

With leaflet the purpose is display, which is again a different context. In this example, with very few isolated cells with values, you might as well use polygons: 

```
ras = rasterFromXYZ(d, crs = '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs') 
p = as.polygons(rast(ras))  |>  project(p, merc)
plot(pm, "n")
``` 

That does not scale well for other cases, but count data is often like this.
