### ISSUE TITLE
'Plot' function in 'raster' package shows values above 'zlim' max as blank

### ISSUE THREAD

**Issue by shirleyxyliu** [rspatial/raster#251]
Hi just writing to see if anyone could kindly help checking the 'plot' function in 'raster' package. When I specified 'zlim' in 'plot' function, the plot show any value exceeding 'zlim' upper limit (50 in my case) as blank cells. Thanks in advance!

plot(r.emis.4km, zlim=c(0,50))
<img width="280" alt="Screen Shot 2022-02-10 at 6 10 04 PM" src="https://user-images.githubusercontent.com/64938264/153518146-580e336f-2615-4931-9278-48b883d1ba5a.png">

**Comment by rhijmans** [comment]
That is by design. 

Instead of 

```
f <- system.file("ex/elev.tif", package="terra") 
r <- raster(f)
plot(r, zlim=c(0,400))
``` 
You could do 

```
x <- clamp(r, 0, 400)
plot(x)
```
