### ISSUE TITLE
rasterToPoints R3.6.1 and R4.1.1

### ISSUE THREAD

**Issue by nduqueg** [rspatial/raster#252]
I've discovered a downside of the rasterToPoints function of Raster package in R version 4.1.1, it runs really slow🐢 when a raster Stack (several layers) is transform to a dataFrame through the rasterToPoints function. In version 3.6.1 is much faster. Can anyone tell me if it can be change in future versions of Raster? or should I keep changing R versions in Rstudio?
Thank you so much for your help

**Comment by rhijmans** [comment]
It is unlikely that this is associated with the version of R. It *might* be associated with the version of the raster package, but you do not specify these. Can you provide a timed example?
