### ISSUE TITLE
availableRAM check very slow. Possibility for extra option to disable it?

### ISSUE THREAD

**Issue by tazend** [rspatial/raster#253]
Hi,

unfortunately, we observed that the `availableRAM` check (from [here](https://github.com/rspatial/raster/blob/master/src/memory.cpp#L26), the one for Linux with `awk`) is pretty slow in some cases.

## Problem Description

The `raster` package is used pretty often by some of our scientists on our Centos7 based Computing-Cluster
Additionally, we are using the Ressource Scheduler [SLURM](https://github.com/SchedMD/slurm) to grant applications fine-grained access to ressources on the compute-nodes (which have from 40 to 56 CPU-Cores available total)
Often, many thousand `raster`-jobs are queued, and it is very likely that many of them will land on the same compute-node. Meaning, that a lot of unique `raster` processes are able to run side by side on the compute-nodes, sometimes 30+ or even more, since all of them only need 1 CPU-Core.

This also introduces the bottleneck that comes with the before mentioned `availableRAM` check: 30+ Processes wanting to access `/proc/meminfo` through `awk` almost at the same time. And this `availableRAM` check is called very often, basically every 2 seconds, resulting in a massive slowdown. The CPU-Efficiency of those processes is basically 0% due to that.

Additionally, at least for our use case and in combination with SLURM, checking `/proc/meminfo` for `MemAvailable` doesn't actually tell you how much memory is still available for a specific `raster` process. Multiple users can share compute-ressources on a compute node, and declaring Memory requirements for a Job is mandatory beforehand. These Memory requirements are further enforced via `cgroups`. 

If a job declares to use 4GB RAM max, it will only have those 4GB available. Therefore, checking `/proc/meminfo` isn't truthful in that case. Memory allocations exceeding those RAM restrictions would result in malloc failures and the kernel rightfully killing that specific process.

## Solution Proposal

Ideally, what we would like to have is an extra Option in the [canProcessInMemory Function](https://github.com/rspatial/raster/blob/master/R/canProcessInMemory.R#L32) that completely disables these Memory checks if set (simply returning `TRUE` at the beginning if the option is enabled)

The already existing `.toDisk()` option in there wouldn't be optimal, since always writing to disk is much slower.
We already tested, and without that `availableRAM` check the CPU-Efficiency is back to 100%. We'd rather take this performance enhancement with the possible risk that some individual processes having that check disabled may crash due to memory-allocation failures.

What do you think about that? If you want, I can also try and create a Pull-Request with the new option.

**Comment by rhijmans** [comment]
Thank you for your detailed description; and I am sorry that it took me a while to address this. I have added an option `minmeory` (in bytes) below which no check is done. The default is 10^8 (that is 1 million raster cells). It cannot be set to a number below 10^4, but you can set it to Inf if you do not want any checking  `rasterOptions(minmemory=Inf)`. This has also been implemented in the `terra` package (the replacement of `raster`) as `terraOptions(minmem=)`

**Comment by tazend** [comment]
Thanks a lot for adding that option, this will do what we need.
