### ISSUE TITLE
Open Zarr files

### ISSUE THREAD

**Issue by gdkrmr** [rspatial/raster#254]
When looking at
```
R> raster::writeFormats()
...
[57,] "Zarr"      "Zarr"                                   
```
raster says that it can read the Zarr format I always get an error if I try to open a dataset
```
R> raster("~/data/DataCube/v2.1.0/esdc-8d-0.25deg-184x90x90-2.1.0.zarr/")
Error in .local(.Object, ...) : 

Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file.
```

**Comment by mdsumner** [comment]
two things to check, is there a reason for the trailing slash? I'd try without it, also try with a full path - expand out the ~

Is there an easy source of Zarr files we can try?

**Comment by mdsumner** [comment]
well, fwiw I created a file with gdal and this works

```R
raster("~/out.zarr/")

```

so, I think my suggestions above are irrelevant

**Comment by rhijmans** [comment]
Apparently this works.
