### ISSUE TITLE
plotRGB alpha should be interpolated like r, g, b

### ISSUE THREAD

**Issue by andrewclausen** [rspatial/raster#256]
I'm not sure if plotRGB is supposed to support alpha (transparency) being a matrix rather than just a scalar.

In any case, whether it actually works is hit and miss.  sampleRegular() is used rescale/crop r,g,b but not alpha.

Are pull requests welcome for addressing both issues?  That is,

1. fully documenting alpha channel support
2. fixing bugs in this support.

**Comment by rhijmans** [comment]
Sorry for not responding earlier. I think "terra" behaves better in this respect. If not, I would not mind fixing it there, but I do not want to add new features to "raster" anymore.
