### ISSUE TITLE
Unknown argument 'units' does not produce error when used in terrain() function

### ISSUE THREAD

**Issue by CoryG-Aerotract** [rspatial/raster#259]
When using the function terrain() to calculate aspect, using incorrect argument 'units' rather than the correct 'unit' will allow function to run rather than producing an unknown argument error.

See here: https://gis.stackexchange.com/questions/426928/error-calculating-aspect-from-dem-in-r-using-raster-terra/426934?noredirect=1#comment696665_426934

**Comment by rhijmans** [comment]
This happens because it is taken as an additional argument, and then ignored because it does not match anything. This is unfortunate but not something I can easily change anymore. It works better in `terra`, the replacement for `raster`, where you get:

```
library(terra)
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
x <- terrain(r, "slope", units="degrees")
#Error: [write] unknown option(s): units
```

So I am going to leave it as is.
