### ISSUE TITLE
getData not retrieving data: biogeo server down?

### ISSUE THREAD

**Issue by ldemaz** [rspatial/raster#263]
I have been trying to use `getData` for a few days and it is timing out. This was experienced trying to access srtm and worldclim data.

```
dem <- raster::getData(name = "alt", country = "ZMB", path = tempdir())
```
```
trying URL 'https://biogeo.ucdavis.edu/data/diva/msk_alt/ZMB_msk_alt.zip'
Error in utils::download.file(url = aurl, destfile = fn, quiet = FALSE,  : 
  cannot open URL 'https://biogeo.ucdavis.edu/data/diva/msk_alt/ZMB_msk_alt.zip'
In addition: Warning message:
In utils::download.file(url = aurl, destfile = fn, quiet = FALSE,  :
  URL 'https://biogeo.ucdavis.edu/data/diva/msk_alt/ZMB_msk_alt.zip': status was 'Couldn't connect to server' 
```

**Comment by Nowosad** [comment]
See https://github.com/rspatial/raster/issues/262

**Comment by ldemaz** [comment]
Thanks @rhijmans and @Nowosad for the quick responses.

**Comment by rhijmans** [comment]
Finally working again. Took much longer than expected.

**Comment by PanditPranav** [comment]
Is the server down again? I am having the same issues with the getData function. 
Thanks!!

**Comment by ajm102** [comment]
Is the server down again? I am having this issue as well trying to work with the Wallace Ecological Modeling App. Thanks!

**Comment by Nowosad** [comment]
```r
> geodata::gadm("Norway", path = ".")
The geodata server is down for maintenance. 
It is expected to be back online on October 12, 2023.
```

**Comment by zlongshark** [comment]
Hi @rhijmans, 

Are the severs down again?

`> my0 = getData('GADM', country="AUS", level=0)
trying URL 'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_AUS_0_sp.rds'
Error in utils::download.file(url = aurl, destfile = fn, quiet = FALSE,  : 
  cannot open URL 'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_AUS_0_sp.rds'`

Thanks.
