### ISSUE TITLE
is biogeo.ucdavis.edu still down?

### ISSUE THREAD

**Issue by gsadoti** [rspatial/raster#264]
I'm hoping to extract some Worldclim layers. I saw this was resolved a couple days ago, but I'm still getting errors ...

trying URL 'https://biogeo.ucdavis.edu/data/diva/msk_alt/USA_msk_alt.zip'
Error in utils::download.file(url = aurl, destfile = fn, method = "auto",  : 
  cannot open URL 'https://biogeo.ucdavis.edu/data/diva/msk_alt/USA_msk_alt.zip'
In addition: Warning message:
In utils::download.file(url = aurl, destfile = fn, method = "auto",  :
  InternetOpenUrl failed: 'A connection with the server could not be established'

Also, if anyone knows of any alternate repositories, please advise. Many thanks.

**Comment by rhijmans** [comment]
raster::getData is still not working (any time now) but you can use the `geodata` package instead. 
https://github.com/rspatial/geodata

**Comment by rhijmans** [comment]
This now works again.
