### ISSUE TITLE
drawPoly() and drawExtent() bugged

### ISSUE THREAD

**Issue by chfleming** [rspatial/raster#265]
The polygons output by `drawPoly` are above and to the left of where I select. As a simple example:
``
plot(-1:1,-1:1);
raster::drawPoly(sp=FALSE)
``
Clicking four times around the center point results in a polygon at the top left of the plot. `drawExtent` is doing something similar.

I'm using the latest versions of R and RStudio on Windows, in a fresh session. I've never had issues with these functions in the past.

**Comment by rhijmans** [comment]
This was designed for Rgui and it seems to work fine there. The Rstuido graphics do not work exactly the same way. The `draw` method in the `terra` package should work well in Rstudio.

**Comment by gse-cc-git** [comment]
I have the same issue as OP using `terra::draw` with Rstudio 2022.12.0 Build 353. Never had the issue with `raster::drawExtent` in the paste neither.
