### ISSUE TITLE
"ties" parameter not usable in modal() when used in aggregate()

### ISSUE THREAD

**Issue by sostberg** [rspatial/raster#267]
The `modal()` function normally has a `ties` parameter that controls what is done if several values have the same frequency.
However, when using `modal()` as the `fun` in `aggregate()` it seems that no `ties` parameter is passed from `aggregate()` to `modal()`. I have tested `aggregate(sourcedata, fact = 2, fun = modal)`  with several different `ties = "..."`  parameters but ties are always broken in a random fashion.

Is there any way to use `modal()` within `aggregate()` and set `ties` to something different from "random"?

**Comment by rhijmans** [comment]
This kind of "how to?" question is more appropriate (and is likely to be answered faster) for stackoverflow or gis.stackexchange. But here you go:

```
library(raster)
r <- raster(ncol=10, nrow=10)
set.seed(1)
r <- setValues(r, sample(3, ncell(r), replace=TRUE))
a <- aggregate(r, fact=2, fun=function(x, ...) modal(x, ties='first'))
```
