### ISSUE TITLE
writeRaster bug when trying to write out stack layers

### ISSUE THREAD

**Issue by jscamac** [rspatial/raster#271]
Hi,
I think a bug has inadvertently been added to raster::writeRaster when trying to write out individual stack layers in this #221 (https://github.com/rspatial/raster/commit/de8faaffc640ace75255ee44a3ac18a6f17e5d4b):

MWE below:

```
x1 <- raster::raster(nrows = 10, ncols = 10, vals = rnorm(100,1,2))
x2 <- raster::raster(nrows = 10, ncols = 10, vals = rnorm(100,10,2))
s <- raster::stack(x1,x2)
raster::writeRaster(s, filename = c("test1.tif","test2.tif"), bylayer=TRUE)
```

```
Error in if (tolower(e) %in% c(".tiff", ".tif")) { : 
  the condition has length > 1
```

**Comment by rhijmans** [comment]
Thank you. It probably was there for a while, but gave a warning that with R 4.2 (?) has become an error.
