### ISSUE TITLE
issue with new R version and writeRaster for multilayer tif - potential solution 

### ISSUE THREAD

**Issue by sjevelazco** [rspatial/raster#274]
Hi 

I noticed that writeRaster is experiencing an error at moment to save multiple tif layers in the R version 4.2.0. 
As far as I know when this new version function like while() or if() with a condition of length greater than one gives an error [rather than a warning](https://www.r-bloggers.com/2022/04/new-features-in-r-4-2-0/) 

```
tmp <- tempdir()
r <- raster(system.file("external/test.grd", package="raster"))

# take a small part
r <- crop(r, extent(179880, 180800, 329880, 330840) )
r <- brick(r, r*2)
# save as tif
writeRaster(r, filename=file.path(tmp, paste0(names(r), ".tif")), bylayer=TRUE, format='GTiff', overwrite=TRUE)
# writeRaster(r, filename=file.path(tmp,  "asfd.tif"), format='GTiff', overwrite=TRUE)
```

I am sure the error is here 
https://github.com/rspatial/raster/blob/6f90d642efb3573de3df77b67dd7799248151a2a/R/extension.R#L76

Maybe if you add an any() within this if() will fix this problem
```
if (any(tolower(e) %in% c(".tiff", ".tif"))) {
			return (e)
		} 
```

**Comment by rhijmans** [comment]
Thank you. I believe this was already fixed in the development version of `raster`.
