### ISSUE TITLE
Error in CRS after updating from  raster 3.5.2 to 3.5.15 version

### ISSUE THREAD

**Issue by bijoychandraAU** [rspatial/raster#275]
Previously, I used 
`proj4string(P) <- CRS("+init=epsg:28992")` in raster version of 3.5.2. This works fine.
Unfortunately, after updating the 3.5.15 version, the same code no longer works as the error comes with `Error in CRS("+init=epsg:28992") : NA`.
how could I re-install the previous version or any alternative approach?

Thank you

**Comment by rhijmans** [comment]
I cannot reproduce this (on windows with current R, raster and rgdal)

```
library(raster)
r <- raster()
proj4string(r) <- CRS("+init=epsg:28992")
# or like this 
proj4string(r) <- "+init=epsg:28992"
# or like this
crs(r) <- "+init=epsg:28992"

r
#class      : RasterLayer 
#dimensions : 180, 360, 64800  (nrow, ncol, ncell)
#resolution : 1, 1  (x, y)
#extent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#crs        : +proj=sterea +lat_0=52.1561605555556 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +units=m +no_defs 
```
