### ISSUE TITLE
Install packages compilation fail

### ISSUE THREAD

**Issue by Buckmaster7** [rspatial/raster#276]
When I run:   install.packages("raster")  
I get the following error:
                  * installing *source* package 'raster' ...
                  ** package 'raster' successfully unpacked and MD5 sums checked
                  ** using staged installation
                  ** libs
                  g++  -std=gnu++11 -I"D:/program_d/R/R-4.2.0/include" -DNDEBUG  -I'D:/program_d/R/R-4.2.0/library/Rcpp/include'   -I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RasterModule.cpp -o RasterModule.o
                  sh: g++: command not found
                  make: *** [D:/program_d/R/R-4.2.0/etc/x64/Makeconf:259: RasterModule.o] Error 127
                  **ERROR: compilation failed for package 'raster'**
                  * removing 'D:/program_d/R/R-4.2.0/library/raster'
                  Warning in install.packages :
                    installation of package ‘raster’ had non-zero exit status

This error makes it so the "raster" library is not recognized...

**Comment by rhijmans** [comment]
You could do some googling about how to install R packages from source (you need Rtools), but the simplest way to avoid this problem is to install the binary package from CRAN, and to *not* install from source.

**Comment by Buckmaster7** [comment]
Thank you for the advice that worked!

Glenn Buckmaster  MSc., P. For
Senior Planner, Forestry Planning & Commercial Growth
Electricity

C.  780 722 7088
