### ISSUE TITLE
rasterFromXYZ can mess up the order of values

### ISSUE THREAD

**Issue by frousseu** [rspatial/raster#277]
Hello!

This is a very strange bug that appears inconsistently and that seems to be platform-dependent. When building a raster stack or brick with many values using `rasterFromXYZ`, sometimes the ordering of values will be completely wrong. Here is an example that does this on my computer:

```r
library(raster)
mm <- as.matrix(expand.grid(1:3000, 1:3000))
nl <- 20
mm <- cbind(mm, matrix(rep(1:nrow(mm), nl), ncol = nl))
colnames(mm) <- c("X", "Y", paste0(LETTERS[1:nl], 1:nl))
r <- rasterFromXYZ(mm)
plot(r)
```

However, the problem does not appear every time. If I have a low number of values (say `nl = 2`), the resulting layers are ok. If I have a high number of values (e.g. `nl = 20`), layers are all wrong. There is a point in between where results will alternate between being right or wrong. Also, values that produce wrong results seem to vary across platforms. I tested this on both a Windows machine and an Ubuntu server and values that produce wrong results are not the same on both platforms. In general, increasing the total number of values in the raster will lead to the problem. I initially had raster 3.5-15 and the problem persists with 3.5-21.

I looked into the `rasterFromXYZ` function to see if I could find the problem and the closest I could get was the last part of the function, namely this part:

```r
if (d[2] > 2) {
    names(r) <- ln[-c(1:2)]
    r[cells] <- xyz[, 3:d[2]]
}
return(r)
```
The line that seems to be causing the problem is `r[cells] <- xyz[, 3:d[2]]`. When values are ok, the name of layers is retained, but they are dropped when values are wrong. Something weird seem to be going on with this value assignment. From what I understood, the `cells` object is ok in all cases.

Let me know If more details are needed or if I should do further tests. I should be transitioning to terra in a few weeks.

François

**Comment by rhijmans** [comment]
Thank you. I now get:

```
(r <- rasterFromXYZ(mm))
#class      : RasterBrick 
#dimensions : 3000, 3000, 9e+06, 20  (nrow, ncol, ncell, nlayers)
#resolution : 1, 1  (x, y)
#extent     : 0.5, 3000.5, 0.5, 3000.5  (xmin, xmax, ymin, ymax)
#crs        : NA 
#source     : memory
#names      :      A1,      B2,      C3,      D4,      E5,      F6,      G7,      H8,      I9,     J10,     K11,     L12,     M13,     N14,     O15, ... 
#min values :       1,       1,       1,       1,       1,       1,       1,       1,       1,       1,       1,       1,       1,       1,       1, ... 
#max values : 9000000, 9000000, 9000000, 9000000, 9000000, 9000000, 9000000, 9000000, 9000000, 9000000, 9000000, 9000000, 9000000, 9000000, 9000000, ... 
```
Or with "terra"
``` 
library(terra)
(x <- rast(mm, type="xyz"))
#class       : SpatRaster 
#dimensions  : 3000, 3000, 20  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : 0.5, 3000.5, 0.5, 3000.5  (xmin, xmax, ymin, ymax)
#coord. ref. :  
#source      : memory 
#names       :    A1,    B2,    C3,    D4,    E5,    F6, ... 
#min values  :     1,     1,     1,     1,     1,     1, ... 
#max values  : 9e+06, 9e+06, 9e+06, 9e+06, 9e+06, 9e+06, ... 
```

**Comment by frousseu** [comment]
Thanks for the very quick fix and the terra translation. It now works on my machine as well.
