### ISSUE TITLE
Automaticaly resample rasters to create RasterStack

### ISSUE THREAD

**Issue by samuel-rosa** [rspatial/raster#28]
Satellite images are composed of several bands. These bands have the same extent and origin. However, some of them have different spatial resolutions. Thus, it is not possible to read them using `raster::stack()`. Before, one has to `raster::resample()` them so that all bands share the same spatial resolutions. An interesting alternative would be add an argument to `raster::stack()` -- e.g. resample -- so that the bands are resampled on the fly.

**Comment by rhijmans** [comment]
aggregate / disaggregate would be more appropriate than resample. I appreciate your suggestion but I am not going to implement this.
