### ISSUE TITLE
Drop or not import a RasterLayer within a RasterStack that does not have values in all cells in R

### ISSUE THREAD

**Issue by agronomofiorentini** [rspatial/raster#280]
Dear Creators,

I have this situation that i have a RasterStack with 17 RasterLayers, some rasterlayers do not, however, include the entire area of interest, I would like to ask you how I can eliminate RasterLayers that do not have data at every point in the area of interest.

Here are some photos of the problems
<img width="637" alt="Screenshot_1" src="https://user-images.githubusercontent.com/66969646/184350191-6f248896-a4af-4bfe-a164-b3de7771ee93.png">
<img width="635" alt="Screenshot_2" src="https://user-images.githubusercontent.com/66969646/184350198-98acbde7-3fba-48d3-b666-e3bb5c7d4158.png">

Could you help to avoid those RasterLayers and get a complete RasterStack?

Thanks

The follow link will led you to a google drive with all the data.

https://drive.google.com/drive/folders/19m7rJHdVgfQ4Nc8CrMSBtoRSYAUjrk3M?usp=sharing

**Comment by rhijmans** [comment]
github is for bugs and feature requests. To ask questions, stackoverflow is a better place, and I see that you have posted [this question ](https://stackoverflow.com/questions/73333843/drop-or-not-import-a-rasterlayer-within-a-rasterstack-that-does-not-have-values) there.
