### ISSUE TITLE
Error in x$.self$finalize() : attempt to apply non-function

### ISSUE THREAD

**Issue by caemillan** [rspatial/raster#282]
I am tried to read a shapefile:
`raster::shapefile("myshape.shp")`

And show  an error `Error in x$.self$finalize() : attempt to apply non-function`.

I tried to reinstall the package; uninstall R and RStudio and all packages, but doesn´t resolve the problem.
![Captura](https://user-images.githubusercontent.com/34458589/186279416-d2a04f7f-c0d6-4ec9-a480-7c9d93fb1477.PNG)

Any suggestion?

**Comment by rhijmans** [comment]
These are annoying messages that I understand to be emitted by the R garbage collection process. They are not errors in the sense that your code runs and your results are not affected.  So you can ignore them.

**Comment by rhijmans** [comment]
It looks like this problem has now been [solved](https://github.com/rspatial/terra/issues/30) by making a change in Rcpp, but it will take a couple of months until that is released

**Comment by rhijmans** [comment]
But if you can install "terra" from source, the problem will go away if you use the development version of Rcpp 

```
install.packages("Rcpp", repos="https://rcppcore.github.io/drat")
install.packages("terra")
```

**Comment by rhijmans** [comment]
These messages no longer appear if you use the current CRAN version of Rcpp.
