### ISSUE TITLE
How to use getData with CMIP6

### ISSUE THREAD

**Issue by maurobio** [rspatial/raster#286]
Dear ALL,

For modelling present and future distributions of biological species, I can easily use the function getData as follows:

futureEnv <- getData(name = "CMIP5", 	 # forecast data
                         var = "bio",    # bioclim
                         res = 2.5,      # 2.5 minute resolution
                         path = "data/", # destination directory
                         model = "GD",   # GFDL-ESM2G
                         rcp = "45",     # CO2 increase 4.5
                         year = 70)      # 2070

This works fine, but the forecast data downloaded above retrieves the CMIP5 data, which are now obsolete. Then, I manually downloaded the latest CMIP6 data from the WorldClim website for the GFDL model and put them in a 'cmip6' folder in my computer. However, when I attempted to do:
 
futureEnv <- getData('CMIP6', var='bio', res=2.5, rcp=45, model='GD', year=70)

I got an error message:

Error in getData("CMIP6", var = "bio", res = 2.5, rcp = 85, model = "GD",  : 
  CMIP6 not recognized as a valid name.

So, I would like to ask: is there any way in the raster package to handle the latest CMIP6 data?

Thanks in advance for any assistance you can provide!

**Comment by Nowosad** [comment]
Have you tried the {geodata} package -- https://github.com/rspatial/geodata?

**Comment by maurobio** [comment]
Hi,

Didn't know this package, it looks great and more up-to-date than raster.
Thanks a lot for pointing it out.

With best wishes,

--
Dr. Mauro J. Cavalcanti
E-mail: ***@***.***
Web: http://sites.google.com/site/maurobio

Em dom, 11 de set de 2022 13:04, Jakub Nowosad ***@***.***>
escreveu:
