### ISSUE TITLE
Cover does not provide desired output as of version 3.5-29

### ISSUE THREAD

**Issue by kcohar** [rspatial/raster#290]
As of version 3.5-29, the raster package function "cover" doesn't seem capable of producing the kind of object it's supposed to. In fact, it returns a null object.

Running the following code:
```
library(raster)
f <- system.file("external/lux.shp", package="raster")
p <- shapefile(f)
z <- raster(p, nrow=2, ncol=2, vals=1:4)
z <- as(z,'SpatialPolygonsDataFrame')
cover(p,z)
```
using raster 3.5-29 or 3.6.3 does nothing and leaves a null object behind:

```
str(cover(p,z))
#NULL
```

If you use raster 3.5-21 however, it does provide the correct output:

```
#Loading required package: sp
#Loading required namespace: rgeos
#class       : SpatialPolygonsDataFrame
#features    : 6
#extent      : 5.74414, 6.528252, 49.44781, 50.18162  (xmin, xmax, ymin, ymax)
#crs         : +proj=longlat +datum=WGS84 +no_defs
#variables   : 6
#names       : ID_1,       NAME_1, ID_2,     NAME_2, AREA, layer
#min values  :    1,     Diekirch,    1,   Clervaux,  188,     1
#max values  :    2, Grevenmacher,    6, Echternach,  312,     4
```

There doesn't seem to be any difference between the working and malfunctioning versions of cover when I run cover (raster::cover) or showMethods(cover) (showMethods(raster::cover)).

**Comment by rhijmans** [comment]
Thank you very much. Fixed now (and the attributes are better than before, I think). 
That bug happened because I replaced "rgeos" methods with methods from the "terra" package.

**Comment by kcohar** [comment]
Thank you! That was super fast haha
