### ISSUE TITLE
.tif.aux.xml no longer generated in raster version 3.6-3

### ISSUE THREAD

**Issue by mariekecf** [rspatial/raster#291]
In raster version 3.5-15 when I saved a raster with label values (i.e. county names) it would generate a .tif.aux.xml file. After updating to raster version 3.6-3 the .tif.aux.xml is no longer generated. Below is a generic example of the code I'm running. I can reproduce this on a Linux server and a Windows laptop. Thanks!

```
newraster <- rasterize(sf_item, raster_item)
writeRaster(newraster, "newraster.tif") 
# no .tif.aux.xml file is generated
```

**Comment by rhijmans** [comment]
What is the functionality that you are looking for? That is, what is lost for you when that file is not there? Also, can you provide a reproducible example, otherwise it may be difficult to help.

**Comment by rhijmans** [comment]
When you can, please let me know what the missing functionality is so that I may be able to address that.
