### ISSUE TITLE
raster::focalWeight( ... , d = "circle") results in wrong Matrix (Kernel)

### ISSUE THREAD

**Issue by Quartaer** [rspatial/raster#297]
Goal: I wanted to create a circular, equally weighted matrix (as a kernel) for about 1 ha!

Whether I entered the diameter or the radius for the parameter 'd', a new raster was output with dimensions that were inexplicable or wrong to me. I manually developed the value of diameter-23 that was suitable in my case. I also cannot explain why the 23 comes about.

I use the raster package 3.6-3 and R 4.2.2 under windows.

```
## Create Kernel Matrix: Focal approx. equal weighted 1 ha Circle, 
W <-                                                     # Weight-matrix for Kernel of equal weights
  raster::focalWeight(                            # Create Kernel
    raster::raster( 
      ncols= 113,                                    # Properly dim for ~1 ha circle
      nrow= 113,
      xmn= 0,
      CRS = "+proj=utm +zone=34 +south +a=6378249.145 +rf=293.4663077 +units=m +no_defs"),      # CRS as Proj.4 WKT
    ## !!! ###
    d = 113,        # !!! Works NOT properly in the case of diameter 113 and radius 56 ## Works properly with 113-23 !!! ??? -> dim  113x113
    type = "circle",                            
    fillNA = F)                                  
```

**Comment by Quartaer** [comment]
The same proplem with terra::focalMat( , d= "circle)

I think that the algorithm for "circle" somehow uses a fraction (0.55) of the radius, maybe something similar to sigma (about 0.68). That would explain the (strange) reduced dimensioning of the matrix from, say, 100*100 input grid (x) at radius 50 (d) to 55 * 55 in the output matrix (w). As a user, I would assume that the parameter x= specifies the grid on which the weights are projected with the resolution of x. That is, output (w) should again be 100 * 100 if I choose radius (d=) 50 with an input of 100 * 100 (x). But instead, I get a matrix (w) of 55 * 55!?

I need this matrix as a moving window for another analysis. In my 1 ha case, I need a grid with a 1-meter resolution of 2 * (r=) 56.4m ... pi*r² = 1 ha --> 113 * 113 cells matrix and not 71 * 71.

Or I don't understand the idea behind the function!
I hope my English is not rude! Thanks!

**Comment by rhijmans** [comment]
See https://github.com/rspatial/terra/issues/894
