### ISSUE TITLE
Raster (.tif) cell values not correctly interpreted in R?

### ISSUE THREAD

**Issue by jorisbertrand** [rspatial/raster#301]
Hi,
I have download rasters (.tif) from CHELSA (e.g. https://os.zhdk.cloud.switch.ch/envicloud/chelsa/chelsa_V2/GLOBAL/climatologies/1981-2010/bio/CHELSA_ai_1981-2010_V.2.1.tif)
I can open these files successfully as a RasterStack object (i.e. with raster::stack(c(layer1, layer2, ...)).
However when I try to plot the first layer of this multilayer raster with something like: plot(myraster$layer1), it seems that the cell values range from 2200 to about 3000 whereas this layer is supposed to contain mean annual temperatures.
When I try to open the exact same file in QGIS, band values range from -53.55 to 34.75 which looks more consistent.
It seems that the function raster::stack (as I used it) does not interpret cell values as it should. You will find below a summary of this layer:
> summary(predictors$bio1)
        bio1
Min.    2196
1st Qu. 2672
Median  2833
3rd Qu. 2963
Max.    3073
NA's       0
Warning message:
In .local(object, ...) :
  summary is an estimate based on a sample of 1e+05 cells (0.01% of all cells)
Do you have any idea of what happens?
All the best,
Joris

**Comment by rhijmans** [comment]
I do not see anything going wrong here.

The values do look off (very high in cold areas). Perhaps something went wrong in the processing.   

This is what I see:

```
library(terra)
f <- "CHELSA_ai_1981-2010_V.2.1.tif"
x <- rast(f)
plot(x)

x
#class       : SpatRaster 
#dimensions  : 20880, 43200, 1  (nrow, ncol, nlyr)
#resolution  : 0.008333333, 0.008333333  (x, y)
#extent      : -180.0001, 179.9999, -90.00014, 83.99986  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : CHELSA_ai_1981-2010_V.2.1.tif 
#name        : CHELSA_ai_1981-2010_V.2.1 
#min value   :              2.660725e-04 
#max value   :              6.553500e+08 
```

These numbers are read from the metadata stored in the file

```
describe(f)[46:54]
#[1] "Band 1 Block=43200x1 Type=Float32, ColorInterp=Gray"                         
#[2] "  Min=0.000 Max=655350016.000 "                                              
#[3] "  Minimum=0.000, Maximum=655350016.000, Mean=2462773.433, StdDev=6772288.142"
#[4] "  NoData Value=-99999"                                                       
#[5] "  Metadata:"                                                                 
#[6] "    STATISTICS_MAXIMUM=655350016"                                            
#[7] "    STATISTICS_MEAN=2462773.4329186"                                         
#[8] "    STATISTICS_MINIMUM=0.0002660725149326"                                   
#[9] "    STATISTICS_STDDEV=6772288.1423685"                                       
```

**Comment by jorisbertrand** [comment]
Hi, thanks for the answer, 
the thing that I don't get is that the values differ if I open my raster with raster::stack() or with terra::raster() (see picture below).
Actually it seems that that the terra version legend values look more consistent with temperatures but I am supposed to use an object of an object of type Raster Stack or Raster Layer instead of SpatRaster for my subsequent analyses.
Do you see how I could make the Raster Stack/Layer z values looking similar to the SpatRaster version?
Cheers,
[terra vs raster.pdf](https://github.com/rspatial/raster/files/10466505/terra.vs.raster.pdf)

**Comment by rhijmans** [comment]
With the development version of "raster" I now see the same values:

```
raster(f)
#class      : RasterLayer 
#dimensions : 20880, 43200, 902016000  (nrow, ncol, ncell)
#resolution : 0.008333333, 0.008333333  (x, y)
#extent     : -180.0001, 179.9999, -90.00014, 83.99986  (xmin, xmax, ymin, ymax)
#crs        : +proj=longlat +datum=WGS84 +no_defs 
#source     : CHELSA_ai_1981-2010_V.2.1.tif 
#names      : CHELSA_ai_1981.2010_V.2.1 
#values     : 0.0002660725, 655350016  (min, max)

rast(f)
#class       : SpatRaster 
#dimensions  : 20880, 43200, 1  (nrow, ncol, nlyr)
#resolution  : 0.008333333, 0.008333333  (x, y)
#extent      : -180.0001, 179.9999, -90.00014, 83.99986  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : CHELSA_ai_1981-2010_V.2.1.tif 
#name        : CHELSA_ai_1981-2010_V.2.1 
#min value   :              2.660725e-04 
#max value   :              6.553500e+08 
```

**Comment by jorisbertrand** [comment]
Thanks a lot! I just tested it and it works perfectly. 
Cheers,
