### ISSUE TITLE
Progress bar not working

### ISSUE THREAD

**Issue by stschl** [rspatial/raster#305]
`pbStep` seems not to be working at the moment, text progress bars stay at 0 percent.

I believe this is due to a small bug in [`pbStep`](https://github.com/rspatial/raster/blob/master/R/progressBar.R):

```
pbclass <- class(pb)
	if (inherits(pbclass, "txtProgressBar")) {
		if (is.null(step)) { step = pb$getVal() + 1 }
		utils::setTxtProgressBar(pb, step)
	}
```

`pbclass` inherits from `character`, so second line should be 

```
if (inherits(pb, "txtProgressBar")) {
```

**Comment by rhijmans** [comment]
Thanks for spotting that. I think that is due to a hasty replacement of cases of `class(x) == "someclass"` to `inherits(x, "someclass")`
