### ISSUE TITLE
Coordinates no longer appear on the map

### ISSUE THREAD

**Issue by armandosunny** [rspatial/raster#306]
Hello, 
with the update the coordinates no longer appear on the map, when you put the command: plot(map)
I wish they could fix it. thank you so much,
Greetings, 
Armando Sunny

**Comment by rhijmans** [comment]
Are saying that coordinate labels are not shown on the axes?  I do not think that is generally the case. See the examples in `?plot` such as 

```
library(terra)
f <- system.file("ex/elev.tif", package="terra") 
r <- rast(f)
plot(r)
```
But if you do not see coordinates on the axes with your data, I would need more information to understand why that might be. Can you provide a reproducible example, or at least `show(map)`?

**Comment by rhijmans** [comment]
Sorry, that was an example for "terra". I also see coordinates with "raster"

```
library(raster)
f <- system.file("external/test.grd", package="raster")
f
r <- raster(f)
```

although I would recommend using terra for plotting (and everything else)
