### ISSUE TITLE
RasterLayer has no values

### ISSUE THREAD

**Issue by millie-robson** [rspatial/raster#309]
Hello,

I am trying to run the following land of code to plot a land cover map:

```
# Woodland cover map of UK
landsc <- terra::rast("nfi_england_2020_raster.txt")
plot(landsc)

# Plot woodland cover map
landsc.f <- as.factor(raster(landsc))
#Error in .local(x, incomparables = incomparables, ...) : 
#  RasterLayer has no values
```
I am confused as I cannot find an issue with my raster layer - I have attached the txt. file for my raster and I was wondering if anyone could help with this issue?

Many thanks!
[nfi_england_2020_raster.txt](https://github.com/rspatial/raster/files/11179441/nfi_england_2020_raster.txt)

**Comment by rhijmans** [comment]
This works for me. Are you using the current versions of raster and terra?

This "how-to" question is more appropriate for stackoverflow.com. If you ask it there, please explain what you are trying to accomplish. and Include the packages you use `library(terra)` etc. Why are you mixing up raster and terra? You could also do 

```
landsc.f <- as.factor(landsc)
```
