### ISSUE TITLE
Incorrect large values saved to disk with writeRaster()

### ISSUE THREAD

**Issue by SarahGoslee-USDA** [rspatial/raster#311]
The values written to disk are not the same as those in the raster when the values are large but within dataType range.

In the below simple example, if n = 0 or a smallish value, the results match as expected.

```
    library(raster)

    n <- 20000000 # if n is less, works as expected

    sequence.r <- raster(nrows = 100, ncols = 100, 
                     vals = seq_len(100 * 100) + n)

    # write to disk
    writeRaster(sequence.r, filename = "sequence.r.grd", dataType = "INT4S", overwrite = TRUE)

    # read back in the same file
    sequence.read <- raster("sequence.r.grd")

    # compare values
    summary(sequence.r - sequence.read)
    length(unique(values(sequence.r)))
    length(unique(values(sequence.read)))
```

Giving incorrect cell values:

```
> summary(sequence.r - sequence.read)
        layer
Min.    -1.00
1st Qu. -0.25
Median   0.00
3rd Qu.  0.25
Max.     1.00
NA's     0.00

  > length(unique(values(sequence.r)))
[1] 10000

  > length(unique(values(sequence.read)))
[1] 5001
```

Things that I tried that did not matter:

  - updating raster to raster_3.6-21
  -  testing on Mac with R 4.3.0 or linux with R 4.1.3
  - different projections (LCC, NAD83, unprojected as in this example)
  - using INT4S or FLT4S, although both have adequate ranges and should set out of range values to NA
  - using GRD or TIF formats; I did not try others.

Using terra instead of raster does provide the expected result.

```

# repeat in terra

library(terra)

n <- 20000000 # if n is less, works as expected


tsequence.r <- rast(nrows = 100, ncols = 100, 
                     xmin = -1560750, xmax = -1460750, ymin = 1384500, ymax = 1484500,
                     crs = "+proj=lcc +lat_0=42.5 +lon_0=-100 +lat_1=25 +lat_2=60 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs",
                     resolution = 1000,
                     vals = seq_len(100 * 100) + n)


terra::writeRaster(tsequence.r, filename = "tsequence.r.grd", datatype = "INT4S", overwrite = TRUE)

tsequence.read <- rast("tsequence.r.grd")

all(values(tsequence.r) == values(tsequence.read)) # TRUE

```

**Comment by rhijmans** [comment]
Thanks for reporting this. The underlying reason is that the integers get represented as real numbers internally. Apparently, in raster they become 32-bit doubles (loss of precision at integer numbers > (2^24 + 1; ~17 million), while in terra they get converted to 64-bit doubles (loss of precision at integers > (2^53 + 1)).  I assume that raster has always had this so I am not going to fix this.
