### ISSUE TITLE
isLonLat fails on epsg code

### ISSUE THREAD

**Issue by mdsumner** [rspatial/raster#32]
This should be `TRUE`: 

```R
 raster::isLonLat("+init=epsg:4326")
```

It can be worked around with `rgdal`, but probably best to simply match on "init=4326" as this is a very common case. 

```R
raster::isLonLat(rgdal::CRSargs(sp::CRS("+init=epsg:4326")))
```

**Comment by rhijmans** [comment]
Implemented as suggested. Thank you,
