### ISSUE TITLE
Looking for non-existing metadata

### ISSUE THREAD

**Issue by emilio-berti** [rspatial/raster#321]
Hi,

I am running some analyses on a server and I cannot thus fully reproduce the issue on my laptop. I have a job that loads several files as a stack, e.g:

```
ff <- list.files(datadir)
s <- stack(ff)
```

The files are simple `.tif` files, with to ancillary metadata files (i.e., no `.aux`, etc.). Inspecting the job (sysadmin did this for me, I am not sure how to replicate it), however, reveals that raster is looking for those ancillary metadata files:

```
open("03_2003_V.2.1.aux", O_RDONLY) = -1 ENOENT (No such file or directory)
open("03_2003_V.2.1.AUX", O_RDONLY) = -1 ENOENT (No such file or directory)
open("03_2003_V.2.1.tif.aux", O_RDONLY) = -1 ENOENT (No such file or directory)
open("03_2003_V.2.1.tif.AUX", O_RDONLY) = -1 ENOENT (No such file or directory)
```

Is there a way to force raster to not look for the ancillary files?

**Comment by rhijmans** [comment]
This does not provide enough information for me to act upon.

**Comment by mdsumner** [comment]
it's a GDAL config, and doesn't raster use terra for that? so probably see if terra can set this 🙏

GDAL_DISABLE_READDIR_ON_OPEN

**Comment by rhijmans** [comment]
That would be 

```
setGDALconfig("GDAL_DISABLE_READDIR_ON_OPEN", "YES")
#or 
setGDALconfig("GDAL_DISABLE_READDIR_ON_OPEN", "TRUE")
```

but it seems that to avoid all side-car file probing you need 

```
setGDALconfig("GDAL_DISABLE_READDIR_ON_OPEN", "EMPTY_DIR")
```
