### ISSUE TITLE
Rstudio abort when running "resample"

### ISSUE THREAD

**Issue by monviso** [rspatial/raster#322]
Hi, Working with Windows 10, Rstudio 2023.09.01, R 4.3.2, terra 1.7.55 all functions that I usually work with work as usual but when running `resample` R studio aborts the session. 

It's hard to give further details. Let me know if any further test is needed

**Comment by rhijmans** [comment]
If this is for "terra" then it should be reported there. But there is nothing much I can do without more details about the raster used.
