### ISSUE TITLE
Why can't I download cmip6_tile?

### ISSUE THREAD

**Issue by skmaharjan** [rspatial/raster#324]
I am using following script to download cmip6_world.
bio30s_2021_2040 <- cmip6_world(model = "ACCESS-CM2", ssp = "585", time = "2021-2040", var = "bioc", res = 0.5, path = "./WorldClim2.1/2021-2040")

This works fine but when I try to download cmip6_tile using following script it gives me following error.
bio30s_2021_2040 <- cmip6_tile(lon = 81.55802, lat = 28.99313, model = "ACCESS-CM2", ssp = "585", time = "2021-2040", var = "bioc", res = 0.5, path = "./WorldClim2.1/2021-2040")

Error: The geodata server is down for maintenance. 
It is expected to be back online on October 12, 2023.
download failed 

What I don't understand is if these two functions are using different sources to download the data. If that is not the case, then why am I getting this error?

**Comment by Rapsodia86** [comment]
This is not the correct place for that issue:
See rspatial/geodata: https://github.com/rspatial/geodata
That issue already exists: https://github.com/rspatial/geodata/issues/53

**Comment by skmaharjan** [comment]
@Rapsodia86, I am new to github and thank you very much for connecting to the correct thread.
