### ISSUE TITLE
future of the raster package

### ISSUE THREAD

**Issue by benj919** [rspatial/raster#325]
Hi all

Of course just after posting an issue on the r-spatial/evolution project I realize that the raster package is on github as well ( https://github.com/r-spatial/evolution/issues/23 ). So here I go again:  What is the future for the raster package in general, and on cran? It's superseded by terra, but does that imply it will soon be retired and archived like rgeos and friends, or will it remain with basic maintenance?

Thanks in advance and cheers

**Comment by rhijmans** [comment]
The plan is for raster to be in "basic maintenance mode" for the time being.
