### ISSUE TITLE
Example failure when running R CMD check (TopologyException)

### ISSUE THREAD

**Issue by kyleam** [rspatial/raster#326]
On an Ubuntu 20.04-based system, the check for raster is failing due to an exception in one of the examples:

```
> #SpatialPolygons
> p <- shapefile(system.file("external/lux.shp", package="raster"))
> b <- as(extent(6, 6.4, 49.75, 50), 'SpatialPolygons')
> crs(b) <- crs(p)
> b <- SpatialPolygonsDataFrame(b, data.frame(ID_1=9))
>
> cv1 <- cover(p, b)
Error: TopologyException: Input geom 1 is invalid: Self-intersection at or near point 5.78807545 49.877223970000003 at 5.78807545 49.877223970000003
Execution halted
```

I verified that I can trigger the same error with a Docker image based on `rstudio/r-base:4.3.1-focal`.

<details>
<summary>Dockerfile</summary>

```
FROM rstudio/r-base:4.3.1-focal
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends eatmydata && \
    eatmydata apt-get install -y --no-install-recommends locales && \
    echo 'en_US.UTF-8 UTF-8' >>/etc/locale.gen && locale-gen && \
    eatmydata apt-get install -y --no-install-recommends \
      git \
      libgdal-dev \
      libgeos-dev \
      libglpk-dev \
      libproj-dev \
      libudunits2-dev \
      sqlite3 \
      && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
ARG COMMIT=a2065ae0d522107d1a4639ea543ec13d12c6b6b2
RUN git clone https://github.com/rspatial/raster.git && \
    git -C raster checkout "$COMMIT"
ARG CRAN=https://packagemanager.posit.co/cran/__linux__/focal/2023-12-14
RUN printf 'options(repos = c("CRAN"= "%s"))\n' "$CRAN" >/opt/R/4.3.1/lib/R/etc/Rprofile.site
RUN Rscript -e 'install.packages(c("remotes", "rcmdcheck"))' && \
    Rscript -e 'remotes::install_deps("raster", dependencies = TRUE, upgrade = "always")' && \
    rm -rf /tmp/R*
CMD ["Rscript", "-e", "rcmdcheck::rcmdcheck('raster')"]
```

</details>

System library versions:

```
# apt-cache policy libproj-dev libgdal-dev libgeos-dev
libproj-dev:
  Installed: 6.3.1-1
  Candidate: 6.3.1-1
  Version table:
 *** 6.3.1-1 100
        100 /var/lib/dpkg/status
libgdal-dev:
  Installed: 3.0.4+dfsg-1build3
  Candidate: 3.0.4+dfsg-1build3
  Version table:
 *** 3.0.4+dfsg-1build3 100
        100 /var/lib/dpkg/status
libgeos-dev:
  Installed: 3.8.0-1build1
  Candidate: 3.8.0-1build1
  Version table:
 *** 3.8.0-1build1 100
        100 /var/lib/dpkg/status
```

Any ideas what could be triggering the failure?

Thanks in advance.

**Comment by kadyb** [comment]
Try updating GEOS to newer version (e.g. from [ubuntugis-unstable PPA](https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable)). Since version 3.9 a new OverlayNG engine for geometric operations is used.

**Comment by kyleam** [comment]
Thanks @kadyb.

> Try updating GEOS to newer version (e.g. from [ubuntugis-unstable PPA](https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable)).

Yes, the example failure is resolved if I get libgeos from ubuntugis (3.9.1).

<details>
<summary>Dockerfile change</summary>

```diff
diff --git a/Dockerfile b/Dockerfile
index 00a4fad..c22e1aa 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -6,13 +6,19 @@ RUN apt-get update && \
     echo 'en_US.UTF-8 UTF-8' >>/etc/locale.gen && locale-gen && \
     eatmydata apt-get install -y --no-install-recommends \
       git \
+      gpg \
+      dirmngr \
       libgdal-dev \
-      libgeos-dev \
       libglpk-dev \
       libproj-dev \
       libudunits2-dev \
       sqlite3 \
       && \
+    echo 'deb https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu focal main' >>/etc/apt/sources.list && \
+    echo 'deb-src https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu focal main' >>/etc/apt/sources.list && \
+    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B827C12C2D425E227EDCA75089EBE08314DF160 && \
+    apt-get update && \
+    eatmydata apt-get install -y --no-install-recommends libgeos-dev && \
     apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ARG COMMIT=a2065ae0d522107d1a4639ea543ec13d12c6b6b2
 RUN git clone https://github.com/rspatial/raster.git && \
```

</details>

> Since version 3.9 a new OverlayNG engine for geometric operations is used.

Okay, so it sounds like the example failure is expected then.  raster's DESCRIPTION doesn't list anything in `SystemRequirements`.  However, it depends on `terra`, and that specifies `GEOS (>= 3.4.0)`.  Based on that, is it accurate to say that raster in general supports `GEOS (>= 3.4.0)`, although for some subset of features that require the new OverlayNG engine, an error is expected (and hopefully obvious to users familiar with the area)?

I'm trying to get a sense for whether this failing example indicates general functional problems with raster on Ubuntu 20.04 or it's a relatively specific failure with a clear reason.  (This is in the context of a CRAN-like repository that is targeting Ubuntu 20.04 ([MPN](https://mpn.metworx.com/).)

Thanks again.

**Comment by rhijmans** [comment]
> is it accurate to say that raster in general supports GEOS (>= 3.4.0)

Yes

> for some subset of features that require the new OverlayNG engine, an error is expected (and hopefully obvious to users familiar with the area)?

Not expected, really. The new GEOS algorithms should be more robust; but it really is a coincidence that this example fails.

**Comment by kyleam** [comment]
@rhijmans I see, thanks
