### ISSUE TITLE
SRTM: case-sensitive filenames

### ISSUE THREAD

**Issue by tatianic** [rspatial/raster#34]
Hello!

I have a set of .tif files and try to call ```getData('SRTM', ...)```. Since filenames in Linux are case-sensitive, I get a 'file not found' error.

A problem is here:
https://github.com/rspatial/raster/blob/9fa97f991e15d6a15700d42126ba7bfe4b251045/R/getData.R#L406

And after that ```file.exists(tiffilename)``` does not try to find files with lowercase extension .tif, but only uppercase .TIF

Changing extensions of all my files to .TIF solves the problem for me, bit is not an elegant solution.

Thank you!
~tatianic

**Comment by rhijmans** [comment]
Fixed. Works on win and lin now. Thank you.
