### ISSUE TITLE
Unexpected results with rasterize on polygons: possible bug?

### ISSUE THREAD

**Issue by Farewe** [rspatial/raster#36]
Hello,

I was trying to rasterize polygons of IUCN distribution data for species, in order to calculate species richness. 
I tried two different procedures that should give the same result, one as suggested in rasterize help (using `fun = function(x, ...) length(unique(na.omit(x))`), and another method consisting in rasterizing all species polygons in 1/0 and then summing the results. However, the two procedures yielded differences in some places. From my understanding, `fun = function(x, ...) length(unique(na.omit(x))` fails to perform as expected.

 I cannot figure out why; I posted a question on GIS/stackexchange with little success. Could you look into this?

Here is the GIS/stackexchange question with code and reproducible example:

https://gis.stackexchange.com/questions/307770/inconsistencies-in-r-rasterize-polygons-packages-raster-and-sf

**Comment by rhijmans** [comment]
Thank you very much for reporting this. I have looked at this in detail, and in this case, method 2 produced the correct answer, whereas method 1 did not. This was related to polygons with holes and the order in which they were rasterized. I have fixed this in version 2.8-14
