### ISSUE TITLE
Raster values differ after writing/reading from disk

### ISSUE THREAD

**Issue by jspijker** [rspatial/raster#38]
Dear dev

Values in my raster files differ after writing to and reading from disk. See following code:

```r
library(raster)
n <- 15000 # raster size
r1 <- raster(nrows=n,ncols=n) # create raster
values(r1) <- 1:ncell(r1) # fill with unique values
writeRaster(r1,"test.grd",overwrite=TRUE) # write raster to disk
r2 <- raster("test.grd") # read the same raster
print(summary(r1-r2)) # subtract, expect only 0 values
```
I expect that in last print statement all the values will be 0. This is the case for small number of n (raster rows/cols, e.g. 5000) but for larger values of n, like 15000, the summary shows values between -8 to 8. Plotting the result of the subtracted grids also give weird patterns

![capture](https://user-images.githubusercontent.com/25150737/51521247-5a0e7c00-1e26-11e9-9b9a-1a363043d963.PNG)

I expect that r1 and r2 are equal to each other but it doesn't look like that they are equal. So what's happening?

R version info:
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.6 (Maipo)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] raster_2.8-4       sp_1.3-1           localoptions_1.0.0

loaded via a namespace (and not attached):
[1] compiler_3.5.1   rgdal_1.3-6      tools_3.5.1      Rcpp_1.0.0      
[5] codetools_0.2-15 grid_3.5.1       lattice_0.20-35
```

**Comment by lbusett** [comment]
I may be mistaken, but I'd guess you have a problem of integer representation in float (`writeRaster` saves to Float32 by default, I think).
(see https://stackoverflow.com/questions/3793838/which-is-the-first-integer-that-an-ieee-754-float-is-incapable-of-representing-e)
Forcing to save as INT4S seems to avoid the problem, infact: 

```
library(raster)
n <- 5000 # raster size
r1 <- raster(nrows=n,ncols=n) # create raster
r1 <- init(r1) # fill with unique values
writeRaster(r1,"test.grd",overwrite=TRUE, datatype = "INT4S") # write raster to disk
r2 <- raster("test.grd") # read the same raster
pippo <- r1-r2
summary(pippo)
        layer
Min.        0
1st Qu.     0
Median      0
3rd Qu.     0
Max.        0
NA's        0
```

**Comment by jspijker** [comment]
Indeed, adding the datatype="INT4S" to writeRaster solves my problem. Thanx!
However, it is behaviour I didn't expect. So I leave it to the developer to consider this as a bug or not.

**Comment by rhijmans** [comment]
I suppose that if one where to do 
    
`values(r1) <- as.integer(1:ncell(r1))
`
The subsequent writeRaster could automatically switch to writing INT4S values.

**Comment by rhijmans** [comment]
I will not change this behavior.
