### ISSUE TITLE
Error: cannot allocate vector of size 31.6 Gb

### ISSUE THREAD

**Issue by felaminh** [rspatial/raster#39]
Hello,

I did use the function crop and mean for 434 rasters. Each one is very big, it corresponds almost like 1/4 of Brazil

now I want to calculate de standard deviation between these 434 rasters images but this error appears. 
I have 66gb of space but it seems that my computer will not process .

sd_ndvi_caat_crop<-calc(ndvi_caat_crop, sd, na.rm=TRUE, aszero=FALSE)

What should I do?

Or if a use the function cellStats does it calculate in the same way? like calculating the sd of each cell of each 434 rasters images?

**Comment by rhijmans** [comment]
What version of "raster" are you using? 

`packageVersion("raster")`

**Comment by felaminh** [comment]
‘2.8.4

**Comment by rhijmans** [comment]
In that case, I need some more info.
What does

canProcessInMemory( ndvi_caat_crop, verbose=TRUE)

show?

And what does

traceback()

show, after the error occurs?


Thanks, Robert

**Comment by rhijmans** [comment]
I need to do some testing, probably over the weekend. For now, I would suggest lowering the chunksize option. Something like this:

`rasterOptions(chunksize=1e+06)`

**Comment by felaminh** [comment]
Thank you.

My R session was ended, so I lost the temporary files that build the object **ndvi_caat_crop**
So I need to spend 2 days running this again before testing **rasterOptions(chunksize=1e+06)**

**Comment by rhijmans** [comment]
Can you write `ndvi_caat_crop` to a geotiff file instead of to a (temporary) native "raster" format file? If that makes the problem go away it would narrow down where to look.
