### ISSUE TITLE
area function producing different results between versions

### ISSUE THREAD

**Issue by sharonbm1** [rspatial/raster#44]
I seem to be getting different results that vary by a factor of 100 from area calculations in raster packages. Back in late 2017, I run the code below with R version 3.3.2 (2016-10-31), rgdal package version 1.2-5, and raster package version 2.6-7 and received for the variable kba_total_impact_km2_optimal a value of 70.52. I’ve recently rerun the analyses with the same code but R version 3.4.3 (2017-11-30), rgdal package version 1.3-6, and raster package version 2.8-19 and received for the variable kba_total_impact_km2_optimal a value of 0.7052. Input of optimal and temp.kba are in m units (and are also attached), hence I converted area to km2 by dividing by 1000000. I’m a bit confused and apologize if I’m missing something obvious, but I’ve never had such differences occur with different versions of R. Based on the data, the value of 70.52 km2 makes sense so I’m assuming something is not processing correctly with the latest raster package version?

I greatly appreciate any help on this and again apologies in advance if I’m missing something super simple and obvious. Input data and code are attached.
Sincerely,

Sharon Baruch-Mordo
Spatial Scientist
The Nature Conservancy

[area_calc_r_versions.zip.zip](https://github.com/rspatial/raster/files/2938572/area_calc_r_versions.zip.zip)
 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~```
# Begin code:
 
optimal <- raster(file.choose())
temp.kba <- readOGR(file.choose())
 
# calc area of kba in country
temp.kba$area_sqkm <- area(temp.kba)/1000000
                                
# find area that intersect with optimal scenario = 1 cells 
list.areas.kba.optimal <- extract(optimal, temp.kba, na.rm=FALSE, weight=TRUE, normalizeWeights=FALSE)
                
sum.if <- function(x){if(length(x[,1][!is.na(x[,1])]) > 0) (sum(x[which(x[,1]==1),2])) else NA} 
                
# how much area is impacted for each kba (sum only for those with 1, i.e., those intersecting a raster value of 1)
temp.kba$area_impacted_optimal <- unlist(lapply(list.areas.kba.optimal, FUN=sum.if)) # in sqkm as it is proportion of 1 km cell!
temp.kba$prop_optimal <- temp.kba$area_impacted_optimal/temp.kba$area_sqkm
 
kba_total_impact_km2_optimal <- sum(temp.kba$area_impacted_optimal,na.rm=T)

**Comment by rhijmans** [comment]
This happens is because of a change in the values of the "weights".  I think of them as relative measures, so I did not think it would matter. I will probably restore them back to what they were to avoid this type of problem. or perhaps not. I think where you expected a 1 you now get a value of 0.01. 

I understand that you want a precise estimate of the the sum of raster cells that are 1, for the area covered by the polygons. 

```
# given
library(raster)
optimal <- raster("optimal.tif")
temp.kba <- shapefile("temp_kba.shp.shp")

# The simple way to do that would be:
x <- extract(optimal, temp.kba, fun=sum, na.rm=TRUE)
sum(x)
# 74

# A more precise estimate
r <- disaggregate(optimal, 10)
x <- extract(r, temp.kba, fun=sum, na.rm=TRUE)
sum(x) / 10^2
# 70.52

# Or following your approach (with simplified function)
kba.optimal <- extract(optimal, temp.kba, na.rm=FALSE, weights=TRUE, normalizeWeights=FALSE)
z <- sapply(kba.optimal, function(x) sum(x[!is.na(x[,1]), 2]))
# or
# z <- sapply(kba.optimal, function(x) sum(na.omit(x)[,2]))
sum(z) * 100
# [1] 70.52

# but perhaps simpler
r <- reclassify(optimal, cbind(NA, 0))
kba.opt <- extract(r, temp.kba, weights=TRUE, fun=mean)
a <- area( temp.kba) / 1000000
sum(kba.opt * a)
[1] 70.52537

```
