### ISSUE TITLE
getData SRTM not working ""

### ISSUE THREAD

**Issue by guillaumelobet** [rspatial/raster#46]
I am trying to get elevation data from longitude/latitude informations using the getData function with RSTM. 

I tried the example function: 
 `getData('SRTM', lon=5, lat=45)`

an it returns 

`trying URL 'ftp://xftp.jrc.it/pub/srtmV4/tiff/srtm_38_04.zip'
trying URL 'http://hypersphere.telascience.org/elevation/cgiar_srtm_v4/tiff/zip/srtm_38_04.ZIP'
trying URL 'http://srtm.csi.cgiar.org/SRT-ZIP/SRTM_V41/SRTM_Data_GeoTiff/srtm_38_04.ZIP'
Error in utils::download.file(url = aurl, destfile = fn, method = "auto",  : 
  cannot open URL 'http://srtm.csi.cgiar.org/SRT-ZIP/SRTM_V41/SRTM_Data_GeoTiff/srtm_38_04.ZIP'
In addition: Warning messages:
1: In utils::download.file(url = aurl, destfile = fn, method = "auto",  :
  unable to resolve 'hypersphere.telascience.org'
2: In utils::download.file(url = aurl, destfile = fn, method = "auto",  :
  cannot open URL 'http://srtm.csi.cgiar.org/SRT-ZIP/SRTM_V41/SRTM_Data_GeoTiff/srtm_38_04.ZIP': HTTP status was '404 Not Found'`

I also tried 

`getData('GADM', country='AUT', level=0)`

and I get:

`trying URL 'http://biogeo.ucdavis.edu/data/gadm2.8/rds/AUT_adm0.rds'
Error in utils::download.file(url = aurl, destfile = fn, method = "auto",  : 
  cannot open URL 'http://biogeo.ucdavis.edu/data/gadm2.8/rds/AUT_adm0.rds'`

any ideas why? Or any workaround possible to get elevation data from longitude/latitude ?

**Comment by jsta** [comment]
You might consider the `elevatr` package: https://github.com/jhollist/elevatr

**Comment by jsta** [comment]
You might try the `rgbif` package: https://ropensci.github.io/rgbif/reference/elevation.html

**Comment by rhijmans** [comment]
Works for me. The server may have been down.

**Comment by guillaumelobet** [comment]
I tried the rgbif package, but it seems that the GeoNames webservice it is using is only available in the US. Could it be the same issue for this function as well (out of the US issue?)
