### ISSUE TITLE
Why raster layer name change to default when using raster::calc function?

### ISSUE THREAD

**Issue by CamiloEr** [rspatial/raster#50]
Why raster layer name change to default when using raster::calc function, but not when using Arith-methods (that does not  imply a predefined function like sum or sqrt):

Toy example copied from Reference manual (calc function):
```
library(raster)
r <- raster(ncols=36, nrows=18)
r[] <- 1:ncell(r)
names(r) <- "Band1"
r 

rc1 <- calc(r, function(x) { x * 10 })
names(rc1) # Default name "layer"

#But when:
rc2 <- r*10
names(rc2) #It conserves the name "Band1"
names(sqrt(r)) # It doesn't.
```

This issue begun as a StackExchange Geographic Information System question: https://gis.stackexchange.com/questions/317591/why-raster-layer-name-change-to-default-when-using-rastercalc-function/317597#317597

**Comment by Nowosad** [comment]
I think your question is related to https://github.com/rspatial/raster/issues/42#issuecomment-470063437.

**Comment by CamiloEr** [comment]
Thank you very much. Now I am clear about the reason for this behavior.
