### ISSUE TITLE
Import selected columns of raster

### ISSUE THREAD

**Issue by dominicroye** [rspatial/raster#51]
I was wondering if it would be possible to include additionally to ncol (Number of columns) an argument start_col? In the same sense as it is possible for ncdf (start, count argument). I saw that getValuesBlock has this posibility, but therefore the raster object already has to be present. 

I don't know if I missed something.

**Comment by mdsumner** [comment]
If I understand correctly, you can get this by using the `extent(r, r1, r2, c1, c2)` usage as per `help(extent)`: 

>When x is a Raster* object, you can pass four additional arguments to crop the extent: r1, r2, c1, c2, 
> representing the first and last row and column num


(Using a file from a package I happen to have)
```R
f <- "../stars/inst/nc/reduced.nc"
(r <- raster::raster(f))
Loading required namespace: ncdf4
class       : RasterLayer 
dimensions  : 90, 180, 16200  (nrow, ncol, ncell)
resolution  : 2, 2  (x, y)
extent      : -1, 359, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0 
data source : /perm_storage/home/mdsumner/Git/stars/inst/nc/reduced.nc 
names       : Daily.sea.surface.temperature 
z-value     : 1981-12-31 
zvar        : sst 
level       : 1 
```

That doesn't read any data, see how it's still on disk?  Say we want to ignore all columns before the 50th: 

```R
raster::crop(r, raster::extent(r, 1, 90, 50, 180))
class       : RasterLayer 
dimensions  : 90, 131, 11790  (nrow, ncol, ncell)
resolution  : 2, 2  (x, y)
extent      : 97, 359, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0 
data source : in memory
names       : Daily.sea.surface.temperature 
values      : -1.8, 32.97  (min, max)
time        : 1981-12-31 
```

There I have all rows (1:90), and only the (50:180) columns.   Does that help?

**Comment by rhijmans** [comment]
Conceptually, I would be possible to use an extent to set a "window", representing an area of interest that is a spatial subset of a raster file. I am not going to implement that in "raster". So you would need to do what Mike suggests.
