### ISSUE TITLE
incorrect input documentation for RGB

### ISSUE THREAD

**Issue by dschneiderch** [rspatial/raster#52]
The help file says `RGB` requires a rasterstack or rasterbrick but actually it needs a rasterlayer and results in a rasterbrick. 

https://github.com/rspatial/raster/blob/27d552a5dd262177da9f1d195b1b9ea2ab3f156b/man/RGB.Rd#L21

**Comment by rhijmans** [comment]
Thanks, fixed now.

**Comment by dschneiderch** [comment]
Thanks for all your effort!
