### ISSUE TITLE
No slot of name "data" when writing raster to NCDF

### ISSUE THREAD

**Issue by PhilippBuehler** [rspatial/raster#53]
There is a bug when writing a RasterStack to NetCDF files. Normal RasterLayers work well.

> Error in apply(v, 2, range, na.rm = TRUE) : 
>   no slot of name "data" for this object of class "RasterStack"

Minimal reproducible example:
```
library(raster)
library(ncdf4)
r <- raster(crs="+proj=utm +zone=32 +datum=WGS84", xmn=0, xmx=10, ymn=0, ymx=10)
values(r) <- 1:ncell(r)
s <- stack(r, r/2)

xwriteRaster(s, filename="test.nc",overwrite=TRUE) 
```

**Comment by rhijmans** [comment]
Thanks for reporting. I think this is [fixed now].(https://github.com/rspatial/raster/commit/a3faada014095638254cf7c3ea308614b8f18aa6)

**Comment by PhilippBuehler** [comment]
The Github version with your implementation fixed it for me. 
Thank you for the fast response!
