### ISSUE TITLE
Support conversion to data.table?

### ISSUE THREAD

**Issue by thiagoveloso** [rspatial/raster#55]
Data.tables are usually considerably faster to process than data frames. I was looking for ways to convert raster objects to data.tables preserving as much information as I could, and I just stumbled upon this function written by Etienne Racine: https://gist.github.com/etiennebr/9515738.

Then I was wondering: any chance this function could be included in the raster package as a native one?

**Comment by rhijmans** [comment]
I am not going to add this to raster.  It seems to me that for most cases this suffices:

```
v <- as.data.table(as.data.frame(x))
setnames(v, names(x))

```
