### ISSUE TITLE
focal error with large dimensions

### ISSUE THREAD

**Issue by Synkronicity** [rspatial/raster#56]
Hi,

The focal function seems to produce the following error whenever the dimension size is set to anything higher than 200:

```
Error in .local(x, row, nrows, ...) : validRow(x, row) is not TRUE
Calls: focal ... .local -> getValues -> getValues -> .local -> stopifnot
Execution halted
```

Here's the Rscript that reproduces this error:

```
library(raster)
r1975300<-raster("GHSPOPGPW41975GLOBER2015A540091kv10.tif")

dim=300
msize=2*dim+1
window<-matrix(1,nrow=msize, ncol=msize)
rsum1975300 <- focal(r1975300,w=window)
```

At dim=25 to dim=200, everything works just fine. When set to 300 we got the above error.

Just to make sure it wasn't due to a lack of memory or storage the script was run on an HPC node with 3 TB of RAM and failed the same as a node with 256 GB of RAM, with all Rtemp files being written to ample scratch storage.

R is version 3.5.2, the raster package is version 2.8.19, the sp package is version 1.3.1. 

Thank you for your time!

@bindatype

**Comment by rhijmans** [comment]
I am not to fix this. You can try this with `terra` instead of `raster`.
