### ISSUE TITLE
raster::predict() fails on nnet::multinom model

### ISSUE THREAD

**Issue by danfosterfire** [rspatial/raster#57]
I am using the raster::predict() function to predict a raster using a multinomial model from nnet::multinom(). My code works (and throws the warning 'not sure if factor levels are correct') when using raster v2.8-19, and fails with error "factors[[j]] list index out of range" on raster v2.9-5. 
I'm calling predict with factors = NULL and my model is produced by nnet::multinom. I believe the issue is the removal of the warning handling in commit 190c237cee3519b0a57dab9ba6712cf0628db737, specifically lines 124-136(old) and 139-142(new).

I am hoping that is sufficient information to ID the problem, but if not I am happy to provide files for reproduction. I'm working with large files so it will take me some time to box up a reproducible version.

**Comment by rhijmans** [comment]
Hi Danny, 
Thanks for reporting,  Here is an example (taken from raster::predict that gives a similar error message

```
library(raster)
logo <- brick(system.file("external/rlogo.grd", package="raster"))
p <- matrix(c(48, 48, 48, 53, 50, 46, 54, 70, 84, 85, 74, 84, 95, 85, 66, 42, 26, 4, 19, 17, 7, 14, 26, 29, 39, 45, 51, 56, 46, 38, 31,  22, 34, 60, 70, 73, 63, 46, 43, 28), ncol=2)
a <- matrix(c(22, 33, 64, 85, 92, 94, 59, 27, 30, 64, 60, 33, 31, 9,  99, 67, 15, 5, 4, 30, 8, 37, 42, 27, 19, 69, 60, 73, 3, 5, 21,  37, 52, 70, 74, 9, 13, 4, 17, 47), ncol=2)
xy <- rbind(cbind(1, p), cbind(0, a))
v <- data.frame(cbind(pa=xy[,1], extract(logo, xy[,2:3])))

library(nnet)
model <-  nnet::multinom(formula=pa~., data=v)

r <- predict(logo, model)

v$red <- as.factor(round(v$red/10))
model2 <-  nnet::multinom(formula=pa~., data=v)
r2 <- predict(logo, model2)
#Error in factors[[j]] : subscript out of bounds
```

**Comment by rhijmans** [comment]
And in the CRAN version, you can fix this by doing

```r2 <- predict(logo, model2, factors=list(red=levels(v$red)))```

But the current github version now detects the factors and this works

```r2 <- predict(logo, model2)```

I have simplified and hopefully improved the factor detection. The warning in the previous CRAN version probably should not have been ignored. In stead of warnings, there are errors now forcing the user to set factors manually in case of ambiguity.

**Comment by danfosterfire** [comment]
Thanks for the update and quick response! I tried setting the 'factors' variable as you suggest, but I was structuring the list incorrectly. I'm in the middle of a long processing step now, but when it completes I will install the github version. I'm going to mark this as closed, and will re-open if there are any issues. Thanks again for your time!
