### ISSUE TITLE
raster::brick() small defects when plotting a GeoTiff image

### ISSUE THREAD

**Issue by mgageo** [rspatial/raster#59]
Hi

I read a file and after I plot it :
```
library(httr)
library(raster)
dsn <- 'https://framagit.org/mgageo/plotrgb/raw/master/PLOTRGB/pontorson_echangeur_satellite.tif'
fic <- tempfile('plotrgb', fileext='.tif')
download.file(dsn, fic,  mode = "wb")
img <- brick(fic)
plotRGB(img)
```
Some small parts of the plot are white.

With an other package, there's no defects 
```
im2 <- tiff::readTIFF(fic)
grid::grid.raster(im2)
```
I get the file from a WMTS server with gdal_utils.

![image](https://user-images.githubusercontent.com/2681495/60047204-66468000-96c9-11e9-8c88-67ae4029769c.png)

**Comment by rhijmans** [comment]
This is because of `NA`s in the first layer. See  ```plot(img,1)```
So the plot is correct, I think. You could work around this by replacing the NAs with some arbitrary value. For example

```
img2 <- reclassify(img, cbind(NA, 50))
plotRGB(img2)
```

**Comment by mgageo** [comment]
Thank you for the answer.
why isn't it treated like readTIFF ?
![image](https://user-images.githubusercontent.com/2681495/60070625-a6345400-9717-11e9-950b-dc805f5965a9.png)

**Comment by rhijmans** [comment]
I think this is because there is a "no data" flag, which probably is geotiff extension that readTIFF does not now about. 

```
inf = rgdal::GDALinfo(fic)
attr(inf, "df")
#  GDType hasNoDataValue NoDataValue blockSize1 blockSize2 Bmin Bmax Bmean Bsd
#1   Byte           TRUE           0          8       1024    0  255    NA  NA
#2   Byte           TRUE           0          8       1024    0  255    NA  NA
#3   Byte           TRUE           0          8       1024    0  255    NA  NA
#4   Byte           TRUE           0          8       1024    0  255    NA  NA
``` 
This means that values of 0 (black) become `NA`. Not much we can do about that, but at least we now know a correct work-around:

```
img2 <- reclassify(img, cbind(NA, 0))
plotRGB(img2) 
```

**Comment by mgageo** [comment]
Thank your for the work-around
