### ISSUE TITLE
getData not working for GADM

### ISSUE THREAD

**Issue by HughSt** [rspatial/raster#6]
Hi, it seems like the getData function when used to obtain GADM data isn't working. From my macbook I get the following

> raster::getData("GADM", country="COL", level=1)
trying URL 'http://biogeo.ucdavis.edu/data/gadm2.8/rds/COL_adm1.rds'
Error in readRDS(filename) : unknown input format

**Comment by rhijmans** [comment]
This was caused by the website serving the data being down for maintenance.

**Comment by CamillaStrauch** [comment]
Do you know why the website isn't responding?
