### ISSUE TITLE
raster from sf points fails

### ISSUE THREAD

**Issue by dominicroye** [rspatial/raster#61]
When I try to get a raster object from points in sp or sf class I get always an empty raster with NAs. I have the last version of the raster and sf package, also RStudio and R are up to date. 
```
library(tidyverse)
library(raster)
library(sf)
library(rnaturalearth)


limit <- ne_countries(country="germany", returnclass = "sf")

grd <- st_make_grid(limit, 
                    cellsize = 0.5, 
                    what = "centers") %>% 
         st_sf() %>% 
  
       mutate(dummy=rnorm(nrow(.)))

grd

r <- raster(grd)
r
values(r)  #NA values
```

**Comment by mdsumner** [comment]
This is intended (and desirable), raster() on an object just looks at extent and crs to build a grid. There's nothing in the sf point data to indicate that it is a regular grid, you could use 'rasterFromXYZ' for that

**Comment by dominicroye** [comment]
Ok. I understand, but why it works with gstat::krige? Actually my problem is with Krige when I use sf. The result is an empty raster. 


```

library(sp)
library(gstat)
library(raster)
data(meuse)
coordinates(meuse) = ~x+y
data(meuse.grid)
gridded(meuse.grid) = ~x+y
m <- vgm(.59, "Sph", 874, .04)
# ordinary kriging:
x <- krige(log(zinc)~1, meuse, meuse.grid, model = m)
x
class(x)
raster(x)


```

**Comment by rhijmans** [comment]
what you produce with krige is a `SpatialPixelsDataFrame`. That is equivalent with a Raster* object so it can be coerced to one. With points this is another matter --- perhaps you want to use `rasterize`, perhaps not...  Anyway, this is not a bug report but more a discussion for stackoverflow or some such forum....
