### ISSUE TITLE
`extract()` fails for sf objects with a Z dimension

### ISSUE THREAD

**Issue by Nowosad** [rspatial/raster#64]
An example of the error can be found below. I think the `st_zm()` (https://rdrr.io/cran/sf/man/st_zm.html) function can be used internally to remove the Z dimension in the `extract()` code.

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(raster)
#> Loading required package: sp

r = raster(ncol = 36,
            nrow = 18,
            vals = 1:(18 * 36))

sf = st_sf(st_sfc(st_point(c(5, 8))))
sf_with_z = st_sf(st_sfc(st_point(c(5, 8, 11))))

# works
extract(r, sf)
#> [1] 307

# fails
extract(r, sf_with_z)
#> Error in .xyValues(x, coordinates(y), ..., df = df): xy should have 2 columns only.
#> Found these dimensions: 1, 3
```

<sup>Created on 2019-08-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rhijmans** [comment]
Thanks for pointing this out. `sp::coordinates` never returned 3 columns before. Fixed.
