### ISSUE TITLE
The area function is not working

### ISSUE THREAD

**Issue by Gilbert2015** [rspatial/raster#65]
The area function produces the error Error in area(p): argument "b" is missing, with no default. I used the example in the documentation to check if the error is with raster data but still got the same result

**Comment by rhijmans** [comment]
I think you are mistaken, My guess is that `raster::area` is hidden by a function named `area` from another package. If so, there should have been a message when you loaded that package, and you can work around it by using the namespace, as in `raster::area(x)` instead of `area(x)`

**Comment by mdsumner** [comment]
Yes it's `MASS::area` I hit this recently
