### ISSUE TITLE
change in shift() arguments (object, x, y) -> (x, dx, dy)

### ISSUE THREAD

**Issue by mdsumner** [rspatial/raster#66]
This took me by surprise: 

```R
library(raster)
r <- raster(volcano)
shift(r, x = -70)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘shift’ for signature ‘"numeric"’
```

I'm writing this just to record the situation in case others encounter it (and to issue a *tiny protest and wish* that there had been a more gentle deprecation period). 

The change was made in version 2.9-22 (on CRAN 2019-07-10) [in this commit](https://github.com/rspatial/raster/commit/17a47c7584ba512338c9b912ca91d7a3cafa527b).

This will mysteriously break any code using explicit named arguments to `shift( , x = , y = )` in this version and later. 

A fix for  current and future raster is to name the arguments the new way: 

```R
shift(r, dx = -70)

shift(r, dy = 1)

shift(r, dx = -70, dy = 1)
```

but that will break for code running in older versions. 

I'd recommend changing existing code to positional arguments if it needs to run in new and old versions.  

```R
shift(r, -70)
shift(r, -70, 1)
shift(r, , 1)

```

I had a look if it would be possible to introduce a `.Deprecated()` step, but I'm not sure it's possible - and now it's on CRAN we'll just have to fix code as it comes up - which admittedly will probably be rare).

**Comment by rhijmans** [comment]
mea culpa

**Comment by ffilipponi** [comment]
May I suggest to include this change in the ChangeLog file?
I was trying to identify the cause of this error and I could not find any information about the argument name changes.
