### ISSUE TITLE
cellStats does not seem to work for raster objects

### ISSUE THREAD

**Issue by eesaupe** [rspatial/raster#67]
The cellStats function seems to only return a single numerical value, even for raster objects.

**Comment by rhijmans** [comment]
What did you expect?

**Comment by eesaupe** [comment]
Apologies - perhaps I misunderstood the function, but I swore that previously it returned a raster layer if working with raster objects, particularly a raster stack or brick object.

**Comment by rhijmans** [comment]
cellStats returns global statistics. For local (cell-wise) stats you can do `mean(x)` or `calc(x, mean)`

**Comment by eesaupe** [comment]
Thank you – I appreciate the response, and I apologize for the error.
