### ISSUE TITLE
raster::predict producing only NA with caret random forest - no error message

### ISSUE THREAD

**Issue by yPennylane** [rspatial/raster#68]
I am trying to use predict with a raster stack of 41 rasters. 2 of them have factor values and the rest are numeric.

All the rasters have been masked by polygons having holes. The model is a caret random forest model. The predicted target is numeric. When I run the following code

    test <- predict(object = s, model = model, factors = fa, progress = "text", 
                na.rm = TRUE, inf.rm = TRUE, index = 1)

I get a raster consisting of NAs without any error message. How can I find out, why predict is producing only NAs? My rasters constist of values which were also used to build the model.

    > test
    class      : RasterLayer 
    crs        : +proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
    source     : memory
    names      : layer 
    values     : NA, NA  (min, max)

Unfortunately I couldn't make a reproducible example yet.

**Comment by rhijmans** [comment]
Which version of `raster` are you using? See `packageVersion("raster")`
And did you look at the cforest example in `?raster::predict` (and does that help)?

**Comment by yPennylane** [comment]
I am using the version 2.9.23. I also looked at the cforest example. I had put the factors in a list and I think it has nothing to do with the OOB instead of newdata, because there is a working example at stackoverflow (See my answer https://stackoverflow.com/questions/25121725/error-in-predicting-raster-with-randomforest-caret-and-factor-variables/57255529#57255529 which makes the code working). I am working on a reproducible code that shows the problem.

**Comment by yPennylane** [comment]
I could reproduce the problem. To run the code, the variable `path` needs to be specified:

    path <- "your//path"

    library(caret)
    library(raster)
    library(sp)
    
    # create polygon
    Sr1 = Polygon(cbind(c(45,45.7,46,45.3,45),c(54,54.1,54.7,54.6,54)))
    Sr2 = Polygon(cbind(c(45.25,45.3,45.45,45.7,45.7),c(54.2,54.4,54.6,54.5,54.2)))
    Sr3 = Polygon(cbind(c(44.1,44.8,44.9,44.2, 44.1), c(54.1,54.2,54.5,54.6, 54.1)))
    Sr4 = Polygon(cbind(c(44.3,45.5,45.7,45,44.1,44.3), c(54.6,55,55.7,55.8,55.5,54.6)))
    SpP = SpatialPolygons(list(Polygons(list(Sr1), "s1"), Polygons(list(Sr2), "s2"),
                               Polygons(list(Sr3), "s3"), Polygons(list(Sr4), "s4")), 
                          1:4)
    dat = data.frame(ID = c("s1", "s2", "s3", "s4"), value = c("a", "b", "a", "d"))
    row.names(dat) <- c("s1", "s2", "s3", "s4")
    p <- SpatialPolygonsDataFrame(SpP, data = dat, 
                                  match.ID = TRUE
                                  )
    proj4string(p) = "+proj=utm +zone=33 +ellps=GRS80 +units=m"
    
    AddHoleToPolygon <-function(poly,hole){
      # invert the coordinates for Polygons to flag it as a hole
      coordsHole <-  hole@polygons[[1]]@Polygons[[1]]@coords
      newHole <- Polygon(coordsHole,hole=TRUE)
      
      # punch the hole in the main poly
      listPol <- poly@polygons[[1]]@Polygons
      listPol[[length(listPol)+1]] <- newHole
      punch <- Polygons(listPol,poly@polygons[[1]]@ID)
      
      # make the polygon a SpatialPolygonsDataFrame as the entry
      new <- SpatialPolygons(list(punch),proj4string=poly@proj4string)
      new <- SpatialPolygonsDataFrame(new,data=as(poly,"data.frame"))
      
      return(new)
    }
    
    punchedPoly <-AddHoleToPolygon(p[1,],p[2,])
    
    p1 <- rbind(p, punchedPoly, makeUniqueIDs = TRUE)
    
    # create rasters
    r1 <- raster(ncol=10, nrow=10, ext=extent(c(44,46,54,56)), crs = "+proj=utm +zone=33 +ellps=GRS80 +units=m")
    values(r1) <- 1:length(r1)
    
    set.seed(42)
    r2 <- raster(ncol=10, nrow=10, ext=extent(c(44,46,54,56)), crs = "+proj=utm +zone=33 +ellps=GRS80 +units=m")
    values(r2) <- sample(0:10, length(r2), replace = TRUE)
    
    set.seed(42)
    r3 <- raster(ncol=10, nrow=10, ext=extent(c(44,46,54,56)), crs = "+proj=utm +zone=33 +ellps=GRS80 +units=m")
    values(r3) <- as.factor(sample(letters[1:4], length(r3), replace = TRUE))
    
    # put rasters in list
    r_list <- list(r1 = r1, r2 = r2, r3 = r3)
    
    # mask rasters
    for (i in 1:3) {
      m <- mask(r_list[[i]], p1)
      assign(paste("r", i, sep=""), m)
    }
    
    # rasterize polygon p1
    # get names 
    nam <- unique(p1$value)
    # create a data.frame
    nam_df <- data.frame(ID = 1:length(nam), nam = nam)
    # Place IDs
    p1$ID <- nam_df$ID[match(p1$value, nam_df$nam)]
    # rasterize polygon
    ras <- rasterize(x = p1, y = r1, field = "ID")
    # ratify raster
    r <- ratify(ras)
    # Create levels
    rat <- levels(r)[[1]]
    rat$names <- nam_df$nam
    rat$IDs <- nam_df$ID
    levels(r) <- rat
    r4 <- r
    writeRaster(x = r4, filename = paste0(path, "\\r4.tif"))
    r4 <- raster(path, "r4.tif")
    
    # create raster stack
    s <- stack(r1,r2,r3,r4)
    # change names
    names(s) <- c("r1", "r2", "r3", "r4")
    # create data frame for model building
    set.seed(42)
    mat <- extract(s, sample(1:100, 40))
    df <- as.data.frame(mat)
    df <- df[!is.na(df$r1),]
    # assign factors again to factor variables
    r3_fac <- c("a", "b", "c", "d")
    for (i in 1:length(r3_fac)) {
      df$r3[df$r3 == i] <- paste0(r3_fac[i])
    }
    df$r3 <- as.factor(df$r3)
    
    r4_fac <- c("a", "b", "d")
    for (i in 1:length(r4_fac)) {
      df$r4[df$r4 == i] <- paste0(r4_fac[i])
    }
    df$r4 <- as.factor(df$r4)
    
    
    # built model
    response <- df$r2
    preds <- df[,which(names(df) %in% c("r1", "r3", "r4"))]
    set.seed(42, kind = "Mersenne-Twister", normal.kind = "Inversion")
    tunegrid <- expand.grid(mtry=c(1:ncol(preds)))
    control <- caret::trainControl(search="grid", method="repeatedcv", number=3, repeats=3)
    model <- caret::train(x = preds,
                          y = response, 
                          method = "rf",
                          ntree = 50,
                          tuneGrid = tunegrid,
                          trControl = control,
                          importance = TRUE)
    
    
    # save factor levels for every single raster in a list
    dat <- as.data.frame(s$r3@data@attributes)
    r3 <- dat$VALUE
    dat <- as.data.frame(s$r4@data@attributes)
    r4 <- dat$category
    fa <- list(r3 = r3, r4 = r4)
    
    # predict
    test <- predict(object = s, model = model, factors = fa, progress = "text", 
                    na.rm = TRUE, inf.rm = TRUE)
    
The raster `test` consists of NAs only and the code did not produce any error message. If I do the prediction without the rasterized object `r4`, the resulting raster still only contains NAs. Maybe there is a problem because of the NAs within the rasters? How could this be fixed without using a raster not containing NAs (not masking the rasters before predict)?

**Comment by rhijmans** [comment]
Thank you for the example. It was a bit long and complicated so I simplified it. The problem was indeed because the factor had character labels. Fixed in version 3.0-3.

I get 

```
test
#class      : RasterLayer 
#dimensions : 10, 10, 100  (nrow, ncol, ncell)
#resolution : 0.2, 0.2  (x, y)
#extent     : 44, 46, 54, 56  (xmin, xmax, ymin, ymax)
#crs        : +proj=utm +zone=33 +ellps=GRS80 +units=m 
#source     : memory
#names      : layer 
#values     : 2.549265, 6.623524  (min, max)

# compare with predict with data.frame
x <- data.frame(na.omit(values(s)))
x$r3 <- as.factor(facs[x$r3])
x$r4 <- as.factor(facs[x$r4])
p <- predict(model, x)
all.equal(p, na.omit(values(test)), check.attributes = FALSE)
#[1] TRUE
```

**Comment by yPennylane** [comment]
Sorry for the long and complicated example. Once I had figured out what is the problem, I didn't have time to optimize the example. The 3.0.3 version is not in the repository yet. When will you release the new version?

**Comment by yPennylane** [comment]
ok, thank you for fixing the problem.

**Comment by yPennylane** [comment]
Unfortunately it is impossible for me to use the updated version of raster (3.0-7) because I can't install it. I get the follwing error message, when trying to install it from a local source:

    install.packages("path\\raster_3.0-7.tar.gz", repos = NULL, type="source")

The following error message occurs:

        Installing package into ‘path/R/win-library/3.6’
    (as ‘lib’ is unspecified)
    * installing *source* package 'raster' ...
    ** package 'raster' successfully unpacked and MD5 sums checked
    ** using staged installation
    ** libs
    
    *** arch - i386
    Warning in system(cmd) : 'make' not found
    ERROR: compilation failed for package 'raster'
    * removing 'path/R/win-library/3.6/raster'
    Warning in install.packages :
      installation of package ‘path/raster_3.0-7.tar.gz’ had non-zero exit status

I tried to install Rtools to fix the problem. Since I don't have admin rights and the exe installer of Rtools is blocked, I cannot install the current version of raster.
