### ISSUE TITLE
Permission denied for Worldclim in getData() 

### ISSUE THREAD

**Issue by joheisig** [rspatial/raster#72]
Seems like Worldclim data is not available anymore, regardless of the version you want to download. I tried
`wclim <- raster::getData('worldclim', var='bio', res=10)`
trying URL 'https://biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/bio_10m_bil.zip'
Error in utils::download.file(url = aurl, destfile = fn, method = "auto",  : 
  cannot open URL 'https://biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/bio_10m_bil.zip'
In addition: Warning message:
In utils::download.file(url = aurl, destfile = fn, method = "auto",  :
  cannot open URL 'https://biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/bio_10m_bil.zip': HTTP status was '403 Forbidden'

If trying to download manually at http://worldclim.org/version2 , it says:
Forbidden
You don't have permission to access this resource.

This function is a huge help to many R-spatial users, especially to beginners. I would be very grateful if it could get it back up and running. Thank you!

R version 3.6.0
raster version 3.0-7

**Comment by ethanwhite** [comment]
This issue appears to be assocaited with all data at https://biogeo.ucdavis.edu. E.g., it is also occurring for elevation data, `elevation = getData("alt", country = "US")` and the associated url https://data.biogeo.ucdavis.edu/data/diva/msk_alt/USA_msk_alt.zip.

**Comment by mksmhdb** [comment]
Having the same issue right now

`getData('alt',country='FRA',mask=TRUE)` 
`getData('GADM',country='FRA',level=1)`
result in:
`trying URL 'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_FRA_1_sp.rds'
Error in utils::download.file(url = aurl, destfile = fn, method = "auto",  : 
  cannot open URL 'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_FRA_1_sp.rds'
In addition: Warning message:
In utils::download.file(url = aurl, destfile = fn, method = "auto",  :
  cannot open URL 'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_FRA_1_sp.rds': HTTP status was '403 Forbidden'`

SRTM data semes to be working though `getData('SRTM',lon=5,lat=45)` (those 3 examples I picked from the doc https://cran.r-project.org/web/packages/raster/raster.pdf)

raster version 3.0-7
Rstudio Version 1.2.5001
R version 3.6.1

**Comment by mksmhdb** [comment]
Seems like the server is back up

**Comment by joheisig** [comment]
Thanks for the update!
