### ISSUE TITLE
predict() results in empty rasters after version update 2.8-19 -> 3.0-7

### ISSUE THREAD

**Issue by vvirkki** [rspatial/raster#73]
Hello,

it seems like the predict function has undergone something weird related to factors in latest version updates. I'm having a somewhat similar issue with issue #68. In short, I'm using random forest to predict probabilities of binary classification with mixed categorical (factor) and numerical variables.

I was using raster package version 2.8-19 before but after updating to current CRAN version 3.0-7, my model broke down. After some investigation, I managed to create a reproduction example which is below. Using 2.8-19, the result is a raster of probabilities but using 3.0-7, the result is solely NA.

I checked that all newdata values for fct1 and fct2 are present in the training data. This might be a bug since with the older version my analysis performs well and provides reasonable results.

```
library(raster)
library(randomForest)

# create training data
response <- c(rep(1,10), rep(0,10))
fct1 <- c(160,160,30,160,160,40,12,40,160,30,160,11,160,40,11,12,50,11,50,50)
fct2 <- c(3,3,7,7,7,7,3,7,3,7,4,8,4,10,3,3,7,8,10,4)
dbl1 <- c(4208,4310,8569,4091,5681,5102,4214,4750,4389,6021,4732,5065,6027,6308,4910,4578,6460,4770,6220,7387)
dbl2 <- c(0.58,0.58,0.74,0.55,0.56,0.28,0.59,0.65,0.50,0.49,0.59,0.45,0.65,0.83,0.63,0.60,0.65,0.78,0.70,0.75)

d <- as.data.frame(cbind(response, fct1, fct2, dbl1, dbl2))
d$fct1 <- as.factor(d$fct1)
d$fct2 <- as.factor(d$fct2)

# form RF model
xpred <- d[,2:5]
ydep <- as.factor(d[,1])
rf <- randomForest(x = xpred, y = ydep)

# create new data for prediction
fct1 <- raster(nrows = 10, ncols = 10)
v1 <- c(12,12,12,30,30,30,30,30,30,12,30,30,30,30,40,30,30,30,30,12,40,40,40,40,40,30,30,30,30,12,40,40,40,40,40,30,30,30,30,12,30,30,30,30,12,40,40,30,12,12,30,12,12,30,12,30,30,30,12,30,30,30,30,12,12,30,30,30,40,30,30,30,30,12,12,30,30,30,40,30,12,12,12,12,30,30,30,30,40,11,12,12,12,12,12,30,30,30,30,30)
values(fct1) <- v1

fct2 <- raster(nrows = 10, ncols = 10)
v2 <- c(7,8,7,7,8,7,7,7,8,8,7,8,8,8,8,8,8,7,8,7,8,8,8,8,8,8,8,8,7,7,8,8,8,8,8,8,8,8,8,7,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,7,7,8,8,8,8,8,8,8,8,8,7,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8)
values(fct2) <- v2

dbl1 <- raster(nrows = 10, ncols = 10)
values(dbl1) <- c(6393,6088,5844,5848,6641,6611,7004,7465,7867,7997,6304,6655,6863,6450,6530,6611,6912,7519,7852,7988,6484,6406,6482,6137,6344,6451,6554,
7254,7734,8017,6438,6361,6571,6276,6166,6519,6599,6630,7006,7720,6410,6471,6710,6833,6920,7026,6887,6858,7251,7595,6467,6634,6813,7010,
7187,7310,7438,7253,7723,7758,6635,6862,7092,7208,7251,7380,7600,7569,7565,7622,6989,7055,6985,7201,7167,7183,7210,7330,7547,7628,7240,
7176,7284,7362,7338,7287,7010,7024,7245,7594,7297,7342,7432,7558,7420,7147,7076,7024,7051,7211)

dbl2 <- raster(nrows = 10, ncols = 10)
values(dbl2) <- c(0.30,0.35,0.35,0.39,0.39,0.45,0.45,0.47,0.47,0.49,0.33,0.74,0.74,0.75,0.75,0.41,0.41,0.89,0.89,0.40,0.33,0.74,0.74,0.75,0.75,0.41,0.41,
0.89,0.89,0.40,0.87,0.66,0.66,0.73,0.73,0.41,0.41,0.45,0.45,0.45,0.87,0.66,0.66,0.73,0.73,0.41,0.41,0.45,0.45,0.45,0.87,0.44,0.44,0.40,
0.40,0.91,0.91,0.92,0.92,0.91,0.87,0.44,0.44,0.40,0.40,0.91,0.91,0.92,0.92,0.91,0.45,0.51,0.51,0.43,0.43,0.51,0.51,0.92,0.92,0.88,0.45,
0.51,0.51,0.43,0.43,0.51,0.51,0.92,0.92,0.88,0.48,0.55,0.55,0.40,0.40,0.63,0.63,0.50,0.50,0.50)

newdata <- stack(fct1, fct2, dbl1, dbl2)
names(newdata) <- c("fct1", "fct2", "dbl1", "dbl2")

# predict
pred <- predict(newdata, rf, type = "prob", index = 2)
```

**Comment by jaywt** [comment]
I would like to second to this issue.

I had a random forest model trained before. My dataset is a bunch of raster files. The prediction results (using raster::predict) of this trained model using raster 3.02 yield pretty reasonable results. However, last week I updated to raster 3.07 (from 3.02). Prediction results (using raster::predict) yield many hollow area which do not make sense to me.

**Comment by jaywt** [comment]
> I would like to second to this issue.
> 
> I had a random forest model trained before. My dataset is a bunch of raster files. The prediction results (using raster::predict) of this trained model using raster 3.02 yield pretty reasonable results. However, last week I updated to raster 3.07 (from 3.02). Prediction results (using raster::predict) yield many hollow area which do not make sense to me.

To add some context, i have successfully reproduced this problem/issue in Windows (7 and 10) and MacOS. Rstudio version is 1.2.5001 while R version is 3.6.1

**Comment by rhijmans** [comment]
believe this has been fixed in the development version. I would appreciate confirmation.  Will send this to CRAN soon.

**Comment by vvirkki** [comment]
Works for both the reproducible example and my application. Thanks for fixing!
