### ISSUE TITLE
parallel version of 'extract' function returns `SpatialPolygons` with wrong attribute value relationships

### ISSUE THREAD

**Issue by Jacory** [rspatial/raster#79]
The parallel version of the 'extract' function with spatial polygons can retrieve values from 'RasterStack' and 'RasterBrick', which is faster than the serial version. By specifying the parameter 'sp=TRUE', it returns the 'SpatialPolygons' object with the extracted value from the images. 

But, there is an issue. The order of returned values is random, they should not be linked to the correct attribute values such as 'ID' and 'Name'. 

For example, suppose we have 4 polygons with ID equals '1', '2', '3', and '4', named 'A', 'B', 'C', and 'D', we use them to retrieve the median value of 'RasterStack' pixels within their boundary.  The correct case is that the 'extract' function gives us a table looks like this:

| ID | Name | Median Value |
|----|--------|------|
| 1  | A | 0.7   |
| 2  | B | 0.5   |
| 3  | C | 0.8   |
| 4  | D | 0.9   |

this is the serial version of 'extract' function returns, and it is correct. However, if you change to the parallel version of 'extract', it returns:

| ID | Name | Median Value |
|----|--------|------|
| 1  | A | 0.5   |
| 2  | B | 0.7   |
| 3  | C | 0.9   |
| 4  | D | 0.8   |

The values are correct, they are just in a different order, but the ID and Name values should not be linked with them.

Now, we only find this issue happens on 'RasterStack', 'RasterBrick' and 'SpatialPolygon' with a `fun` parameter specified.

Thanks to my advisor Josh Gray,  here is code for a minimum reproducible example:

```r
library(raster)
library(parallel)

set.seed(42)
r <- raster(matrix(rnorm(1e2 ^ 2), nrow = 100))
s <- stack(r, r)
proj4string(s) <- CRS("+proj=utm +zone=10 +datum=WGS84")

num_pts <- 4 # Note: no problem w/ 2 or 3 points
tmp_sp <- data.frame(x = runif(num_pts, 0, 1), y = runif(num_pts, 0, 1), id = 1:num_pts, y = sample(LETTERS, num_pts))
coordinates(tmp_sp) <- ~x + y
proj4string(tmp_sp) <- CRS("+proj=utm +zone=10 +datum=WGS84")
extract_polys <- buffer(tmp_sp, width = 0.05, dissolve = F)

# Now do the extraction w/o a cluster
tmp_srl <- extract(s, extract_polys, sp = T, fun = median)

# Now do the extraction w/ a cluster
beginCluster(detectCores() - 1) # in our case, a 7 node socket cluster
tmp_par <- extract(s, extract_polys, sp = T, fun = median)
endCluster()

# compare results
identical(tmp_srl, tmp_par)
# [1] FALSE
tmp_srl@data # Note: results maybe slightly different due to randomness
# id y.1     layer.1     layer.2
# 1  1   G -0.08397351 -0.08397351
# 2  2   I  0.22009926  0.22009926
# 3  3   E  0.28864574  0.28864574
# 4  4   L  0.06944213  0.06944213
tmp_par@data # Note: results maybe slightly different due to randomness
# id y.1     layer.1     layer.2
# 1  1   G -0.08397351 -0.08397351
# 2  2   I  0.28864574  0.28864574
# 3  3   E  0.22009926  0.22009926
# 4  4   L  0.06944213  0.06944213
```

**Comment by rhijmans** [comment]
Thank you very much for reporting this. This has been fixed in version 3.0-9.
