### ISSUE TITLE
`extract` fails on a raster created from a `big.matrix`.

### ISSUE THREAD

**Issue by barryrowlingson** [rspatial/raster#80]
Trying `extract` on a raster created from a big.matrix tells me there's a problem...

```
> library(raster)
Loading required package: sp
> library(bigmemory)
> m = matrix(1:12, 3, 4)
> r1 = raster(m)
> r2 = raster(as.big.matrix(m))
> pts = SpatialPoints(cbind(seq(0,1,len=10),seq(0,1,len=10)))
> extract(r1,pts)
 [1]  3  3  3  6  5  8  8 10 10 10
> extract(r2,pts)
Error in .readCells(x, cells, 1) : 
  I did not expect the code to get here. Please report

```

In the above, `r1` is created from a matrix and behaves normally, `r2` is created from a `big.matrix` from the `bigmemory` package and behaves oddly:

```
> values(r2)
Error in .local(.Object, ...) : empty file name
```

I only tried this after seeing the S4 method in the `?raster` docs:

```
     ## S4 method for signature 'big.matrix'
     raster(x, xmn=0, xmx=1, ymn=0, ymx=1, crs=NA, template=NULL)
```

and wondering what a `big.matrix` was.

```
> packageVersion("raster")
[1] ‘3.0.7’
> packageVersion("bigmemory")
[1] ‘4.5.33’
```

**Comment by rhijmans** [comment]
A long, long, time ago, I added support for `big.matrix` as a raster data storage format (together with a header file). The idea was that some computations could be faster. But shortly after that, bigmemory became unavailable for windows for a couple of years, so I did not pursue it further and removed some of the functionality. I have now removed all references and commented out all the code to avoid confusion about this.
