### ISSUE TITLE
getValues errors for netCDF brick with transposed dimensions

### ISSUE THREAD

**Issue by kasselhingee** [rspatial/raster#83]
netCDF files with dimensions of (latitude, longitude, time) are not read properly when using the "dims" argument in brick()

       b <- brick("http://dapds00.nci.org.au/thredds/dodsC/ub8/au/OzWALD/annual/OzWALD.annual.Pg.AnnualSums.nc", 
               dims = c(2, 1, 3))
       getValues(b, 1, 1)

Produces an error:

       > Error in Rsx_nc4_get_vara_double: NetCDF: Index exceeds dimension bound
       > Var: AnnualSums  Ndims: 3   Start: 0,0,0 Count: 19,1,841
       > Error in ncvar_get_inner(ncid2use, varid2use, nc$var[[li]]$missval, addOffset,  : 
       >   C function R_nc4_get_vara_double returned error

This particular error was related to the count value not putting the dimensions in the order of the file on disk. I had a first attempt at fixing this by rearranging 'start' and 'count' vectors in every call to ncvar_get to match the dimension ordering, however I am missing something. It removed the above error code, however plot(b, 1) did not give a figure representing the data (annual rainfall for Australia): the plot was full of striations.

**Comment by rhijmans** [comment]
I do not have access to this file.   `download.file("http://dapds00.nci.org.au/thredds/dodsC/ub8/au/OzWALD/annual/OzWALD.annual.Pg.AnnualSums.nc", "test.nc")` does not work.  
It perhaps requires a login? Can you make it available to me (privately)?

**Comment by mdsumner** [comment]
It's a thredds link, so it works remotely via ncdf4 already. I think this is the file itself: 

http://dapds00.nci.org.au/thredds/fileServer/ub8/au/OzWALD/annual/OzWALD.annual.Pg.AnnualSums.nc

**Comment by rhijmans** [comment]
OK, thanks. I can reproduce this now.  And offer this work-around:

`b <- brick("OzWALD.annual.Pg.AnnualSums.nc")`
`b <- flip( t(b),  "x")`

I have seen the pull request to fix it, and will look at that when I can.

**Comment by kasselhingee** [comment]
Thank you Robert. I hope the modifications in my pull request fits well with your plans for the raster package.

My fear with using t() is that it appears to load the raster values into memory.

```
b <- brick("http://dapds00.nci.org.au/thredds/dodsC/ub8/au/OzWALD/annual/OzWALD.annual.Pg.AnnualSums.nc")
bt <- flip( t(b), "x")
inMemory(b)  #FALSE 
inMemory(bt)  #TRUE
```

**Comment by rhijmans** [comment]
It should go to disk if the data-set is large. But it is a *work-around*, not a solution.

**Comment by mdsumner** [comment]
I'd be cutting into this more directly personally, once you get over orientation you can read the *wrong way* and interpret afterwards

**Comment by rhijmans** [comment]
I have accepted your pull request (https://github.com/rspatial/raster/pull/84/)
