### ISSUE TITLE
Installing Error in centos 7

### ISSUE THREAD

**Issue by zillurbmb51** [rspatial/raster#86]
Hello; I was trying to install this excellent tool :+1: 
install.packages("raster", repos="http://R-Forge.R-project.org")
 Any Help?
`* building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
sh: line 1: 68407 Segmentation fault      (core dumped) '/usr/lib64/R/bin/R' --no-save --slave 2>&1 < '/tmp/RtmpYdeFMf/file10a8b192707a2'

 *** caught segfault ***
address 0x20, cause 'memory not mapped'

Traceback:
 1: Module(module, mustStart = TRUE, where = env)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)
 5: tryCatch(Module(module, mustStart = TRUE, where = env), error = function(e) e)
 6: loadModule(module = "spmod", what = TRUE, env = ns, loadNow = TRUE)
 7: (function (ns) loadModule(module = "spmod", what = TRUE, env = ns, loadNow = TRUE))(<environment>)
 8: doTryCatch(return(expr), name, parentenv, handler)
 9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch((function (ns) loadModule(module = "spmod", what = TRUE, env = ns, loadNow = TRUE))(<environment>),     error = function(e) e)
12: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e),     list(FUN = f, WHERE = where)), where)
13: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e),     list(FUN = f, WHERE = where)), where)
14: .doLoadActions(where, attach)
15: methods::cacheMetaData(ns, TRUE, ns)
16: loadNamespace(package, lib.loc)
17: doTryCatch(return(expr), name, parentenv, handler)
18: tryCatchOne(expr, names, parentenv, handlers[[1L]])
19: tryCatchList(expr, classes, parentenv, handlers)
20: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
21: library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE)
22: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
23: suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE))
24: doTryCatch(return(expr), name, parentenv, handler)
25: tryCatchOne(expr, names, parentenv, handlers[[1L]])
26: tryCatchList(expr, classes, parentenv, handlers)
27: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
28: try(suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE)))
29: tools:::.test_load_package("raster", "/home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/00LOCK-raster/00new")
An irrecoverable exception occurred. R is aborting now ...
ERROR: loading failed
* removing ‘/home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/raster’
Warning in install.packages :
  installation of package 'raster' had non-zero exit status

The downloaded source packages are in
	'/tmp/Rtmp876yMj/downloaded_packages'`

**Comment by Marc-Girondot** [comment]
Perhaps is the same than:
https://github.com/rspatial/raster/issues/63

**Comment by zillurbmb51** [comment]
Yes, in my mac also the same problem. Is there any solution of this?

**Comment by Marc-Girondot** [comment]
I have tried to find a solution since 3 months... nothing except using the 2.5-8 version:
require(devtools)
install_version("raster", version = "2.5-8", repos =
"http://cran.us.r-project.org")

**Comment by Marc-Girondot** [comment]
For the problem in Mac, I have uninstalled R, all the libraries, Rstudio and the .R and .rstudio hidden directories. I have installed again a fresh R 3.6.2 and raster package (from CRAN binary): No more segfault when the package is loaded
I have installed again half of the packages that I had installed. I have still no problem with raster 3.0-7 package.

I try with the 3.0-10 from GitHub installed from source... and no problem !

**Comment by ciaron** [comment]
My fix was to reinstall "Rcpp". I'm not sure why this worked, but it might be that I originally installed it with non-standard options in Makevars. Reinstalling everything isn't always an option (if my case: a central R installation on a HPC cluster)
