### ISSUE TITLE
getData(name="countries") - Could not download file

### ISSUE THREAD

**Issue by RS-eco** [rspatial/raster#89]
For some reason, I cannot download/load the countries_gadm36_sp.rds file.
When I run:

```
library(raster)
getData(name="countries")
```

I get following output:

> trying URL 'https://biogeo.ucdavis.edu/data/gadm3.6/countries_gadm36_sp.rds'
> Content type 'text/html; charset=iso-8859-1' length 138347516 bytes (131.9 MB)
> downloaded 131.9 MB 
> Could not download file -- perhaps it does not exist

When I download the file manually and try to load it into R, I get the following error:

> Error in load() : bad restore file magic number (file may be corrupted) -- no data loaded
> In addition: Warning message: file ‘countries_gadm36_sp.rds’ has magic number 'X'
> Use of save versions prior to 2 is deprecated

I am using R version 3.6.2 and raster version 3.0-7.

**Comment by rhijmans** [comment]
I cannot tell you why the download fails. Permission to write to home directory? The other error seems related to using "load" rather than `readRDS(filename)`

**Comment by RS-eco** [comment]
Okay, `readRDS(filename)` works:

```{r}
dat <- readRDS("/media/matt/Data/Documents/Wissenschaft/Data/GADM/countries_gadm36_sp.rds")
```

but should `getData()` not recognise that the file is already present under the specified path:

```{r}
getData(name="countries", path="/media/matt/Data/Documents/Wissenschaft/Data/GADM/")
```

Running the above command, still tries to download the file, although it is already available in the directory, and fails to download the file.
