### ISSUE TITLE
raster::predict producing only NA with caret random forest

### ISSUE THREAD

**Issue by yPennylane** [rspatial/raster#91]
Consider the following code as in issue [https://github.com/rspatial/raster/issues/68](url):

    library(caret)
    library(raster)
    
    # create example data
    dat <- data.frame(ID=1:4, value = letters[1:4], stringsAsFactors=FALSE)
    crs <- "+proj=utm +zone=33 +ellps=GRS80 +units=m"
    pols <- spPolygons(
        cbind(c(45,45.7,46,45.3,45),c(54,54.1,54.7,54.6,54)),
        cbind(c(45.25,45.3,45.45,45.7,45.7),c(54.2,54.4,54.6,54.5,54.2)),
        cbind(c(44.1,44.8,44.9,44.2, 44.1), c(54.1,54.2,54.5,54.6, 54.1)),
        cbind(c(44.3,45.5,45.7,45,44.1,44.3), c(54.6,55,55.7,55.8,55.5,54.6)),
        attr=dat, crs=crs)
    
    r1 <- r2 <- r3 <- raster(ncol=10, nrow=10, ext=extent(c(44,46,54,56)), crs = crs)
    values(r1) <- 1:ncell(r1)
    set.seed(42)
    values(r2) <- sample(0:10, ncell(r2), replace = TRUE)
    values(r3) <- as.factor(sample(letters[1:4], ncell(r3), replace = TRUE))
    r4 <- rasterize(x = pols, y = r1, field = "ID")
    rs <- stack(r1, r2, r3, r4)
    names(rs) <- c("r1", "r2", "r3", "r4")
    s <- mask(rs, pols)
    
    # create data frame for model building
    set.seed(42)
    mat <- extract(s, sample(1:100, 40))
    df <- na.omit(as.data.frame(mat))
    
    # assign factors again to factor variables
    facs <- c("a", "b", "c", "d")
    df$r3 <- as.factor(facs[df$r3])
    df$r4 <- as.factor(facs[df$r4])
    
    # build model
    preds <- df[, c("r1", "r3", "r4")]
    set.seed(42, kind = "Mersenne-Twister", normal.kind = "Inversion")
    tunegrid <- expand.grid(mtry=c(1:ncol(preds)))
    control <- caret::trainControl(search="grid", method="repeatedcv", number=3, repeats=3)
    
    model <- caret::train(x = preds, y = df$r2, method = "rf", ntree = 50,  tuneGrid = tunegrid, trControl = control, importance = TRUE)
    
    f <- list(r3=levels(df$r3), r4=levels(df$r4))
    
    # predict to Raster
    test <- raster::predict(s, model, factors = f)
    test

The raster `test` consists of NAs only and the code did not produce any error message. If I do the prediction without the rasterized object r4, the resulting raster still only contains NAs. I think it is because of the factors inside the model being not numbers but letters. If they are factors containing numbers, then it is working. 
I am using R version 3.6.2 and raster version 3.0-12.

The issue was fixed in version 3.0-3 and it still did work in version 3.0-7, but the problem occurs again in raster version 3.0-12.
Could you please fix the issue?

**Comment by rhijmans** [comment]
Apologies for the long delay. I rewrote this method to simplify it, and make it easier to maintain. It has been a pain every since. Thank you for helping fix it.

**Comment by yPennylane** [comment]
Thank you for your reply. I still have raster version 3.0-7 installed, so it works. I also have created a workaround that uses caret::predict. I am using dataframes instead of matrices. My workaround is slower than the raster::predict, but it produces the same results. 

Are you going to fix it in the next raster version?
