### ISSUE TITLE
Issue with mask and Polygon containing hole

### ISSUE THREAD

**Issue by philreiter** [rspatial/raster#93]
Hi all,
I stumbled upon an possible issue, not sure if it is meant to be that way, at least it's not obvious for me to work that way: 
When masking a grid with a non-disaggregated multipart polygon feature, where one of the polygons has a hole, the hole is not masked out. However, when masking with the disaggregated polygon feature it is working. Trying a workaround with rasterizing first resulted in the same issue.

See the example below:

`library(raster)`
`library(rgeos)`
`grid <- raster(matrix(1,100,100),xmn=0,xmx=100,ymn=0,ymx=100)`
`point <- SpatialPoints(matrix(c(50,50),nrow=1))`
`ring <- gDifference(gBuffer(point,width=30),gBuffer(point,width=10))`
`plot(mask(grid,ring)) ## working`
`joint <- gUnion(gBuffer(SpatialPoints(matrix(c(20,20),nrow=1)),width=10),ring)`
`plot(mask(grid,joint)) ## not working`
`plot(rasterize(joint,grid)) ## not working`
`plot(mask(grid,disaggregate(joint))) ## working`
`plot(rasterize(disaggregate(joint),grid)) ## working but needs values fixed afterwards`

sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rgeos_0.5-2  raster_3.0-7 sp_1.3-2    

loaded via a namespace (and not attached):
[1] compiler_3.6.2   Rcpp_1.0.3       codetools_0.2-16 grid_3.6.2      
[5] lattice_0.20-38

Would be great to get a feedback on whether I'm getting something wrong here.

Best regards
Philipp

**Comment by rhijmans** [comment]
Thank you for reporting. The underlying cause is that SpatialPolygons do not record to which sub-polygon a hole belongs to. But I have improved the way raster guesses this. Further checks could be implemented in the future.

**Comment by mdsumner** [comment]
They do record it sometimes in the obscure comment created by `rgeos::createSPComment` . 

```R
comment(ring@polygons[[1]])
[1] "0 1"  ## second coords belongs to first coords
```
