### ISSUE TITLE
cliping a raster object to polygon boundaries using mask function from package raster

### ISSUE THREAD

**Issue by ArseneKIEMA** [rspatial/raster#94]
Hi dear all,
I'm trying to clip a raster object to polygon boundaries using the following code:
```
 # Raster object
read.data. <- brick("C:/Users/User/Documents/Memoire/donnees/Temperature/JRA-55/Tmax/Tmax_19610101.nc")
# The shape file to be use for cliping the raster object

shp_nowkuy2 <- readOGR(dsn=paste(getwd(), "geospacial_data", sep = "/"), layer = "Nowkuysubbasins")
rast_mask<- raster::mask(read.data.,shp_nowkuy2)`
```
Unfortunatly I got an error message. Here is that message:

`Error in ncvar_get_inner(ncid2use, varid2use, nc$var[[li]]$missval, addOffset,  : 
  Error: variable has 2 dims, but start has 3 entries.  They must match!`

Very solution to that issue will be greatly appreciate.
Thank you in advance.

**Comment by rhijmans** [comment]
That looks like a problem with the file. I do not have the file, so I cannot further comment.
