### ISSUE TITLE
Attempting to writeRaster with a rasterblock fails

### ISSUE THREAD

**Issue by GeraldCNelson** [rspatial/raster#99]
I read in a netcdf file with climate data (1 variable, three dimensions, 5 years of data) with the following command
`fileNameIn <- "/Volumes/PassportMac/ISIMIP/cmip6/ssp585/MPI-ESM1-2-HR/mpi-esm1-2-hr_r1i1p1f1_w5e5_ssp585_hurs_global_daily_2015_2020.nc"`
`temp <- brick(fileNameIn, varname="hurs")`

Then I attempt to write it back out as a grid
`writeRaster(temp, fileName = "data/landOnly_temp.grd", format = "raster")`

I get this error message

> Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function ‘writeRaster’ for signature ‘"RasterBrick", "missing"’

I get the same error message if I read it in as a stack with 
`temp <- stack(fileNameIn, varname="hurs")`
and then attempt to write it out with writeRaster

I'm using raster version 3.0-12.

**Comment by Nowosad** [comment]
Have you tried:
```r
writeRaster(temp, filename = "data/landOnly_temp.grd", format = "raster")
```

**Comment by rhijmans** [comment]
As Jakub points out, the second argument should be `filename`, not `fileName`. And it should also work like this `writeRaster(temp, "data/landOnly_temp.grd")`  (assuming that the `data` folder exists`)

**Comment by GeraldCNelson** [comment]
I can't believe how many errors I made in that one line of code. The suffix should be 'gri' instead of 'grd'. And it's filename instead of fileName. My only excuse is that the error message isn't exactly clear about what the problems were.

And only a completely different subject is there any way to turn off autocorrect in this GitHub website?
